const ARMOR_PASSIVES = [
  {
    displayName: 'Advanced Filtration',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'advancedfiltration',
    imageURL: 'advancedfiltration.png',
    tier: 'b',
  },
  {
    displayName: 'Acclimated',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'acclimated',
    imageURL: 'acclimated.png',
    tier: 'b',
  },
  {
    displayName: 'Democracy Protects',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'democracyprotects',
    imageURL: 'democracyprotects.png',
    tier: 'b',
  },
  {
    displayName: 'Electrical Conduit',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: 'Cutting Edge',
    warbondCode: '',
    internalName: 'electricalconduit',
    imageURL: 'electricalconduit.png',
    tier: 'b',
  },
  {
    displayName: 'Engineering Kit',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'engineeringkit',
    imageURL: 'engineeringkit.png',
    tier: 'b',
  },
  {
    displayName: 'Extra Padding',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'extrapadding',
    imageURL: 'extrapadding.png',
    tier: 'b',
  },
  {
    displayName: 'Fortified',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'fortified',
    imageURL: 'fortified.png',
    tier: 'b',
  },
  {
    displayName: 'Inflammable',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'inflammable',
    imageURL: 'inflammable.png',
    tier: 'b',
  },
  {
    displayName: 'Med-Kit',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'medkit',
    imageURL: 'medkit.png',
    tier: 'b',
  },
  {
    displayName: 'Peak Physique',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'peakphysique',
    imageURL: 'peakphysique.png',
    tier: 'b',
  },
  {
    displayName: 'Scout',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'scout',
    imageURL: 'scout.png',
    tier: 'b',
  },
  {
    displayName: 'Servo-Assisted',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'servoassisted',
    imageURL: 'servoassisted.png',
    tier: 'b',
  },
  {
    displayName: 'Unflinching',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'unflinching',
    imageURL: 'unflinching.png',
    tier: 'b',
  },
  {
    displayName: 'Siege Ready',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'siegeready',
    imageURL: 'siegeready.png',
    tier: 'b',
  },
  {
    displayName: 'Integrated Explosives',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'integratedexplosives',
    imageURL: 'integratedexplosives.png',
    tier: 'b',
  },
  {
    displayName: 'Gunslinger',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorPassive'],
    warbond: '',
    warbondCode: '',
    internalName: 'gunslinger',
    imageURL: 'gunslinger.png',
    tier: 'b',
  },
];
