const ARMOR_SETS = [
  {
    displayName: "AF-50 Noxious Ranger",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Advanced Filtration",
    warbondCode: "warbond10",
    internalName: "af50noxiousranger",
    imageURL: "af50noxiousranger.webp",
    tier: "b",
    index: 0,
  },
  {
    displayName: "AC-2 Obedient",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Acclimated",
    warbondCode: "warbond18",
    internalName: "ac2obedient",
    imageURL: "ac2obedient.webp",
    tier: "b",
    index: 1,
  },
  {
    displayName: "SR-24 Street Scout",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Siege Ready",
    warbondCode: "warbond12",
    internalName: "sr24streetscout",
    imageURL: "sr24streetscout.webp",
    tier: "b",
    index: 2,
  },
  {
    displayName: "SR-18 Road Block",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Siege Ready",
    warbondCode: "warbond12",
    internalName: "sr18roadblock",
    imageURL: "sr18roadblock.webp",
    tier: "b",
    index: 3,
  },
  {
    displayName: "B-08 Light Gunner",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 100,
    speed: 125,
    stamina: 550,
    passive: "Extra Padding",
    warbondCode: "warbond1",
    internalName: "b08lightgunner",
    imageURL: "b08lightgunner.webp",
    tier: "b",
    index: 4,
  },
  {
    displayName: "CE-07 Demolition Specialist",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 64,
    speed: 536,
    stamina: 118,
    passive: "Engineering Kit",
    warbondCode: "warbond6",
    internalName: "ce07demolitionspecialist",
    imageURL: "ce07demolitionspecialist.webp",
    tier: "b",
    index: 5,
  },
  {
    displayName: "CE-67 Titan",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 79,
    speed: 521,
    stamina: 111,
    passive: "Engineering Kit",
    warbondCode: "warbond1",
    internalName: "ce67titan",
    imageURL: "ce67titan.webp",
    tier: "b",
    index: 6,
  },
  {
    displayName: "CE-74 Breaker",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Engineering Kit",
    warbondCode: "warbond1",
    internalName: "ce74breaker",
    imageURL: "ce74breaker.webp",
    tier: "b",
    index: 7,
  },
  {
    displayName: "CM-21 Trench Paramedic",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 64,
    speed: 536,
    stamina: 118,
    passive: "Med-Kit",
    warbondCode: "warbond1",
    internalName: "cm21trenchparamedic",
    imageURL: "cm21trenchparamedic.webp",
    tier: "b",
    index: 8,
  },
  {
    displayName: "CW-4 Arctic Ranger",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Scout",
    warbondCode: "warbond7",
    internalName: "cw4arcticranger",
    imageURL: "cw4arcticranger.webp",
    tier: "b",
    index: 9,
  },
  {
    displayName: "EX-00 Prototype X",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Electrical Conduit",
    warbondCode: "warbond5",
    internalName: "ex00prototypex",
    imageURL: "ex00prototypex.webp",
    tier: "b",
    index: 10,
  },
  {
    displayName: "FS-37 Ravager",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Engineering Kit",
    warbondCode: "warbond1",
    internalName: "fs37ravager",
    imageURL: "fs37ravager.webp",
    tier: "b",
    index: 11,
  },
  {
    displayName: "FS-38 Eradicator",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Fortified",
    warbondCode: "warbond1",
    internalName: "fs38eradicator",
    imageURL: "fs38eradicator.webp",
    tier: "b",
    index: 12,
  },
  {
    displayName: "I-09 Heatseeker",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Inflammable",
    warbondCode: "warbond9",
    internalName: "i09heatseeker",
    imageURL: "i09heatseeker.webp",
    tier: "b",
    index: 13,
  },
  {
    displayName: "PH-9 Predator",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Peak Physique",
    warbondCode: "warbond8",
    internalName: "ph9predator",
    imageURL: "ph9predator.webp",
    tier: "b",
    index: 14,
  },
  {
    displayName: "SC-30 Trailblazer Scout",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Scout",
    warbondCode: "warbond3",
    internalName: "sc30trailblazerscout",
    imageURL: "sc30trailblazerscout.webp",
    tier: "b",
    index: 15,
  },
  {
    displayName: "SC-34 Infiltrator",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 70,
    speed: 530,
    stamina: 115,
    passive: "Scout",
    warbondCode: "warbond3",
    internalName: "sc34infiltrator",
    imageURL: "sc34infiltrator.webp",
    tier: "b",
    index: 16,
  },
  {
    displayName: "SC-37 Legionnaire",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Servo-Assisted",
    warbondCode: "warbond1",
    internalName: "sc37legionnaire",
    imageURL: "sc37legionnaire.webp",
    tier: "b",
    index: 17,
  },
  {
    displayName: "UF-16 Inspector",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 75,
    speed: 550,
    stamina: 125,
    passive: "Unflinching",
    warbondCode: "warbond11",
    internalName: "uf16inspector",
    imageURL: "uf16inspector.webp",
    tier: "b",
    index: 18,
  },
  {
    displayName: "AF-02 Haz-Master",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Advanced Filtration",
    warbondCode: "warbond10",
    internalName: "af02hazmaster",
    imageURL: "af02hazmaster.webp",
    tier: "b",
    index: 19,
  },
  {
    displayName: "AF-91 Field Chemist",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Advanced Filtration",
    warbondCode: "warbond1",
    internalName: "af91fieldchemist",
    imageURL: "af91fieldchemist.webp",
    tier: "b",
    index: 20,
  },
  {
    displayName: "B-01 Tactical",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 150,
    speed: 500,
    stamina: 100,
    passive: "Extra Padding",
    warbondCode: "none",
    internalName: "b01tactical",
    imageURL: "b01tactical.webp",
    tier: "b",
    index: 21,
  },
  {
    displayName: "B-24 Enforcer",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 129,
    speed: 471,
    stamina: 71,
    passive: "Fortified",
    warbondCode: "warbond1",
    internalName: "b24enforcer",
    imageURL: "b24enforcer.webp",
    tier: "b",
    index: 22,
  },
  {
    displayName: "CE-27 Ground Breaker",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Engineering Kit",
    warbondCode: "warbond6",
    internalName: "ce27groundbreaker",
    imageURL: "ce27groundbreaker.webp",
    tier: "b",
    index: 23,
  },
  {
    displayName: "CE-35 Trench Engineer",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Engineering Kit",
    warbondCode: "warbond3",
    internalName: "ce35trenchengineer",
    imageURL: "ce35trenchengineer.webp",
    tier: "b",
    index: 24,
  },
  {
    displayName: "CE-81 Juggernaut",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Engineering Kit",
    warbondCode: "warbond1",
    internalName: "ce81juggernaut",
    imageURL: "ce81juggernaut.webp",
    tier: "b",
    index: 25,
  },
  {
    displayName: "CM-09 Bonesnapper",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Med-Kit",
    warbondCode: "warbond3",
    internalName: "cm09bonesnapper",
    imageURL: "cm09bonesnapper.webp",
    tier: "b",
    index: 26,
  },
  {
    displayName: "CM-10 Clinician",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Med-Kit",
    warbondCode: "warbond1",
    internalName: "cm10clinician",
    imageURL: "cm10clinician.webp",
    tier: "b",
    index: 27,
  },
  {
    displayName: "CM-14 Physician",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Med-Kit",
    warbondCode: "warbond3",
    internalName: "cm14physician",
    imageURL: "cm14physician.webp",
    tier: "b",
    index: 28,
  },
  {
    displayName: "CW-9 White Wolf",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 150,
    speed: 500,
    stamina: 100,
    passive: "Extra Padding",
    warbondCode: "warbond1",
    internalName: "cw9whitewolf",
    imageURL: "cw9whitewolf.webp",
    tier: "b",
    index: 29,
  },
  {
    displayName: "DP-00 Tactical",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Democracy Protects",
    warbondCode: "none",
    internalName: "dp00tactical",
    imageURL: "dp00tactical.webp",
    tier: "b",
    index: 30,
  },
  {
    displayName: "DP-11 Champion of the People",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Democracy Protects",
    warbondCode: "warbond3",
    internalName: "dp11championofthepeople",
    imageURL: "dp11championofthepeople.webp",
    tier: "b",
    index: 31,
  },
  {
    displayName: "AC-1 Dutiful",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Acclimated",
    warbondCode: "warbond18",
    internalName: "ac1dutiful",
    imageURL: "ac1dutiful.webp",
    tier: "b",
    index: 32,
  },
  {
    displayName: "DP-40 Hero of the Federation",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Democracy Protects",
    warbondCode: "warbond3",
    internalName: "dp40heroofthefederation",
    imageURL: "dp40heroofthefederation.webp",
    tier: "b",
    index: 33,
  },
  {
    displayName: "DP-53 Savior of the Free",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Democracy Protects",
    warbondCode: "warbond0",
    internalName: "dp53saviorofthefree",
    imageURL: "dp53saviorofthefree.webp",
    tier: "b",
    index: 34,
  },
  {
    displayName: "EX-03 Prototype 3",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Electrical Conduit",
    warbondCode: "warbond5",
    internalName: "ex03prototype3",
    imageURL: "ex03prototype3.webp",
    tier: "b",
    index: 35,
  },
  {
    displayName: "EX-16 Prototype 16",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Electrical Conduit",
    warbondCode: "warbond5",
    internalName: "ex16prototype16",
    imageURL: "ex16prototype16.webp",
    tier: "b",
    index: 36,
  },
  {
    displayName: "FS-34 Exterminator",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Fortified",
    warbondCode: "warbond1",
    internalName: "fs34exterminator",
    imageURL: "fs34exterminator.webp",
    tier: "b",
    index: 37,
  },
  {
    displayName: "I-92 Fire Fighter",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Inflammable",
    warbondCode: "warbond1",
    internalName: "i92firefighter",
    imageURL: "i92firefighter.webp",
    tier: "b",
    index: 38,
  },
  {
    displayName: "I-102 Draconaught",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Inflammable",
    warbondCode: "warbond9",
    internalName: "i102draconaught",
    imageURL: "i102draconaught.webp",
    tier: "b",
    index: 39,
  },
  {
    displayName: "PH-56 Jaguar",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Peak Physique",
    warbondCode: "warbond1",
    internalName: "ph56jaguar",
    imageURL: "ph56jaguar.webp",
    tier: "b",
    index: 40,
  },
  {
    displayName: "SA-04 Combat Technician",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Scout",
    warbondCode: "warbond3",
    internalName: "sa04combattechnician",
    imageURL: "sa04combattechnician.webp",
    tier: "b",
    index: 41,
  },
  {
    displayName: "SA-12 Servo Assisted",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Servo-Assisted",
    warbondCode: "warbond4",
    internalName: "sa12servoassisted",
    imageURL: "sa12servoassisted.webp",
    tier: "b",
    index: 42,
  },
  {
    displayName: "SA-25 Steel Trooper",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Servo-Assisted",
    warbondCode: "warbond4",
    internalName: "sa25steeltrooper",
    imageURL: "sa25steeltrooper.webp",
    tier: "b",
    index: 43,
  },
  {
    displayName: "SA-15 Drone Master",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Servo-Assisted",
    warbondCode: "warbond1",
    internalName: "sc15dronemaster",
    imageURL: "sc15dronemaster.webp",
    tier: "b",
    index: 44,
  },
  {
    displayName: "TR-7 Ambassador of the Brand",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 150,
    speed: 500,
    stamina: 100,
    passive: "Extra Padding",
    warbondCode: "warbond2",
    internalName: "tr7ambassadorofthebrand",
    imageURL: "tr7ambassadorofthebrand.webp",
    tier: "b",
    index: 45,
  },
  {
    displayName: "TR-9 Cavalier of Democracy",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Democracy Protects",
    warbondCode: "warbond2",
    internalName: "tr9cavalierofdemocracy",
    imageURL: "tr9cavalierofdemocracy.webp",
    tier: "b",
    index: 46,
  },
  {
    displayName: "TR-40 Gold Eagle",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 150,
    speed: 500,
    stamina: 100,
    passive: "Extra Padding",
    warbondCode: "none",
    internalName: "tr40goldeagle",
    imageURL: "tr40goldeagle.webp",
    tier: "b",
    index: 47,
  },
  {
    displayName: "TR-117 Alpha Commander",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Med-Kit",
    warbondCode: "none",
    internalName: "tr117alphacommander",
    imageURL: "tr117alphacommander.webp",
    tier: "b",
    index: 48,
  },
  {
    displayName: "UF-50 Bloodhound",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 125,
    speed: 500,
    stamina: 100,
    passive: "Unflinching",
    warbondCode: "warbond11",
    internalName: "uf50bloodhound",
    imageURL: "uf50bloodhound.webp",
    tier: "b",
    index: 49,
  },
  {
    displayName: "UF-84 Doubt Killer",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 125,
    speed: 500,
    stamina: 100,
    passive: "Unflinching",
    warbondCode: "warbond1",
    internalName: "uf84doubtkiller",
    imageURL: "uf84doubtkiller.webp",
    tier: "b",
    index: 50,
  },
  {
    displayName: "AF-52 Lockdown",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Advanced Filtration",
    warbondCode: "warbond1",
    internalName: "af52lockdown",
    imageURL: "af52lockdown.webp",
    tier: "b",
    index: 51,
  },
  {
    displayName: "B-27 Fortified Commando",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 200,
    speed: 450,
    stamina: 50,
    passive: "Extra Padding",
    warbondCode: "warbond1",
    internalName: "b27fortifiedcommando",
    imageURL: "b27fortifiedcommando.webp",
    tier: "b",
    index: 52,
  },
  {
    displayName: "CE-64 Grenadier",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Engineering Kit",
    warbondCode: "warbond1",
    internalName: "ce64grenadier",
    imageURL: "ce64grenadier.webp",
    tier: "b",
    index: 53,
  },
  {
    displayName: "CE-101 Guerilla Gorilla",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Engineering Kit",
    warbondCode: "warbond1",
    internalName: "ce101guerillagorilla",
    imageURL: "ce101guerillagorilla.webp",
    tier: "b",
    index: 54,
  },
  {
    displayName: "CM-17 Butcher",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Med-Kit",
    warbondCode: "warbond1",
    internalName: "cm17butcher",
    imageURL: "cm17butcher.webp",
    tier: "b",
    index: 55,
  },
  {
    displayName: "CW-22 Kodiak",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Fortified",
    warbondCode: "warbond7",
    internalName: "cw22kodiak",
    imageURL: "cw22kodiak.webp",
    tier: "b",
    index: 56,
  },
  {
    displayName: "CW-36 Winter Warrior",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Servo-Assisted",
    warbondCode: "warbond7",
    internalName: "cw36winterwarrior",
    imageURL: "cw36winterwarrior.webp",
    tier: "b",
    index: 57,
  },
  {
    displayName: "FS-05 Marksman",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Fortified",
    warbondCode: "warbond3",
    internalName: "fs05marksman",
    imageURL: "fs05marksman.webp",
    tier: "b",
    index: 58,
  },
  {
    displayName: "FS-11 Executioner",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Fortified",
    warbondCode: "warbond1",
    internalName: "fs11executioner",
    imageURL: "fs11executioner.webp",
    tier: "b",
    index: 59,
  },
  {
    displayName: "FS-23 Battle Master",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Fortified",
    warbondCode: "warbond3",
    internalName: "fs23battlemaster",
    imageURL: "fs23battlemaster.webp",
    tier: "b",
    index: 60,
  },
  {
    displayName: "FS-55 Devastator",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Fortified",
    warbondCode: "warbond6",
    internalName: "fs55devastator",
    imageURL: "fs55devastator.webp",
    tier: "b",
    index: 61,
  },
  {
    displayName: "FS-61 Dreadnought",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Servo-Assisted",
    warbondCode: "warbond1",
    internalName: "fs61dreadnought",
    imageURL: "fs61dreadnought.webp",
    tier: "b",
    index: 62,
  },
  {
    displayName: "I-44 Salamander",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Inflammable",
    warbondCode: "warbond1",
    internalName: "i44salamander",
    imageURL: "i44salamander.webp",
    tier: "b",
    index: 63,
  },
  {
    displayName: "PH-202 Twigsnapper",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Peak Physique",
    warbondCode: "warbond8",
    internalName: "ph202twigsnapper",
    imageURL: "ph202twigsnapper.webp",
    tier: "b",
    index: 64,
  },
  {
    displayName: "SA-32 Dynamo",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Servo-Assisted",
    warbondCode: "warbond4",
    internalName: "sa32dynamo",
    imageURL: "sa32dynamo.webp",
    tier: "b",
    index: 65,
  },
  {
    displayName: "TR-62 Knight",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Servo-Assisted",
    warbondCode: "warbond2",
    internalName: "tr62knight",
    imageURL: "tr62knight.webp",
    tier: "b",
    index: 66,
  },
  {
    displayName: "SR-64 Cinderblock",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Siege Ready",
    warbondCode: "warbond1",
    internalName: "sr64cinderblock",
    imageURL: "sr64cinderblock.webp",
    tier: "b",
    index: 67,
  },
  {
    displayName: "B-22 Model Citizen",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Democracy Protects",
    warbondCode: "none",
    internalName: "b22modelcitizen",
    imageURL: "b22modelcitizen.webp",
    tier: "b",
    index: 68,
  },
  {
    displayName: "IE-3 Martyr",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Integrated Explosives",
    warbondCode: "warbond13",
    internalName: "ie3martyr",
    imageURL: "ie3martyr.webp",
    tier: "b",
    index: 69,
  },
  {
    displayName: "IE-12 Righteous",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Integrated Explosives",
    warbondCode: "warbond13",
    internalName: "ie12righteous",
    imageURL: "ie12righteous.webp",
    tier: "b",
    index: 70,
  },
  {
    displayName: "IE-57 Hell-Bent",
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Integrated Explosives",
    warbondCode: "warbond1",
    internalName: "ie57hellbent",
    imageURL: "ie57hellbent.webp",
    tier: "b",
    index: 71,
  },
  {
    displayName: "GS-17 Frontier Marshal",
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Gunslinger",
    warbondCode: "warbond14",
    internalName: "gs17frontiermarshal",
    imageURL: "gs17frontiermarshal.webp",
    tier: "b",
    index: 72,
  },
  {
    displayName: "GS-66 Lawmaker",
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Gunslinger",
    warbondCode: "warbond14",
    internalName: "gs66lawmaker",
    imageURL: "gs66lawmaker.webp",
    tier: "b",
    index: 73,
  },
  {
    displayName: `GS-11 Democracy's Deputy`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Gunslinger",
    warbondCode: "warbond1",
    internalName: "gs11democracysdeputy",
    imageURL: "gs11democracysdeputy.webp",
    tier: "b",
    index: 74,
  },
  {
    displayName: `RE-824 Bearer of the Standard`,
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Reinforced Epaulettes",
    warbondCode: "warbond1",
    internalName: "re824bearerofthestandard",
    imageURL: "re824bearerofthestandard.webp",
    tier: "b",
    index: 75,
  },
  {
    displayName: `RE-1861 Parade Commander`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Reinforced Epaulettes",
    warbondCode: "warbond15",
    internalName: "re1861paradecommander",
    imageURL: "re1861paradecommander.webp",
    tier: "b",
    index: 76,
  },
  {
    displayName: `RE-2310 Honorary Guard`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Reinforced Epaulettes",
    warbondCode: "warbond15",
    internalName: "re2310honoraryguard",
    imageURL: "re2310honoraryguard.webp",
    tier: "b",
    index: 77,
  },
  {
    displayName: `BP-20 Correct Officer`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Ballistic Padding",
    warbondCode: "warbond16",
    internalName: "bp20correctofficer",
    imageURL: "bp20correctofficer.webp",
    tier: "b",
    index: 78,
  },
  {
    displayName: `BP-32 Jackboot`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Ballistic Padding",
    warbondCode: "warbond16",
    internalName: "bp32jackboot",
    imageURL: "bp32jackboot.webp",
    tier: "b",
    index: 79,
  },
  {
    displayName: `BP-77 Grand Juror`,
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Ballistic Padding",
    warbondCode: "warbond1",
    internalName: "bp77grandjuror",
    imageURL: "bp77grandjuror.webp",
    tier: "b",
    index: 80,
  },
  {
    displayName: `AD-11 Livewire`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Adreno-Defibrillator",
    warbondCode: "warbond17",
    internalName: "ad11livewire",
    imageURL: "ad11livewire.webp",
    tier: "b",
    index: 81,
  },
  {
    displayName: `AD-26 Bleeding Edge`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Adreno-Defibrillator",
    warbondCode: "warbond17",
    internalName: "ad26bleedingedge",
    imageURL: "ad26bleedingedge.webp",
    tier: "b",
    index: 82,
  },
  {
    displayName: `AD-49 Apollonian`,
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Adreno-Defibrillator",
    warbondCode: "warbond17",
    internalName: "ad49apollonian",
    imageURL: "ad49apollonian.webp",
    tier: "b",
    index: 83,
  },
  {
    displayName: `A-9 Helljumper`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Feet First",
    warbondCode: "warbond19",
    internalName: "a9helljumper",
    imageURL: "a9helljumper.webp",
    tier: "b",
    index: 84,
  },
  {
    displayName: `A-35 Recon`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Feet First",
    warbondCode: "warbond19",
    internalName: "a35recon",
    imageURL: "a35recon.webp",
    tier: "b",
    index: 85,
  },
  {
    displayName: `DS-42 Federation's Blade`,
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Desert Stormer",
    warbondCode: "warbond20",
    internalName: "ds42federationsblade",
    imageURL: "ds42federationsblade.webp",
    tier: "b",
    index: 86,
  },
  {
    displayName: `DS-191 Scorpion`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Desert Stormer",
    warbondCode: "warbond20",
    internalName: "ds191scorpion",
    imageURL: "ds191scorpion.webp",
    tier: "b",
    index: 87,
  },
  {
    displayName: `DS-10 Big Game Hunter`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Desert Stormer",
    warbondCode: "warbond1",
    internalName: "ds10biggamehunter",
    imageURL: "ds10biggamehunter.webp",
    tier: "b",
    index: 88,
  },
  {
    displayName: `RS-40 Beast of Prey`,
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Rock Solid",
    warbondCode: "warbond21",
    internalName: "rs40beastofprey",
    imageURL: "rs40beastofprey.webp",
    tier: "b",
    index: 89,
  },
  {
    displayName: `RS-20 Constrictor`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Rock Solid",
    warbondCode: "warbond21",
    internalName: "rs20constrictor",
    imageURL: "rs20constrictor.webp",
    tier: "b",
    index: 90,
  },
  {
    displayName: `RS-6 Fiend Destroyer`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Rock Solid",
    warbondCode: "warbond1",
    internalName: "rs6fienddestroyer",
    imageURL: "rs6fienddestroyer.webp",
    tier: "b",
    index: 91,
  },
  {
    displayName: `RS-89 Shadow Paragon`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Reduced Signature",
    warbondCode: "warbond22",
    internalName: "rs89shadowparagon",
    imageURL: "rs89shadowparagon.webp",
    tier: "b",
    index: 92,
  },
  {
    displayName: `RS-100 Sanctioner`,
    type: "Equipment",
    category: "armor",
    tags: ["Light"],
    armorRating: 50,
    speed: 550,
    stamina: 125,
    passive: "Reduced Signature",
    warbondCode: "warbond1",
    internalName: "rs100sanctioner",
    imageURL: "rs100sanctioner.webp",
    tier: "b",
    index: 93,
  },
  {
    displayName: `RS-67 Null Cipher`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Reduced Signature",
    warbondCode: "warbond22",
    internalName: "rs67nullcipher",
    imageURL: "rs67nullcipher.png",
    tier: "b",
    index: 94,
  },
  {
    displayName: `SA-7 Head First`,
    type: "Equipment",
    category: "armor",
    tags: ["Medium"],
    armorRating: 100,
    speed: 500,
    stamina: 100,
    passive: "Supplementary Adrenaline",
    warbondCode: "warbond23",
    internalName: "sa7headfirst",
    imageURL: "sa7headfirst.png",
    tier: "b",
    index: 95,
  },
  {
    displayName: `SA-8 Ram`,
    type: "Equipment",
    category: "armor",
    tags: ["Heavy"],
    armorRating: 150,
    speed: 450,
    stamina: 50,
    passive: "Supplementary Adrenaline",
    warbondCode: "warbond23",
    internalName: "sa8ram",
    imageURL: "sa8ram.webp",
    tier: "b",
    index: 96,
  },
];
