const ARMOR_SIZES = [
  {
    displayName: 'Light Armor',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorSize'],
    warbond: '',
    warbondCode: '',
    internalName: 'light',
    imageURL: '',
    tier: 'b',
  },
  {
    displayName: 'Medium Armor',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorSize'],
    warbond: '',
    warbondCode: '',
    internalName: 'medium',
    imageURL: '',
    tier: 'b',
  },
  {
    displayName: 'Heavy Armor',
    type: 'Equipment',
    category: 'armor',
    tags: ['ArmorSize'],
    warbond: '',
    warbondCode: '',
    internalName: 'heavy',
    imageURL: '',
    tier: 'b',
  },
];
