const ARMOR_SETS = [
  {
    displayName: 'AF-50 Noxious Ranger',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Chemical Agents',
    warbondCode: 'warbond8',
    internalName: 'af50noxiousranger',
    imageURL: 'af50noxiousranger.png',
    tier: 'b',
  },
  {
    displayName: 'AC-2 Obedient',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'ac2obedient',
    imageURL: 'ac2obedient.png',
    tier: 'b',
  },
  {
    displayName: 'SR-24 Street Scout',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Urban Legends',
    warbondCode: 'warbond10',
    internalName: 'sr24streetscout',
    imageURL: 'sr24streetscout.png',
    tier: 'b',
  },
  {
    displayName: 'SR-18 Road Block',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Urban Legends',
    warbondCode: 'warbond10',
    internalName: 'sr18roadblock',
    imageURL: 'sr18roadblock.png',
    tier: 'b',
  },
  {
    displayName: 'B-08 Light Gunner',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'b08lightgunner',
    imageURL: 'b08lightgunner.png',
    tier: 'b',
  },
  {
    displayName: 'CE-07 Demolition Specialist',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond4',
    internalName: 'ce07demolitionspecialist',
    imageURL: 'ce07demolitionspecialist.png',
    tier: 'b',
  },
  {
    displayName: 'CE-67 Titan',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ce67titan',
    imageURL: 'ce67titan.png',
    tier: 'b',
  },
  {
    displayName: 'CE-74 Breaker',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ce74breaker',
    imageURL: 'ce74breaker.png',
    tier: 'b',
  },
  {
    displayName: 'CM-21 Trench Paramedic',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'cm21trenchparamedic',
    imageURL: 'cm21trenchparamedic.png',
    tier: 'b',
  },
  {
    displayName: 'CW-4 Arctic Ranger',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond5',
    internalName: 'c4arcticranger',
    imageURL: 'c4arcticranger.png',
    tier: 'b',
  },
  {
    displayName: 'EX-00 Prototype X',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond3',
    internalName: 'ex00prototypex',
    imageURL: 'ex00prototypex.png',
    tier: 'b',
  },
  {
    displayName: 'FS-37 Ravager',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'fs37ravager',
    imageURL: 'fs37ravager.png',
    tier: 'b',
  },
  {
    displayName: 'FS-38 Eradicator',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'fs38eradicator',
    imageURL: 'fs38eradicator.png',
    tier: 'b',
  },
  {
    displayName: 'I-09 Heatseeker',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: "Freedom's Flame",
    warbondCode: 'warbond7',
    internalName: 'i09heatseeker',
    imageURL: 'i09heatseeker.png',
    tier: 'b',
  },
  {
    displayName: 'PH-9 Predator',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Viper Commandos',
    warbondCode: 'warbond6',
    internalName: 'ph9predator',
    imageURL: 'ph9predator.png',
    tier: 'b',
  },
  {
    displayName: 'SC-30 Trailblazer Scout',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'sc30trailblazerscout',
    imageURL: 'sc30trailblazerscout.png',
    tier: 'b',
  },
  {
    displayName: 'SC-34 Infiltrator',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'sc34infiltrator',
    imageURL: 'sc34infiltrator.png',
    tier: 'b',
  },
  {
    displayName: 'SC-37 Legionnaire',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'sc37legionnaire',
    imageURL: 'sc37legionnaire.png',
    tier: 'b',
  },
  {
    displayName: 'UF-16 Inspector',
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Truth Enforcers',
    warbondCode: 'warbond9',
    internalName: 'uf16inspector',
    imageURL: 'uf16inspector.png',
    tier: 'b',
  },
  {
    displayName: 'AF-02 Haz-Master',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Chemical Agents',
    warbondCode: 'warbond8',
    internalName: 'af02hazmaster',
    imageURL: 'af02hazmaster.png',
    tier: 'b',
  },
  {
    displayName: 'AF-91 Field Chemist',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'af91fieldchemist',
    imageURL: 'af91fieldchemist.png',
    tier: 'b',
  },
  {
    displayName: 'B-01 Tactical',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'b01tactical',
    imageURL: 'b01tactical.png',
    tier: 'b',
  },
  {
    displayName: 'B-24 Enforcer',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'b24enforcer',
    imageURL: 'b24enforcer.png',
    tier: 'b',
  },
  {
    displayName: 'CE-27 Ground Breaker',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond4',
    internalName: 'ce27groundbreaker',
    imageURL: 'ce27groundbreaker.png',
    tier: 'b',
  },
  {
    displayName: 'CE-35 Trench Engineer',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'ce35trenchengineer',
    imageURL: 'ce35trenchengineer.png',
    tier: 'b',
  },
  {
    displayName: 'CE-81 Juggernaut',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ce81juggernaut',
    imageURL: 'ce81juggernaut.png',
    tier: 'b',
  },
  {
    displayName: 'CM-09 Bonesnapper',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'cm09bonesnapper',
    imageURL: 'cm09bonesnapper.png',
    tier: 'b',
  },
  {
    displayName: 'CM-10 Clinician',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'cm10clinician',
    imageURL: 'cm10clinician.png',
    tier: 'b',
  },
  {
    displayName: 'CM-14 Physician',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'cm14physician',
    imageURL: 'cm14physician.png',
    tier: 'b',
  },
  {
    displayName: 'CW-9 White Wolf',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'cw9whitewolf',
    imageURL: 'cw9whitewolf.png',
    tier: 'b',
  },
  {
    displayName: 'DP-00 Tactical',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'dp00tactical',
    imageURL: 'dp00tactical.png',
    tier: 'b',
  },
  {
    displayName: 'DP-11 Champion of the People',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'dp11championofthepeople',
    imageURL: 'dp11championofthepeople.png',
    tier: 'b',
  },
  {
    displayName: 'AC-1 Dutiful',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ac1dutiful',
    imageURL: 'ac1dutiful.png',
    tier: 'b',
  },
  {
    displayName: 'DP-40 Hero of the Federation',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'dp40heroofthefederation',
    imageURL: 'dp40heroofthefederation.png',
    tier: 'b',
  },
  {
    displayName: 'DP-53 Savior of the Free',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Super Citizen Edition',
    warbondCode: 'warbond0',
    internalName: 'dp53saviorofthefree',
    imageURL: 'dp53saviorofthefree.png',
    tier: 'b',
  },
  {
    displayName: 'EX-03 Prototype 3',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond3',
    internalName: 'ex03prototype3',
    imageURL: 'ex03prototype3.png',
    tier: 'b',
  },
  {
    displayName: 'EX-16 Prototype 16',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond3',
    internalName: 'ex16prototype16',
    imageURL: 'ex16prototype16.png',
    tier: 'b',
  },
  {
    displayName: 'FS-34 Exterminator',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'fs34exterminator',
    imageURL: 'fs34exterminator.png',
    tier: 'b',
  },
  {
    displayName: 'I-92 Fire Fighter',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'i92firefighter',
    imageURL: 'i92firefighter.png',
    tier: 'b',
  },
  {
    displayName: 'I-102 Draconaught',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: "Freedom's Flame",
    warbondCode: 'warbond7',
    internalName: 'i102draconaught',
    imageURL: 'i102draconaught.png',
    tier: 'b',
  },
  {
    displayName: 'PH-56 Jaguar',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ph56jaguar',
    imageURL: 'ph56jaguar.png',
    tier: 'b',
  },
  {
    displayName: 'SA-04 Combat Technician',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'sa04combattechnician',
    imageURL: 'sa04combattechnician.png',
    tier: 'b',
  },
  {
    displayName: 'SA-12 Servo Assisted',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond2',
    internalName: 'sa12servoassisted',
    imageURL: 'sa12servoassisted.png',
    tier: 'b',
  },
  {
    displayName: 'SA-25 Steel Trooper',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond2',
    internalName: 'sa25steeltrooper',
    imageURL: 'sa25steeltrooper.png',
    tier: 'b',
  },
  {
    displayName: 'SA-15 Drone Master',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'sa15dronemaster',
    imageURL: 'sa15dronemaster.png',
    tier: 'b',
  },
  {
    displayName: 'TR-7 Ambassador of the Brand',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Pre-order Bonus',
    warbondCode: 'warbond12',
    internalName: 'tr7ambassadorofthebrand',
    imageURL: 'tr7ambassadorofthebrand.png',
    tier: 'b',
  },
  {
    displayName: 'TR-9 Cavalier of Democracy',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Pre-order Bonus',
    warbondCode: 'warbond12',
    internalName: 'tr9cavalierofdemocracy',
    imageURL: 'tr9cavalierofdemocracy.png',
    tier: 'b',
  },
  {
    displayName: 'TR-40 Golden Eagle',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'tr40goldeneagle',
    imageURL: 'tr40goldeneagle.png',
    tier: 'b',
  },
  {
    displayName: 'TR-117 Alpha Commander',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Twitch Drop',
    warbondCode: 'twitchdrop',
    internalName: 'tr117alphacommander',
    imageURL: 'tr117alphacommander.png',
    tier: 'b',
  },
  {
    displayName: 'UF-50 Bloodhound',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Truth Enforcers',
    warbondCode: 'warbond9',
    internalName: 'uf50bloodhound',
    imageURL: 'uf50bloodhound.png',
    tier: 'b',
  },
  {
    displayName: 'UF-84 Doubt Killer',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'uf84doubtkiller',
    imageURL: 'uf84doubtkiller.png',
    tier: 'b',
  },
  {
    displayName: 'AF-52 Lockdown',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'af52lockdown',
    imageURL: 'af52lockdown.png',
    tier: 'b',
  },
  {
    displayName: 'B-27 Fortified Commando',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'b27fortifiedcommando',
    imageURL: 'b27fortifiedcommando.png',
    tier: 'b',
  },
  {
    displayName: 'CE-64 Grenadier',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ce64grenadier',
    imageURL: 'ce64grenadier.png',
    tier: 'b',
  },
  {
    displayName: 'CE-101 Guerilla Gorilla',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ce101guerillagorilla',
    imageURL: 'ce101guerillagorilla.png',
    tier: 'b',
  },
  {
    displayName: 'CM-17 Butcher',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'cm17butcher',
    imageURL: 'cm17butcher.png',
    tier: 'b',
  },
  {
    displayName: 'CW-22 Kodiak',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond5',
    internalName: 'cw22kodiak',
    imageURL: 'cw22kodiak.png',
    tier: 'b',
  },
  {
    displayName: 'CW-36 Winter Warrior',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond5',
    internalName: 'cw36winterwarrior',
    imageURL: 'cw36winterwarrior.png',
    tier: 'b',
  },
  {
    displayName: 'FS-05 Marksman',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'fs05marksman',
    imageURL: 'fs05marksman.png',
    tier: 'b',
  },
  {
    displayName: 'FS-11 Executioner',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'fs11executioner',
    imageURL: 'fs11executioner.png',
    tier: 'b',
  },
  {
    displayName: 'FS-23 Battle Master',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'fs23battlemaster',
    imageURL: 'fs23battlemaster.png',
    tier: 'b',
  },
  {
    displayName: 'FS-55 Devastator',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond4',
    internalName: 'fs55devastator',
    imageURL: 'fs55devastator.png',
    tier: 'b',
  },
  {
    displayName: 'FS-51 Dreadnought',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'fs51dreadnought',
    imageURL: 'fs51dreadnought.png',
    tier: 'b',
  },
  {
    displayName: 'I-44 Salamander',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'i44salamander',
    imageURL: 'i44salamander.png',
    tier: 'b',
  },
  {
    displayName: 'PH-202 Twigsnapper',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Viper Commandos',
    warbondCode: 'warbond6',
    internalName: 'ph202twigsnapper',
    imageURL: 'ph202twigsnapper.png',
    tier: 'b',
  },
  {
    displayName: 'SA-32 Dynamo',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond2',
    internalName: 'sa32dynamo',
    imageURL: 'sa32dynamo.png',
    tier: 'b',
  },
  {
    displayName: 'TR-62 Knight',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Pre-Order Bonus',
    warbondCode: 'warbond12',
    internalName: 'tr62knight',
    imageURL: 'tr62knight.png',
    tier: 'b',
  },
  {
    displayName: 'SR-64 Cinderblock',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'sr64cinderblock',
    imageURL: 'sr64cinderblock.png',
    tier: 'b',
  },
  {
    displayName: 'B-22 Model Citizen',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'b22modelcitizen',
    imageURL: 'b22modelcitizen.png',
    tier: 'b',
  },
  {
    displayName: 'IE-3 Martyr',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Servants of Freedom',
    warbondCode: 'warbond11',
    internalName: 'ie3martyr',
    imageURL: 'ie3martyr.png',
    tier: 'b',
  },
  {
    displayName: 'IE-12 Righteous',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Servants of Freedom',
    warbondCode: 'warbond11',
    internalName: 'ie12righteous',
    imageURL: 'ie12righteous.png',
    tier: 'b',
  },
  {
    displayName: 'IE-57 Hell-Bent',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'ie57hellbent',
    imageURL: 'ie57hellbent.png',
    tier: 'b',
  },
  {
    displayName: 'GS-17 Frontier Marshal',
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Borderline Justice',
    warbondCode: 'warbond12',
    internalName: 'gs17frontiermarshal',
    imageURL: 'gs17frontiermarshal.png',
    tier: 'b',
  },
  {
    displayName: 'GS-66 Lawmaker',
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Borderline Justice',
    warbondCode: 'warbond12',
    internalName: 'gs66lawmaker',
    imageURL: 'gs66lawmaker.png',
    tier: 'b',
  },
  {
    displayName: `GS-11 Democracy's Deputy`,
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 'gs11democracysdeputy',
    imageURL: 'gs11democracysdeputy.png',
    tier: 'b',
  },
  {
    displayName: `RE-824 Bearer of the Standard`,
    type: 'Equipment',
    category: 'armor',
    tags: ['Heavy'],
    warbond: 'Superstore',
    warbondCode: 'superstore',
    internalName: 're824bearerofthestandard',
    imageURL: 're824bearerofthestandard.png',
    tier: 'b',
  },
  {
    displayName: `RE-1861 Parade Commander`,
    type: 'Equipment',
    category: 'armor',
    tags: ['Light'],
    warbond: 'Masters of Ceremony',
    warbondCode: 'warbond13',
    internalName: 're1861paradecommander',
    imageURL: 're1861paradecommander.png',
    tier: 'b',
  },
  {
    displayName: `RE-2310 Honorary Guard`,
    type: 'Equipment',
    category: 'armor',
    tags: ['Medium'],
    warbond: 'Masters of Ceremony',
    warbondCode: 'warbond13',
    internalName: 're2310honoraryguard',
    imageURL: 're2310honoraryguard.png',
    tier: 'b',
  },
];
