const BOOSTERS = [
  {
    displayName: "Expert Extraction Pilot",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond6",
    internalName: "expertextractionpilot",
    imageURL: "expertextractionpilot.png",
    tier: "c",
  },
  {
    displayName: "Dead Sprint",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond11",
    internalName: "deadsprint",
    imageURL: "deadsprint.png",
    tier: "b",
  },
  {
    displayName: "Armed Resupply Pods",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond12",
    internalName: "armedresupplypods",
    imageURL: "armedresupplypods.png",
    tier: "b",
  },
  {
    displayName: "Experimental Infusion",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond8",
    internalName: "experimentalinfusion",
    imageURL: "experimentalinfusion.png",
    tier: "s",
  },
  {
    displayName: "Motivational Shocks",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond7",
    internalName: "motivationalshocks",
    imageURL: "motivationalshocks.png",
    tier: "b",
  },
  {
    displayName: "Flexible Reinforcement Budget",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond4",
    internalName: "flexiblereinforcementbudget",
    imageURL: "flexiblereinforcementbudget.png",
    tier: "c",
  },
  {
    displayName: "Hellpod Space Optimization",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "hellpodspaceoptimization",
    imageURL: "hellpodspaceoptimization.png",
    tier: "s",
  },
  {
    displayName: "Increased Reinforcement Budget",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "increasedreinforcementbudget",
    imageURL: "increasedreinforcementbudget.png",
    tier: "b",
  },
  {
    displayName: "Localization Confusion",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond5",
    internalName: "localizationconfusion",
    imageURL: "localizationconfusion.png",
    tier: "b",
  },
  {
    displayName: "Muscle Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "muscleenhancement",
    imageURL: "muscleenhancement.png",
    tier: "a",
  },
  {
    displayName: "Stamina Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "staminaenhancement",
    imageURL: "staminaenhancement.png",
    tier: "s",
  },
  {
    displayName: "UAV Recon",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "uavrecon",
    imageURL: "uavrecon.png",
    tier: "b",
  },
  {
    displayName: "Vitality Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "vitalityenhancement",
    imageURL: "vitalityenhancement.png",
    tier: "s",
  },
  {
    displayName: "Firebomb Hellpods",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond9",
    internalName: "firebombhellpods",
    imageURL: "firebombhellpods.png",
    tier: "c",
  },
  {
    displayName: "Sample Extricator",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond14",
    internalName: "sampleextricator",
    imageURL: "sampleextricator.png",
    tier: "c",
  },
  {
    displayName: "Sample Scanner",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond15",
    internalName: "samplescanner",
    imageURL: "samplescanner.png",
    tier: "c",
  },
  {
    displayName: "Stun Pods",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond16",
    internalName: "stunpods",
    imageURL: "stunpods.png",
    tier: "b",
  },

  // {
  //   displayName: "Concealed Insertion",
  //   type: "Equipment",
  //   category: "booster",
  //   tags: [],
  //   warbondCode: "warbond22",
  //   internalName: "concealedinsertion",
  //   imageURL: "concealedinsertion.png",
  //   tier: "b",
  // },
];

// s: 4
// a: 1
// b: 6
// c: 5
