const BOOSTERS = [
  {
    displayName: 'Expert Extraction Pilot',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond4',
    internalName: 'expertextractionpilot',
    imageURL: 'expertextractionpilot.png',
    tier: 'b',
  },
  {
    displayName: 'Dead Sprint',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Truth Enforcers',
    warbondCode: 'warbond9',
    internalName: 'deadsprint',
    imageURL: 'deadsprint.png',
    tier: 'b',
  },
  {
    displayName: 'Armed Resupply Pods',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Urban Legends',
    warbondCode: 'warbond10',
    internalName: 'armedresupplypods',
    imageURL: 'armedresupplypods.png',
    tier: 'b',
  },
  {
    displayName: 'Experimental Infusion',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Viper Commandos',
    warbondCode: 'warbond6',
    internalName: 'experimentalinfusion',
    imageURL: 'experimentalinfusion.png',
    tier: 'b',
  },
  {
    displayName: 'Motivational Shocks',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond5',
    internalName: 'motivationalshocks',
    imageURL: 'motivationalshocks.png',
    tier: 'b',
  },
  {
    displayName: 'Flexible Reinforcement Budget',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond2',
    internalName: 'flexiblereinforcementbudget',
    imageURL: 'flexiblereinforcementbudget.png',
    tier: 'b',
  },
  {
    displayName: 'Hellpod Space Optimization',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'hellpodspaceoptimization',
    imageURL: 'hellpodspaceoptimization.png',
    tier: 'b',
  },
  {
    displayName: 'Increased Reinforcement Budget',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'increasedreinforcementbudget',
    imageURL: 'increasedreinforcementbudget.png',
    tier: 'b',
  },
  {
    displayName: 'Localization Confusion',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond3',
    internalName: 'localizationconfusion',
    imageURL: 'localizationconfusion.png',
    tier: 'b',
  },
  {
    displayName: 'Muscle Enhancement',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'muscleenhancement',
    imageURL: 'muscleenhancement.png',
    tier: 'b',
  },
  {
    displayName: 'Stamina Enhancement',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Heldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'staminaenhancement',
    imageURL: 'staminaenhancement.png',
    tier: 'b',
  },
  {
    displayName: 'UAV Recon',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'uavrecon',
    imageURL: 'uavrecon.png',
    tier: 'b',
  },
  {
    displayName: 'Vitality Enhancement',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'vitalityenhancement',
    imageURL: 'vitalityenhancement.png',
    tier: 'b',
  },
  {
    displayName: 'Firebomb Hellpods',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: "Freedom's Flame",
    warbondCode: 'warbond7',
    internalName: 'firebombhellpods',
    imageURL: 'firebombhellpods.png',
    tier: 'b',
  },
  {
    displayName: 'Sample Extricator',
    type: 'Equipment',
    category: 'booster',
    tags: [],
    warbond: 'Borderline Justice',
    warbondCode: 'warbond12',
    internalName: 'sampleextricator',
    imageURL: 'sampleextricator.png',
    tier: 'b',
  },
];
