const CAPES = [
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Will of the People",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond0",
    internalName: "willofthepeople",
    imageURL: "willofthepeople.webp",
    tier: "b",
  },
  {
    displayName: "Independence Bringer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "independencebringer",
    imageURL: "independencebringer.webp",
    tier: "b",
  },
  {
    displayName: "Liberty's Herald",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "libertysherald",
    imageURL: "libertysherald.webp",
    tier: "b",
  },
  {
    displayName: "Tideturner",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "tideturner",
    imageURL: "tideturner.webp",
    tier: "b",
  },
  {
    displayName: "Stars and Suffrage",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "thecapeofstarsandsuffrage",
    imageURL: "thecapeofstarsandsuffrage.webp",
    tier: "b",
  },
  {
    displayName: "Unblemished Allegiance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "unblemishedallegiance",
    imageURL: "unblemishedallegiance.webp",
    tier: "b",
  },
  {
    displayName: "Judgment Day",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "judgmentday",
    imageURL: "judgmentday.webp",
    tier: "b",
  },
  {
    displayName: "Cresting Honor",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "crestinghonor",
    imageURL: "crestinghonor.webp",
    tier: "b",
  },
  {
    displayName: "Mantle of True Citizenship",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "mantleoftruecitizenship",
    imageURL: "mantleoftruecitizenship.webp",
    tier: "b",
  },
  {
    displayName: "Blazing Samaritan",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "blazingsamaritan",
    imageURL: "blazingsamaritan.webp",
    tier: "b",
  },
  {
    displayName: "Light of Eternal Liberty",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "lightofeternalliberty",
    imageURL: "lightofeternalliberty.webp",
    tier: "b",
  },
  {
    displayName: "Tyrant Hunter",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "tyranthunter",
    imageURL: "tyranthunter.webp",
    tier: "b",
  },
  {
    displayName: "Cloak of Posterity's Gratitude",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "cloakofposteritysgratitude",
    imageURL: "cloakofposteritysgratitude.webp",
    tier: "b",
  },
  {
    displayName: "Drape of Glory",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "drapeofglory",
    imageURL: "drapeofglory.webp",
    tier: "b",
  },
  {
    displayName: "Bastion of Integrity",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "bastionofintegrity",
    imageURL: "bastionofintegrity.webp",
    tier: "b",
  },
  {
    displayName: "Botslayer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "botslayer",
    imageURL: "botslayer.webp",
    tier: "b",
  },
  {
    displayName: "Martyris Rex",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "martyrisrex",
    imageURL: "martyrisrex.webp",
    tier: "b",
  },
  {
    displayName: "Agent of Oblivion",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "agentofoblivion",
    imageURL: "agentofoblivion.webp",
    tier: "b",
  },
  {
    displayName: "Fallen Hero's Vengeance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "fallenherosvengeance",
    imageURL: "fallenherosvengeance.webp",
    tier: "b",
  },
  {
    displayName: "Harbinger of True Equality",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "harbingeroftrueequality",
    imageURL: "harbingeroftrueequality.webp",
    tier: "b",
  },
  {
    displayName: "Eagle's Fury",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "eaglesfury",
    imageURL: "eaglesfury.webp",
    tier: "b",
  },
  {
    displayName: "Freedom's Tapestry",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "freedomstapestry",
    imageURL: "freedomstapestry.webp",
    tier: "b",
  },
  {
    displayName: "Dissident's Nightmare",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "dissidentsnightmare",
    imageURL: "dissidentsnightmare.webp",
    tier: "b",
  },
  {
    displayName: "Rightful Occupier",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "rightfuloccupier",
    imageURL: "rightfuloccupier.webp",
    tier: "b",
  },
  {
    displayName: "Pinions of Everlasting Glory",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "pinionsofeverlastingglory",
    imageURL: "pinionsofeverlastingglory.webp",
    tier: "b",
  },
  {
    displayName: "Windswept Wayfinder",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "windsweptwayfinder",
    imageURL: "windsweptwayfinder.webp",
    tier: "b",
  },
  {
    displayName: "Order of the Venerated Ballot",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "orderoftheveneratedballot",
    imageURL: "orderoftheveneratedballot.webp",
    tier: "b",
  },
  {
    displayName: "Mark of the Crimson Fang",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "markofthecrimsonfang",
    imageURL: "markofthecrimsonfang.webp",
    tier: "b",
  },
  {
    displayName: "Executioner's Canopy",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "executionerscanopy",
    imageURL: "executionerscanopy.webp",
    tier: "b",
  },
  {
    displayName: "Purifying Eclipse",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "purifyingeclipse",
    imageURL: "purifyingeclipse.webp",
    tier: "b",
  },
  {
    displayName: "The Breach",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "thebreach",
    imageURL: "thebreach.webp",
    tier: "b",
  },
  {
    displayName: "Standard of Safe Distance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "standardofsafedistance",
    imageURL: "standardofsafedistance.webp",
    tier: "b",
  },
  {
    displayName: "Patient Zero's Remembrance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "patientzerosremembrance",
    imageURL: "patientzerosremembrance.webp",
    tier: "b",
  },
  {
    displayName: "Cover of Darkness",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "coverofdarkness",
    imageURL: "coverofdarkness.webp",
    tier: "b",
  },
  {
    displayName: "Pride of the Whistleblower",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "prideofthewhistleblower",
    imageURL: "prideofthewhistleblower.webp",
    tier: "b",
  },
  {
    displayName: "Proof of Faultless Virtue",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "proofoffaultlessvirtue",
    imageURL: "proofoffaultlessvirtue.webp",
    tier: "b",
  },
  {
    displayName: "Stone-Wrought Perseverance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "stonewroughtperserverance",
    imageURL: "stonewroughtperserverance.webp",
    tier: "b",
  },
  {
    displayName: "Greatcloak of Rebar Resolve",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "greatcloakofrebarresolve",
    imageURL: "greatcloakofrebarresolve.webp",
    tier: "b",
  },
  {
    displayName: "Holder of the Yellow Line",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "holderoftheyellowline",
    imageURL: "holderoftheyellowline.webp",
    tier: "b",
  },
  {
    displayName: "Strength in Our Arms",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "strengthinourarms",
    imageURL: "strengthinourarms.webp",
    tier: "b",
  },
  {
    displayName: "Defender of Our Dream",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "defenderofourdream",
    imageURL: "defenderofourdream.webp",
    tier: "b",
  },
  {
    displayName: "Vision of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "visionoffreedom",
    imageURL: "visionoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Eternal Corona",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "eternalcorona",
    imageURL: "eternalcorona.webp",
    tier: "b",
  },
  {
    displayName: "Fre Liberam",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "freliberam",
    imageURL: "freliberam.webp",
    tier: "b",
  },
  {
    displayName: "Per Democrasum",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "perdemocrasum",
    imageURL: "perdemocrasum.webp",
    tier: "b",
  },
  {
    displayName: "Eye of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "eyeoffreedom",
    imageURL: "eyeoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Emblem of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "emblemoffreedom",
    imageURL: "emblemoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Veil of the Valorous Vagabond",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "veilofthevalorousvagabond",
    imageURL: "veilofthevalorousvagabond.webp",
    tier: "b",
  },
  {
    displayName: "Reaper of Bounties",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "reaperofbounties",
    imageURL: "reaperofbounties.webp",
    tier: "b",
  },
  {
    displayName: "Way of the Bandolier",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "wayofthebandolier",
    imageURL: "wayofthebandolier.webp",
    tier: "b",
  },
  {
    displayName: "Seal of General Consensus",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "sealofgeneralconsensus",
    imageURL: "sealofgeneralconsensus.webp",
    tier: "b",
  },
  {
    displayName: "Federation's Embrace",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "federationsembrace",
    imageURL: "federationsembrace.webp",
    tier: "b",
  },
  {
    displayName: "Humble Regalia",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "humbleregalia",
    imageURL: "humbleregalia.webp",
    tier: "b",
  },
  {
    displayName: "Badge of Order",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "badgeoforder",
    imageURL: "badgeoforder.webp",
    tier: "b",
  },
  {
    displayName: "Miranda's Legacy",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mirandaslegacy",
    imageURL: "mirandaslegacy.webp",
    tier: "b",
  },
  {
    displayName: "Mother Eagle's Wings",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mothereagleswings",
    imageURL: "mothereagleswings.webp",
    tier: "b",
  },
  {
    displayName: "Protector of the Heart",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "protectoroftheheart",
    imageURL: "protectoroftheheart.webp",
    tier: "b",
  },
  {
    displayName: "Pillars of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "pillarsoffreedom",
    imageURL: "pillarsoffreedom.webp",
    tier: "b",
  },
  {
    displayName: "Conductor of Brilliance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "conductorofbrilliance",
    imageURL: "conductorofbrilliance.webp",
    tier: "b",
  },
  {
    displayName: "Over Artifice Triumphant",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "overartificetriumphant",
    imageURL: "overartificetriumphant.webp",
    tier: "b",
  },
  {
    displayName: "Schema Laid Bare",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "schemalaidbare",
    imageURL: "schemalaidbare.webp",
    tier: "b",
  },
  {
    displayName: "Ingress-81",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "ingress81",
    imageURL: "ingress81.webp",
    tier: "b",
  },
  {
    displayName: "Honored Heirloom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "honoredheirloom",
    imageURL: "honoredheirloom.webp",
    tier: "b",
  },
  {
    displayName: "Eye of the Clandestine",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "eyeoftheclandestine",
    imageURL: "eyeoftheclandestine.webp",
    tier: "b",
  },
  {
    displayName: "Veridical Ideology",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "veridicalideology",
    imageURL: "veridicalideology.webp",
    tier: "b",
  },

  // {
  //   displayName: "Pillar of the Abyss",
  //   type: "Equipment",
  //   category: "cape",
  //   tags: [],
  //   warbondCode: "warbond21",
  //   internalName: "pillaroftheabyss",
  //   imageURL: "pillaroftheabyss.webp",
  //   tier: "b",
  // },
  // {
  //   displayName: "Triangulation Veil",
  //   type: "Equipment",
  //   category: "cape",
  //   tags: [],
  //   warbondCode: "warbond21",
  //   internalName: "triangulationveil",
  //   imageURL: "triangulationveil.webp",
  //   tier: "b",
  // },
  // {
  //   displayName: "Gilded Quill",
  //   type: "Equipment",
  //   category: "cape",
  //   tags: [],
  //   warbondCode: "warbond21",
  //   internalName: "gildedquill",
  //   imageURL: "gildedquill.webp",
  //   tier: "b",
  // },
];
