const CAPES = [
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Will of the People",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond0",
    internalName: "willofthepeople",
    imageURL: "willofthepeople.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
  },
];
