const CAPES = [
  {
    displayName: "Foesmasher",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foesmasher",
    imageURL: "foesmasher.webp",
    tier: "b",
    index: 0,
  },
  {
    displayName: "Will of the People",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond0",
    internalName: "willofthepeople",
    imageURL: "willofthepeople.webp",
    tier: "b",
    index: 1,
  },
  {
    displayName: "Independence Bringer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "independencebringer",
    imageURL: "independencebringer.webp",
    tier: "b",
    index: 2,
  },
  {
    displayName: "Liberty's Herald",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "libertysherald",
    imageURL: "libertysherald.webp",
    tier: "b",
    index: 3,
  },
  {
    displayName: "Tideturner",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "tideturner",
    imageURL: "tideturner.webp",
    tier: "b",
    index: 4,
  },
  {
    displayName: "Stars and Suffrage",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "thecapeofstarsandsuffrage",
    imageURL: "thecapeofstarsandsuffrage.webp",
    tier: "b",
    index: 5,
  },
  {
    displayName: "Unblemished Allegiance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "unblemishedallegiance",
    imageURL: "unblemishedallegiance.webp",
    tier: "b",
    index: 6,
  },
  {
    displayName: "Judgment Day",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "judgmentday",
    imageURL: "judgmentday.webp",
    tier: "b",
    index: 7,
  },
  {
    displayName: "Cresting Honor",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "crestinghonor",
    imageURL: "crestinghonor.webp",
    tier: "b",
    index: 8,
  },
  {
    displayName: "Mantle of True Citizenship",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "mantleoftruecitizenship",
    imageURL: "mantleoftruecitizenship.webp",
    tier: "b",
    index: 9,
  },
  {
    displayName: "Blazing Samaritan",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "blazingsamaritan",
    imageURL: "blazingsamaritan.webp",
    tier: "b",
    index: 10,
  },
  {
    displayName: "Light of Eternal Liberty",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "lightofeternalliberty",
    imageURL: "lightofeternalliberty.webp",
    tier: "b",
    index: 11,
  },
  {
    displayName: "Tyrant Hunter",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "tyranthunter",
    imageURL: "tyranthunter.webp",
    tier: "b",
    index: 12,
  },
  {
    displayName: "Cloak of Posterity's Gratitude",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "cloakofposteritysgratitude",
    imageURL: "cloakofposteritysgratitude.webp",
    tier: "b",
    index: 13,
  },
  {
    displayName: "Drape of Glory",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond4",
    internalName: "drapeofglory",
    imageURL: "drapeofglory.webp",
    tier: "b",
    index: 14,
  },
  {
    displayName: "Bastion of Integrity",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond3",
    internalName: "bastionofintegrity",
    imageURL: "bastionofintegrity.webp",
    tier: "b",
    index: 15,
  },
  {
    displayName: "Botslayer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "botslayer",
    imageURL: "botslayer.webp",
    tier: "b",
    index: 16,
  },
  {
    displayName: "Martyris Rex",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "martyrisrex",
    imageURL: "martyrisrex.webp",
    tier: "b",
    index: 17,
  },
  {
    displayName: "Agent of Oblivion",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond5",
    internalName: "agentofoblivion",
    imageURL: "agentofoblivion.webp",
    tier: "b",
    index: 18,
  },
  {
    displayName: "Fallen Hero's Vengeance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "fallenherosvengeance",
    imageURL: "fallenherosvengeance.webp",
    tier: "b",
    index: 19,
  },
  {
    displayName: "Harbinger of True Equality",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "harbingeroftrueequality",
    imageURL: "harbingeroftrueequality.webp",
    tier: "b",
    index: 20,
  },
  {
    displayName: "Eagle's Fury",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "eaglesfury",
    imageURL: "eaglesfury.webp",
    tier: "b",
    index: 21,
  },
  {
    displayName: "Freedom's Tapestry",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond6",
    internalName: "freedomstapestry",
    imageURL: "freedomstapestry.webp",
    tier: "b",
    index: 22,
  },
  {
    displayName: "Dissident's Nightmare",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "dissidentsnightmare",
    imageURL: "dissidentsnightmare.webp",
    tier: "b",
    index: 23,
  },
  {
    displayName: "Rightful Occupier",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "rightfuloccupier",
    imageURL: "rightfuloccupier.webp",
    tier: "b",
    index: 24,
  },
  {
    displayName: "Pinions of Everlasting Glory",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "pinionsofeverlastingglory",
    imageURL: "pinionsofeverlastingglory.webp",
    tier: "b",
    index: 25,
  },
  {
    displayName: "Windswept Wayfinder",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond20",
    internalName: "windsweptwayfinder",
    imageURL: "windsweptwayfinder.webp",
    tier: "b",
    index: 26,
  },
  {
    displayName: "Order of the Venerated Ballot",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond7",
    internalName: "orderoftheveneratedballot",
    imageURL: "orderoftheveneratedballot.webp",
    tier: "b",
    index: 27,
  },
  {
    displayName: "Mark of the Crimson Fang",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "markofthecrimsonfang",
    imageURL: "markofthecrimsonfang.webp",
    tier: "b",
    index: 28,
  },
  {
    displayName: "Executioner's Canopy",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond8",
    internalName: "executionerscanopy",
    imageURL: "executionerscanopy.webp",
    tier: "b",
    index: 29,
  },
  {
    displayName: "Purifying Eclipse",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "purifyingeclipse",
    imageURL: "purifyingeclipse.webp",
    tier: "b",
    index: 30,
  },
  {
    displayName: "The Breach",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond9",
    internalName: "thebreach",
    imageURL: "thebreach.webp",
    tier: "b",
    index: 31,
  },
  {
    displayName: "Standard of Safe Distance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "standardofsafedistance",
    imageURL: "standardofsafedistance.webp",
    tier: "b",
    index: 32,
  },
  {
    displayName: "Patient Zero's Remembrance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond10",
    internalName: "patientzerosremembrance",
    imageURL: "patientzerosremembrance.webp",
    tier: "b",
    index: 33,
  },
  {
    displayName: "Cover of Darkness",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "coverofdarkness",
    imageURL: "coverofdarkness.webp",
    tier: "b",
    index: 34,
  },
  {
    displayName: "Pride of the Whistleblower",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "prideofthewhistleblower",
    imageURL: "prideofthewhistleblower.webp",
    tier: "b",
    index: 35,
  },
  {
    displayName: "Proof of Faultless Virtue",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond11",
    internalName: "proofoffaultlessvirtue",
    imageURL: "proofoffaultlessvirtue.webp",
    tier: "b",
    index: 36,
  },
  {
    displayName: "Stone-Wrought Perseverance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "stonewroughtperserverance",
    imageURL: "stonewroughtperserverance.webp",
    tier: "b",
    index: 37,
  },
  {
    displayName: "Greatcloak of Rebar Resolve",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "greatcloakofrebarresolve",
    imageURL: "greatcloakofrebarresolve.webp",
    tier: "b",
    index: 38,
  },
  {
    displayName: "Holder of the Yellow Line",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond12",
    internalName: "holderoftheyellowline",
    imageURL: "holderoftheyellowline.webp",
    tier: "b",
    index: 39,
  },
  {
    displayName: "Strength in Our Arms",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "strengthinourarms",
    imageURL: "strengthinourarms.webp",
    tier: "b",
    index: 40,
  },
  {
    displayName: "Defender of Our Dream",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond18",
    internalName: "defenderofourdream",
    imageURL: "defenderofourdream.webp",
    tier: "b",
    index: 41,
  },
  {
    displayName: "Vision of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "visionoffreedom",
    imageURL: "visionoffreedom.webp",
    tier: "b",
    index: 42,
  },
  {
    displayName: "Eternal Corona",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "eternalcorona",
    imageURL: "eternalcorona.webp",
    tier: "b",
    index: 43,
  },
  {
    displayName: "Fre Liberam",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "freliberam",
    imageURL: "freliberam.webp",
    tier: "b",
    index: 44,
  },
  {
    displayName: "Per Democrasum",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond13",
    internalName: "perdemocrasum",
    imageURL: "perdemocrasum.webp",
    tier: "b",
    index: 45,
  },
  {
    displayName: "Eye of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "eyeoffreedom",
    imageURL: "eyeoffreedom.webp",
    tier: "b",
    index: 46,
  },
  {
    displayName: "Emblem of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "emblemoffreedom",
    imageURL: "emblemoffreedom.webp",
    tier: "b",
    index: 47,
  },
  {
    displayName: "Veil of the Valorous Vagabond",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "veilofthevalorousvagabond",
    imageURL: "veilofthevalorousvagabond.webp",
    tier: "b",
    index: 48,
  },
  {
    displayName: "Reaper of Bounties",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "reaperofbounties",
    imageURL: "reaperofbounties.webp",
    tier: "b",
    index: 49,
  },
  {
    displayName: "Way of the Bandolier",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond14",
    internalName: "wayofthebandolier",
    imageURL: "wayofthebandolier.webp",
    tier: "b",
    index: 50,
  },
  {
    displayName: "Seal of General Consensus",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "sealofgeneralconsensus",
    imageURL: "sealofgeneralconsensus.webp",
    tier: "b",
    index: 51,
  },
  {
    displayName: "Federation's Embrace",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "federationsembrace",
    imageURL: "federationsembrace.webp",
    tier: "b",
    index: 52,
  },
  {
    displayName: "Humble Regalia",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond15",
    internalName: "humbleregalia",
    imageURL: "humbleregalia.webp",
    tier: "b",
    index: 53,
  },
  {
    displayName: "Badge of Order",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "badgeoforder",
    imageURL: "badgeoforder.webp",
    tier: "b",
    index: 54,
  },
  {
    displayName: "Miranda's Legacy",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mirandaslegacy",
    imageURL: "mirandaslegacy.webp",
    tier: "b",
    index: 55,
  },
  {
    displayName: "Mother Eagle's Wings",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond16",
    internalName: "mothereagleswings",
    imageURL: "mothereagleswings.webp",
    tier: "b",
    index: 56,
  },
  {
    displayName: "Protector of the Heart",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "protectoroftheheart",
    imageURL: "protectoroftheheart.webp",
    tier: "b",
    index: 57,
  },
  {
    displayName: "Pillars of Freedom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "pillarsoffreedom",
    imageURL: "pillarsoffreedom.webp",
    tier: "b",
    index: 58,
  },
  {
    displayName: "Conductor of Brilliance",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "conductorofbrilliance",
    imageURL: "conductorofbrilliance.webp",
    tier: "b",
    index: 59,
  },
  {
    displayName: "Over Artifice Triumphant",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond17",
    internalName: "overartificetriumphant",
    imageURL: "overartificetriumphant.webp",
    tier: "b",
    index: 60,
  },
  {
    displayName: "Schema Laid Bare",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "schemalaidbare",
    imageURL: "schemalaidbare.webp",
    tier: "b",
    index: 61,
  },
  {
    displayName: "Ingress-81",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "ingress81",
    imageURL: "ingress81.webp",
    tier: "b",
    index: 62,
  },
  {
    displayName: "Honored Heirloom",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "honoredheirloom",
    imageURL: "honoredheirloom.webp",
    tier: "b",
    index: 63,
  },
  {
    displayName: "Eye of the Clandestine",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond19",
    internalName: "eyeoftheclandestine",
    imageURL: "eyeoftheclandestine.webp",
    tier: "b",
    index: 64,
  },
  {
    displayName: "Veridical Ideology",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "veridicalideology",
    imageURL: "veridicalideology.webp",
    tier: "b",
    index: 65,
  },
  {
    displayName: "Mark of the Constrictor",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "markoftheconstrictor",
    imageURL: "markoftheconstrictor.webp",
    tier: "b",
    index: 66,
  },
  {
    displayName: "Foe Rent Asunder",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "foerentasunder",
    imageURL: "foerentasunder.webp",
    tier: "b",
    index: 67,
  },
  {
    displayName: "De-Forester's Sailcloth",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "deforesterssailcloth",
    imageURL: "deforesterssailcloth.webp",
    tier: "b",
    index: 68,
  },
  {
    displayName: "Against the Tyrant Cloud",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "againstthetyrantcloud",
    imageURL: "againstthetyrantcloud.webp",
    tier: "b",
    index: 69,
  },
  {
    displayName: "Reckoning's Cheer",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "none",
    internalName: "reckoningscheer",
    imageURL: "reckoningscheer.webp",
    tier: "b",
    index: 70,
  },
  {
    displayName: "Pillar of the Abyss",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond22",
    internalName: "pillaroftheabyss",
    imageURL: "pillaroftheabyss.webp",
    tier: "b",
    index: 71,
  },
  {
    displayName: "Triangulation Veil",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond22",
    internalName: "triangulationveil",
    imageURL: "triangulationveil.webp",
    tier: "b",
    index: 72,
  },
  {
    displayName: "Gilded Quill",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "gildedquill",
    imageURL: "gildedquill.webp",
    tier: "b",
    index: 73,
  },
  {
    displayName: "Rags of the Fashionable",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond23",
    internalName: "ragsofthefashionable",
    imageURL: "ragsofthefashionable.webp",
    tier: "b",
    index: 74,
  },
  {
    displayName: "Wedgeful Tricorn",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond23",
    internalName: "wedgefultricorn",
    imageURL: "wedgefultricorn.webp",
    tier: "b",
    index: 75,
  },
  {
    displayName: "Thundering Hooves of Loyalty",
    type: "Equipment",
    category: "cape",
    tags: [],
    warbondCode: "warbond1",
    internalName: "thunderinghoovesofloyalty",
    imageURL: "thunderinghoovesofloyalty.webp",
    tier: "b",
    index: 76,
  },
];
