MISSION_COMPLETE_ITEMS = [
  {
    displayName: 'Advanced Filtration',
    internalName: 'advancedfiltration',
    imageURL: 'advancedfiltration.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Acclimated',
    internalName: 'acclimated',
    imageURL: 'acclimated.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Democracy Protects',
    internalName: 'democracyprotects',
    imageURL: 'democracyprotects.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Electrical Conduit',
    internalName: 'electricalconduit',
    imageURL: 'electricalconduit.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Engineering Kit',
    internalName: 'engineeringkit',
    imageURL: 'engineeringkit.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Extra Padding',
    internalName: 'extrapadding',
    imageURL: 'extrapadding.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Fortified',
    internalName: 'fortified',
    imageURL: 'fortified.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Inflammable',
    internalName: 'inflammable',
    imageURL: 'inflammable.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Med-Kit',
    internalName: 'medkit',
    imageURL: 'medkit.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Peak Physique',
    internalName: 'peakphysique',
    imageURL: 'peakphysique.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Scout',
    internalName: 'scout',
    imageURL: 'scout.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Servo-Assisted',
    internalName: 'servoassisted',
    imageURL: 'servoassisted.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Unflinching',
    internalName: 'unflinching',
    imageURL: 'unflinching.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Siege Ready',
    internalName: 'siegeready',
    imageURL: 'siegeready.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Integrated Explosives',
    internalName: 'integratedexplosives',
    imageURL: 'integratedexplosives.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Gunslinger',
    internalName: 'gunslinger',
    imageURL: 'gunslinger.png',
    type: 'armorPassive',
  },
  {
    displayName: 'Peacemaker',
    internalName: 'p2peacemaker',
    imageURL: 'p2peacemaker.png',
    type: 'secondary',
  },
  {
    displayName: 'Stun Lance',
    internalName: 'cqc19stunlance',
    imageURL: 'cqc19stunlance.png',
    type: 'secondary',
  },
  {
    displayName: 'Stun Baton',
    internalName: 'cqc30stunbaton',
    imageURL: 'cqc30stunbaton.png',
    type: 'secondary',
  },
  {
    displayName: 'Stim Pistol',
    internalName: 'p11stimpistol',
    imageURL: 'p11stimpistol.png',
    type: 'secondary',
  },
  {
    displayName: 'Loyalist',
    internalName: 'plas15loyalist',
    imageURL: 'plas15loyalist.png',
    type: 'secondary',
  },
  {
    displayName: 'Bushwhacker',
    internalName: 'sg22bushwhacker',
    imageURL: 'sg22bushwhacker.png',
    type: 'secondary',
  },
  {
    displayName: 'Redeemer',
    internalName: 'p19redeemer',
    imageURL: 'p19redeemer.png',
    type: 'secondary',
  },
  {
    displayName: 'Grenade Pistol',
    internalName: 'gp31grenadepistol',
    imageURL: 'gp31grenadepistol.png',
    type: 'secondary',
  },
  {
    displayName: 'Verdict',
    internalName: 'p113verdict',
    imageURL: 'p113verdict.png',
    type: 'secondary',
  },
  {
    displayName: 'Senator',
    internalName: 'p4senator',
    imageURL: 'p4senator.png',
    type: 'secondary',
  },
  {
    displayName: 'Dagger',
    internalName: 'las7dagger',
    imageURL: 'las7dagger.png',
    type: 'secondary',
  },
  {
    displayName: 'Talon',
    internalName: 'las58talon',
    imageURL: 'las58talon.png',
    type: 'secondary',
  },
  {
    displayName: 'Crisper',
    internalName: 'p72crisper',
    imageURL: 'p72crisper.png',
    type: 'secondary',
  },
  {
    displayName: 'GP-31 Ultimatum',
    internalName: 'gp31ultimatum',
    imageURL: 'gp31ultimatum.png',
    type: 'secondary',
  },
  {
    displayName: 'G-12 High Explosive',
    internalName: 'g12highexplosivegrenade',
    imageURL: 'g12highexplosivegrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-4 Gas',
    internalName: 'g4gasgrenade',
    imageURL: 'g4gasgrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'K-2 Throwing Knife',
    internalName: 'k2throwingknife',
    imageURL: 'k2throwingknife.png',
    type: 'throwable',
  },
  {
    displayName: 'G-6 Frag',
    internalName: 'g6fraggrenade',
    imageURL: 'g6fraggrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-16 Impact',
    internalName: 'g16impactgrenade',
    imageURL: 'g16impactgrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-3 Smoke',
    internalName: 'g3smokegrenade',
    imageURL: 'g3smokegrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-10 Incendiary',
    internalName: 'g10incendiarygrenade',
    imageURL: 'g10incendiarygrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-23 Stun',
    internalName: 'g23stungrenade',
    imageURL: 'g23stungrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-123 Thermite',
    internalName: 'g123thermitegrenade',
    imageURL: 'g123thermitegrenade.png',
    type: 'throwable',
  },
  {
    displayName: 'G-13 Incendiary Impact',
    internalName: 'g13incendiaryimpact',
    imageURL: 'g13incendiaryimpact.png',
    type: 'throwable',
  },
  {
    displayName: 'G-50 Seeker',
    internalName: 'g50seeker',
    imageURL: 'g50seeker.png',
    type: 'throwable',
  },
  {
    displayName: 'TED-63 Throwable Dynamite',
    internalName: 'ted63throwabledynamite',
    imageURL: 'ted63throwabledynamite.png',
    type: 'throwable',
  },
];
