const PRIMARIES = [
  {
    displayName: 'Liberator',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'ar23liberator',
    imageURL: 'ar23liberator.png',
    tier: 'b',
  },
  {
    displayName: 'StA-11 SMG',
    type: 'Equipment',
    category: 'primary',
    tags: ['Submachinegun'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'sta11smg',
    imageURL: 'sta11smg.png',
    tier: 'b',
  },
  {
    displayName: 'PLAS-39 Accelerator Rifle',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'plas39acceleratorrifle',
    imageURL: 'plas39acceleratorrifle.png',
    tier: 'b',
  },
  {
    displayName: 'StA-52 Assault Rifle',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Superstore',
    warbondCode: 'warbond13',
    internalName: 'sta52assaultrifle',
    imageURL: 'sta52assaultrifle.png',
    tier: 'b',
  },
  {
    displayName: 'Liberator Carbine',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Viper Commandos',
    warbondCode: 'warbond8',
    internalName: 'ar23aliberatorcarbine',
    imageURL: 'ar23aliberatorcarbine.png',
    tier: 'b',
  },
  {
    displayName: 'Halt',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: 'Truth Enforcers',
    warbondCode: 'warbond11',
    internalName: 'sg20halt',
    imageURL: 'sg20halt.png',
    tier: 'a',
  },
  {
    displayName: 'Reprimand',
    type: 'Equipment',
    category: 'primary',
    tags: ['Submachinegun'],
    warbond: 'Truth Enforcers',
    warbondCode: 'warbond11',
    internalName: 'smg32reprimand',
    imageURL: 'smg32reprimand.png',
    tier: 'a',
  },
  {
    displayName: 'Constitution',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'r2124constitution',
    imageURL: 'r2124constitution.png',
    tier: 'c',
  },
  {
    displayName: 'Pummeler',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond7',
    internalName: 'smg72pummeler',
    imageURL: 'smg72pummeler.png',
    tier: 'a',
  },
  {
    displayName: 'Purifier',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond7',
    internalName: 'plas101purifier',
    imageURL: 'plas101purifier.png',
    tier: 's',
  },
  {
    displayName: 'Liberator Penetrator',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'ar23pliberatorpenetrator',
    imageURL: 'ar23pliberatorpenetrator.png',
    tier: 'a',
  },
  {
    displayName: 'Liberator Concussive',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond4',
    internalName: 'ar23cliberatorconcussive',
    imageURL: 'ar23cliberatorconcussive.png',
    tier: 'b',
  },
  {
    displayName: 'Adjudicator',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond6',
    internalName: 'br14adjudicator',
    imageURL: 'br14adjudicator.png',
    tier: 'a',
  },
  {
    displayName: 'Defender',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'smg37defender',
    imageURL: 'smg37defender.png',
    tier: 'b',
  },
  {
    displayName: 'Punisher',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'sg8punisher',
    imageURL: 'sg8punisher.png',
    tier: 'b',
  },
  {
    displayName: 'Tenderizer',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond7',
    internalName: 'ar61tenderizer',
    imageURL: 'ar61tenderizer.png',
    tier: 'a',
  },
  {
    displayName: 'Slugger',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'sg8sslugger',
    imageURL: 'sg8sslugger.png',
    tier: 'b',
  },
  {
    displayName: 'Breaker',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'sg225breaker',
    imageURL: 'sg225breaker.png',
    tier: 'b',
  },
  {
    displayName: 'Breaker Incendiary',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond4',
    internalName: 'sg225iebreakerincendiary',
    imageURL: 'sg225iebreakerincendiary.png',
    tier: 's',
  },
  {
    displayName: 'Breaker Spray & Pray',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'sg225spbreakerspraynpray',
    imageURL: 'sg225spbreakerspraynpray.png',
    tier: 'b',
  },
  {
    displayName: 'Knight',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbond: 'Super Citizen',
    warbondCode: 'warbond0',
    internalName: 'mp98knight',
    imageURL: 'mp98knight.png',
    tier: 'b',
  },
  {
    displayName: 'Diligence',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'r63diligence',
    imageURL: 'r63diligence.png',
    tier: 'b',
  },
  {
    displayName: 'Diligence Counter Sniper',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'r63csdiligencecountersniper',
    imageURL: 'r63csdiligencecountersniper.png',
    tier: 'a',
  },
  {
    displayName: 'Deadeye',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbond: 'Borderline Justice',
    warbondCode: 'warbond14',
    internalName: 'r6deadeye',
    imageURL: 'r6deadeye.png',
    tier: 'a',
  },
  {
    displayName: 'Scythe',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'las5scythe',
    imageURL: 'las5scythe.png',
    tier: 'b',
  },
  {
    displayName: 'Sickle',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond5',
    internalName: 'las16sickle',
    imageURL: 'las16sickle.png',
    tier: 'a',
  },
  {
    displayName: 'Scorcher',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond3',
    internalName: 'plas1scorcher',
    imageURL: 'plas1scorcher.png',
    tier: 's',
  },
  {
    displayName: 'Punisher Plasma',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond5',
    internalName: 'sg8ppunisherplasma',
    imageURL: 'sg8ppunisherplasma.png',
    tier: 'a',
  },
  {
    displayName: 'Blitzer',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond5',
    internalName: 'arc12blitzer',
    imageURL: 'arc12blitzer.png',
    tier: 's',
  },
  {
    displayName: 'Dominator',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive'],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond4',
    internalName: 'jar5dominator',
    imageURL: 'jar5dominator.png',
    tier: 'b',
  },
  {
    displayName: 'Eruptor',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive'],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond6',
    internalName: 'r36eruptor',
    imageURL: 'r36eruptor.png',
    tier: 's',
  },
  {
    displayName: 'Exploding Crossbow',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive'],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond6',
    internalName: 'cb9explodingcrossbow',
    imageURL: 'cb9explodingcrossbow.png',
    tier: 's',
  },
  {
    displayName: 'Cookout',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbond: "Freedom's Flame",
    warbondCode: 'warbond9',
    internalName: 'sg451cookout',
    imageURL: 'sg451cookout.png',
    tier: 'a',
  },
  {
    displayName: 'Torcher',
    type: 'Equipment',
    category: 'primary',
    tags: ['Special'],
    warbond: "Freedom's Flame",
    warbondCode: 'warbond9',
    internalName: 'flam66torcher',
    imageURL: 'flam66torcher.png',
    tier: 'b',
  },
  {
    displayName: 'Double Edge Sickle',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbond: 'Servants of Freedom',
    warbondCode: 'warbond13',
    internalName: 'las17doubleedgesickle',
    imageURL: 'las17doubleedgesickle.png',
    tier: 'a',
  },
  {
    displayName: 'R-2 Amendment',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbond: 'Masters of Ceremony',
    warbondCode: 'warbond15',
    internalName: 'r2amendment',
    imageURL: 'r2amendment.png',
    tier: 'b',
  },
  {
    displayName: 'AR-32 Pacifier',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbond: 'Force of Law',
    warbondCode: 'warbond16',
    internalName: 'ar32pacifier',
    imageURL: 'ar32pacifier.png',
    tier: 'a',
  },
];

// s: 6
// a: 13
// b: 17
// c: 1
