const PRIMARIES = [
  {
    displayName: 'Liberator',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'none',
    internalName: 'ar23liberator',
    imageURL: 'ar23liberator.png',
    antitank: false,
    tier: 'b',
    index: 0,
  },
  {
    displayName: 'Liberator Penetrator',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond3',
    internalName: 'ar23pliberatorpenetrator',
    imageURL: 'ar23pliberatorpenetrator.png',
    antitank: false,
    tier: 'a',
    index: 1,
  },
  {
    displayName: 'Liberator Concussive',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond4',
    internalName: 'ar23cliberatorconcussive',
    imageURL: 'ar23cliberatorconcussive.png',
    antitank: false,
    tier: 'b',
    index: 2,
  },
  {
    displayName: 'Liberator Carbine',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond8',
    internalName: 'ar23aliberatorcarbine',
    imageURL: 'ar23aliberatorcarbine.png',
    antitank: false,
    tier: 'a',
    index: 3,
  },
  {
    displayName: 'Adjudicator',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond6',
    internalName: 'br14adjudicator',
    imageURL: 'br14adjudicator.png',
    antitank: false,
    tier: 'a',
    index: 4,
  },
  {
    displayName: 'StA-52 Assault Rifle',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond18',
    internalName: 'sta52assaultrifle',
    imageURL: 'sta52assaultrifle.png',
    antitank: false,
    tier: 'b',
    index: 5,
  },
  {
    displayName: 'Pacifier',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond16',
    internalName: 'ar32pacifier',
    imageURL: 'ar32pacifier.png',
    antitank: false,
    tier: 'b',
    index: 6,
  },
  {
    displayName: 'Tenderizer',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond7',
    internalName: 'ar61tenderizer',
    imageURL: 'ar61tenderizer.png',
    antitank: false,
    tier: 'a',
    index: 7,
  },
  {
    displayName: 'MA5C Assault Rifle',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond19',
    internalName: 'ma5c',
    imageURL: 'ma5c.png',
    antitank: false,
    tier: 'b',
    index: 8,
  },
  {
    displayName: 'AR-2 Coyote',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond20',
    internalName: 'ar2coyote',
    imageURL: 'ar2coyote.png',
    antitank: false,
    tier: 's',
    index: 9,
  },
  {
    displayName: 'One Two',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond21',
    internalName: 'onetwo',
    imageURL: 'onetwo.webp',
    antitank: false,
    tier: 'b',
    index: 10,
  },
  {
    displayName: 'Suppressor',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond22',
    internalName: 'ar59suppressor',
    imageURL: 'ar59suppressor.webp',
    antitank: false,
    tier: 'b',
    index: 11,
  },
  {
    displayName: 'Defender',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbondCode: 'warbond3',
    internalName: 'smg37defender',
    imageURL: 'smg37defender.png',
    antitank: false,
    tier: 'b',
    index: 12,
  },
  {
    displayName: 'Pummeler',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbondCode: 'warbond7',
    internalName: 'smg72pummeler',
    imageURL: 'smg72pummeler.png',
    antitank: false,
    tier: 'b',
    index: 13,
  },
  {
    displayName: 'Reprimand',
    type: 'Equipment',
    category: 'primary',
    tags: ['Submachinegun'],
    warbondCode: 'warbond11',
    internalName: 'smg32reprimand',
    imageURL: 'smg32reprimand.png',
    antitank: false,
    tier: 'a',
    index: 14,
  },
  {
    displayName: 'StA-11 SMG',
    type: 'Equipment',
    category: 'primary',
    tags: ['Submachinegun'],
    warbondCode: 'warbond18',
    internalName: 'sta11smg',
    imageURL: 'sta11smg.png',
    antitank: false,
    tier: 'b',
    index: 15,
  },
  {
    displayName: 'Knight',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbondCode: 'warbond0',
    internalName: 'mp98knight',
    imageURL: 'mp98knight.png',
    antitank: false,
    tier: 'b',
    index: 16,
  },
  {
    displayName: 'M7S SMG',
    type: 'Equipment',
    category: 'primary',
    tags: ['SubmachineGun'],
    warbondCode: 'warbond19',
    internalName: 'm7s',
    imageURL: 'm7s.png',
    antitank: false,
    tier: 'b',
    index: 17,
  },
  {
    displayName: 'Double Freedom',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond1',
    internalName: 'doublefreedom',
    imageURL: 'doublefreedom.webp',
    antitank: false,
    tier: 'b',
    index: 18,
  },
  {
    displayName: 'Punisher',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond3',
    internalName: 'sg8punisher',
    imageURL: 'sg8punisher.png',
    antitank: false,
    tier: 'b',
    index: 19,
  },
  {
    displayName: 'Cookout',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond9',
    internalName: 'sg451cookout',
    imageURL: 'sg451cookout.png',
    antitank: false,
    tier: 'a',
    index: 20,
  },
  {
    displayName: 'Slugger',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond3',
    internalName: 'sg8sslugger',
    imageURL: 'sg8sslugger.png',
    antitank: false,
    tier: 'b',
    index: 21,
  },
  {
    displayName: 'Breaker',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond3',
    internalName: 'sg225breaker',
    imageURL: 'sg225breaker.png',
    antitank: false,
    tier: 'b',
    index: 22,
  },
  {
    displayName: 'Breaker Incendiary',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond4',
    internalName: 'sg225iebreakerincendiary',
    imageURL: 'sg225iebreakerincendiary.png',
    antitank: false,
    tier: 'a',
    index: 23,
  },
  {
    displayName: 'Breaker Spray & Pray',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond3',
    internalName: 'sg225spbreakerspraynpray',
    imageURL: 'sg225spbreakerspraynpray.png',
    antitank: false,
    tier: 'b',
    index: 24,
  },
  {
    displayName: 'Halt',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond11',
    internalName: 'sg20halt',
    imageURL: 'sg20halt.png',
    antitank: false,
    tier: 'a',
    index: 25,
  },
  {
    displayName: 'M90A Shotgun',
    type: 'Equipment',
    category: 'primary',
    tags: ['Shotgun'],
    warbondCode: 'warbond19',
    internalName: 'm90a',
    imageURL: 'm90a.png',
    antitank: false,
    tier: 'a',
    index: 26,
  },
  {
    displayName: 'Diligence',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'warbond3',
    internalName: 'r63diligence',
    imageURL: 'r63diligence.png',
    antitank: false,
    tier: 'b',
    index: 27,
  },
  {
    displayName: 'Diligence Counter Sniper',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'warbond3',
    internalName: 'r63csdiligencecountersniper',
    imageURL: 'r63csdiligencecountersniper.png',
    antitank: false,
    tier: 'b',
    index: 28,
  },
  {
    displayName: 'Deadeye',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'warbond14',
    internalName: 'r6deadeye',
    imageURL: 'r6deadeye.png',
    antitank: false,
    tier: 'a',
    index: 29,
  },
  {
    displayName: 'Amendment',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'warbond15',
    internalName: 'r2amendment',
    imageURL: 'r2amendment.png',
    antitank: false,
    tier: 'a',
    index: 30,
  },
  {
    displayName: 'Censor',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'warbond22',
    internalName: 'r72censor',
    imageURL: 'r72censor.webp',
    antitank: false,
    tier: 'a',
    index: 31,
  },
  {
    displayName: 'Constitution',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'none',
    internalName: 'r2124constitution',
    imageURL: 'r2124constitution.png',
    antitank: false,
    tier: 'c',
    index: 32,
  },
  {
    displayName: 'Scythe',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond3',
    internalName: 'las5scythe',
    imageURL: 'las5scythe.png',
    antitank: false,
    tier: 'b',
    index: 33,
  },
  {
    displayName: 'Sickle',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond5',
    internalName: 'las16sickle',
    imageURL: 'las16sickle.png',
    antitank: false,
    tier: 'a',
    index: 34,
  },
  {
    displayName: 'Scorcher',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond3',
    internalName: 'plas1scorcher',
    imageURL: 'plas1scorcher.png',
    antitank: false,
    tier: 's',
    index: 35,
  },
  {
    displayName: 'Purifier',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond7',
    internalName: 'plas101purifier',
    imageURL: 'plas101purifier.png',
    antitank: false,
    tier: 's',
    index: 36,
  },
  {
    displayName: 'Punisher Plasma',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond5',
    internalName: 'sg8ppunisherplasma',
    imageURL: 'sg8ppunisherplasma.png',
    antitank: false,
    tier: 's',
    index: 37,
  },
  {
    displayName: 'Blitzer',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond5',
    internalName: 'arc12blitzer',
    imageURL: 'arc12blitzer.png',
    antitank: false,
    tier: 's',
    index: 38,
  },
  {
    displayName: 'Double Edge Sickle',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond13',
    internalName: 'las17doubleedgesickle',
    imageURL: 'las17doubleedgesickle.png',
    antitank: false,
    tier: 'a',
    index: 39,
  },
  {
    displayName: 'PLAS-39 Accelerator Rifle',
    type: 'Equipment',
    category: 'primary',
    tags: ['MarksmanRifle'],
    warbondCode: 'warbond18',
    internalName: 'plas39acceleratorrifle',
    imageURL: 'plas39acceleratorrifle.png',
    antitank: false,
    tier: 'b',
    index: 40,
  },
  {
    displayName: 'Eruptor',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive'],
    warbondCode: 'warbond6',
    internalName: 'r36eruptor',
    imageURL: 'r36eruptor.png',
    antitank: true,
    tier: 's',
    index: 41,
  },
  {
    displayName: 'Exploding Crossbow',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive'],
    warbondCode: 'warbond6',
    internalName: 'cb9explodingcrossbow',
    imageURL: 'cb9explodingcrossbow.png',
    antitank: false,
    tier: 's',
    index: 42,
  },
  {
    displayName: 'Variable',
    type: 'Equipment',
    category: 'primary',
    tags: ['AssaultRifle'],
    warbondCode: 'warbond17',
    internalName: 'variable',
    imageURL: 'variable.png',
    antitank: false,
    tier: 'b',
    index: 43,
  },
  {
    displayName: 'Dominator',
    type: 'Equipment',
    category: 'primary',
    tags: ['Explosive'],
    warbondCode: 'warbond4',
    internalName: 'jar5dominator',
    imageURL: 'jar5dominator.png',
    antitank: false,
    tier: 'b',
    index: 44,
  },
  {
    displayName: 'Torcher',
    type: 'Equipment',
    category: 'primary',
    tags: ['Special'],
    warbondCode: 'warbond9',
    internalName: 'flam66torcher',
    imageURL: 'flam66torcher.png',
    antitank: false,
    tier: 'b',
    index: 45,
  },
  {
    displayName: 'Trident',
    type: 'Equipment',
    category: 'primary',
    tags: ['EnergyWeapon'],
    warbondCode: 'warbond23',
    internalName: 'las16trident',
    imageURL: 'las16trident.webp',
    antitank: false,
    tier: 'b',
    index: 46,
  },
];

// s: 7
// a: 17
// b: 21
// c: 1
