const PRO_TIPS = [
  "The W.A.S.P. Launcher can lock-on to the cannon turrets of Factory Striders, and destroy them with just a few shots.",
  "You can drive the FRV while carrying a package. Get into the front passenger's seat with the package, then switch seats.",
  "You can throw stratagems as a passenger in the FRV.",
  "To help keep the FRV from rolling away, hold the parking brake button as you're getting out.",
  "You can use the jump pack while holding a SEAF Artillery shell. Have the shell in front of you, move toward it and jump, and grab it right when you're leaving the ground.",
  "Tell every new player you see that samples and other resources are shared!",
  "Avoid being in a sentry's line of fire by placing it above or below you, around a corner, or over a wall.",
  "One Seeker grenade can take down a gunship. Simply throw the grenade, then ping the gunship.",
  "Eagle Smoke Strike can destroy bug holes and bot fabricators.",
  "Orbital EMS Strike can take out bug holes.",
  "You can destroy Bile Titan holes by calling down a hellpod on the edge of the hole.",
  "Recoil can be mostly or completely negated by being prone, even if you're not aiming down sights.",
  "The Crisper and other flame weapons can quickly destroy a Factory Strider by shooting it in the belly.",
  "The minimum safe distance from the Orbital 380mm Barrage, Orbital Napalm Barrage, and Orbital Walking Barrage is 50 meters.",
  "If all enemy outposts are destroyed during the extraction countdown, enemies will spawn from the closest edge of the map.",
  "The least risky way to kill a Hulk with the Railgun is to destroy its legs.",
  "The PLAS-39 Accelerator Rifle can destroy tanks and cannon turrets with 2 bursts into the heat sink.",
  "Chargers, Hulks, and Fleshmobs are some of the easiest enemies to stick a stratagem ball.",
  "Eagle Smoke Strike and Orbital Smoke Strike are generally more effective when used on your current position, rather than throwing it at the enemy.",
  "Damage taken from the Double-Edge Sickle can be heavily reduced by wearing heavy Inflammable armor, and using the Vitality booster.",
  "The Guard Dog Breath is extremely effective at keeping you safe from the Predator Strain, and in close-range encounters in general.",
  "You can easily kill Hulks, Chargers, Impalers, and Fleshmobs with the Airburst Rocket Launcher by firing a rocket underneath them in Flak mode.",
  "You can kill groups of enemies over walls with the Airburst Rocket Launcher by switching to the Cluster firing mode.",
  "You can plant the One True Flag into the FRV, Guard Dogs, and live enemies.",
  "The Urchin grenades will interrupt Bile Titan attacks.",
  "You can put your Guard Dog back into your backpack. This is useful when you don't want to immediately engage nearby enemies.",
  "The Tesla Tower, and Illuminate Lightning Spires, won't target you when you're prone.",
  "The Muscle Enhancement booster increases movement speed through snow, sand, mud, blizzards, and sandstorms.",
  "Damage taken from the Dead Sprint booster can be heavily reduced with the Vitality booster.",
  "You can completely refill a Supply Pack from a Resupply pod, as well as the ammo of everyone on your team, by passing the Supply Pack to each teammate as they grab a Resupply box.",
  "Enemies generally prioritize destroying sentries, Shield Generator Relays, and Hellbombs over Helldivers. Useful when you need a decoy.",
  "After arming a Hellbomb, you can cause it to pre-emptively explode by shooting it.",
  "The Deadeye can one-shot Overseers by shooting them in the head.",
  "Reinforced Scout Striders can be easily destroyed, even with light penetration weapons, by shooting the rockets on their sides.",
  "The Orbital Gas Strike can destroy Rogue Research Stations, Stratagem Jammers, and shielded Illuminate Warpships.",
  "SEAF Artillery can still be used when the mission timer runs out, as well as in the vicinity of an active Stratagem Jammer.",
  "The SEAF Mini Nuke artillery shell can destroy Gunship Fabricators.",
  "Devastators can easily be taken out with light penetration weapons by aiming for their head, or below the waist.",
  "Your Helldiver has almost perfect aim while diving, even without aiming down sights. Use this to your advantage to get the most out of your movements in close range combat.",
  "The Exploding Crossbow can be used to stealthily divert enemy patrols by firing a bolt in the direction you want the patrol to go.",
  "Points of Interest will reveal themselves on the minimap when you hover the minimap cursor over them.",
  "The SEAF Artillery objective is the easiest objective to spot on your minimap, generally showing up as a circle or two circles next to each other.",
  "You can stim a teammate wearing the Shield Generator Pack with the stim pistol by standing directly next to them, inside of the shield.",
  "To save ammo while using an Exosuit, use melee attacks against small enemies in close quarters.",
  "Reloading the Senator and Stim Pistol is faster when the cylinder is completely empty.",
  "Reloading the Autocannon is significantly faster when there is at least one round in the magazine. This applies to many other weapons as well.",
  "Your Helldiver will start spinning the Senator, Talon, and Stim Pistol if you hold the reload button.",
  "When a headless bug is charging you, hit them with a melee attack when they get close enough. It will interrupt their charge, and they will typically die shortly after.",
  "The Autocannon has two firing modes: Flak mode is most effective against chaff, and APHET mode is best for heavy units.",
  "Two headshots with the Senator will leave the Hive Guard to bleed out, and die shortly after.",
  "If you find yourself running out of ammo often, try tap firing your weapon, switching to burst mode, or lowering the fire rate.",
  "You can teleport in and out of buddy bunkers, and destroy storage container doors, with the warp pack.",
  "While using the Total firing mode with the Variable, you can prevent yourself from getting knocked over by firing while prone.",
  "To get the maximum distance with the Ultimatum, dive while firing at a 45 degree angle. You can launch the projectile at a maximum range of about 55 meters.",
  "The Ballistic Shield will block attacks from the Tesla Tower.",
];
