const SECONDARIES = [
  {
    displayName: 'Peacemaker',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'None',
    warbondCode: 'none',
    internalName: 'p2peacemaker',
    imageURL: 'p2peacemaker.png',
  },
  {
    displayName: 'Stun Lance',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Urban Legends',
    warbondCode: 'warbond10',
    internalName: 'cqc19stunlance',
    imageURL: 'cqc19stunlance.png',
  },
  {
    displayName: 'Stun Baton',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Superstore',
    warbondCode: 'warbond11',
    internalName: 'cqc30stunbaton',
    imageURL: 'cqc30stunbaton.png',
  },
  {
    displayName: 'Stim Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Chemical Agents',
    warbondCode: 'warbond8',
    internalName: 'p11stimpistol',
    imageURL: 'p11stimpistol.png',
  },
  {
    displayName: 'Loyalist',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Truth Enforcers',
    warbondCode: 'warbond9',
    internalName: 'plas15loyalist',
    imageURL: 'plas15loyalist.png',
  },
  {
    displayName: 'Bushwhacker',
    type: 'Equipment',
    category: 'secondary',
    tags: ['Shotgun'],
    warbond: 'Viper Commandos',
    warbondCode: 'warbond6',
    internalName: 'sg22bushwhacker',
    imageURL: 'sg22bushwhacker.png',
  },
  {
    displayName: 'Redeemer',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Helldivers Mobilize',
    warbondCode: 'warbond1',
    internalName: 'p19redeemer',
    imageURL: 'p19redeemer.png',
  },
  {
    displayName: 'Grenade Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Democratic Detonation',
    warbondCode: 'warbond4',
    internalName: 'gp31grenadepistol',
    imageURL: 'gp31grenadepistol.png',
  },
  {
    displayName: 'Verdict',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Polar Patriots',
    warbondCode: 'warbond5',
    internalName: 'p113verdict',
    imageURL: 'p113verdict.png',
  },
  {
    displayName: 'Senator',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Steeled Veterans',
    warbondCode: 'warbond2',
    internalName: 'p4senator',
    imageURL: 'p4senator.png',
  },
  {
    displayName: 'Dagger',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond3',
    internalName: 'las7dagger',
    imageURL: 'las7dagger.png',
  },
  {
    displayName: 'Talon',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Borderline Justice',
    warbondCode: 'warbond12',
    internalName: 'las58talon',
    imageURL: 'las58talon.png',
  },
  {
    displayName: 'Crisper',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Cutting Edge',
    warbondCode: 'warbond7',
    internalName: 'p72crisper',
    imageURL: 'p72crisper.png',
  },
  {
    displayName: 'GP-31 Ultimatum',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbond: 'Servants of Freedom',
    warbondCode: 'warbond11',
    internalName: 'gp31ultimatum',
    imageURL: 'gp31ultimatum.png',
  },
];
