const SECONDARIES = [
  {
    displayName: 'Peacemaker',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'none',
    internalName: 'p2peacemaker',
    imageURL: 'p2peacemaker.png',
    antitank: false,
    index: 0,
    tier: 'c',
  },
  {
    displayName: 'Combat Hatchet',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'cqc5combathatchet',
    imageURL: 'cqc5combathatchet.png',
    antitank: false,
    index: 1,
    tier: 'c',
  },
  {
    displayName: 'Saber',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond15',
    internalName: 'cqc2saber',
    imageURL: 'cqc2saber.png',
    antitank: false,
    index: 2,
    tier: 'c',
  },
  {
    displayName: 'Machete',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'cqc42machete',
    imageURL: 'cqc42machete.png',
    antitank: false,
    index: 3,
    tier: 'c',
  },
  {
    displayName: 'Stun Lance',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond12',
    internalName: 'cqc19stunlance',
    imageURL: 'cqc19stunlance.png',
    antitank: false,
    index: 4,
    tier: 'c',
  },
  {
    displayName: 'Stun Baton',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'cqc30stunbaton',
    imageURL: 'cqc30stunbaton.png',
    antitank: false,
    index: 5,
    tier: 'c',
  },
  {
    displayName: 'Redeemer',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'p19redeemer',
    imageURL: 'p19redeemer.png',
    antitank: false,
    index: 6,
    tier: 'b',
  },
  {
    displayName: 'Verdict',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond7',
    internalName: 'p113verdict',
    imageURL: 'p113verdict.png',
    antitank: false,
    index: 7,
    tier: 'b',
  },
  {
    displayName: 'Senator',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond4',
    internalName: 'p4senator',
    imageURL: 'p4senator.png',
    antitank: false,
    index: 8,
    tier: 'a',
  },
  {
    displayName: 'P-92 Warrant',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'p92warrant',
    imageURL: 'p92warrant.png',
    antitank: false,
    index: 9,
    tier: 'b',
  },
  {
    displayName: 'M6C/SOCOM',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond19',
    internalName: 'm6csocompistol',
    imageURL: 'm6csocompistol.png',
    antitank: false,
    index: 10,
    tier: 'b',
  },
  {
    displayName: 'Stim Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond10',
    internalName: 'p11stimpistol',
    imageURL: 'p11stimpistol.png',
    antitank: false,
    index: 11,
    tier: 'b',
  },
  {
    displayName: 'Loyalist',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond11',
    internalName: 'plas15loyalist',
    imageURL: 'plas15loyalist.png',
    antitank: false,
    index: 12,
    tier: 'a',
  },
  {
    displayName: 'Bushwhacker',
    type: 'Equipment',
    category: 'secondary',
    tags: ['Shotgun'],
    warbondCode: 'warbond8',
    internalName: 'sg22bushwhacker',
    imageURL: 'sg22bushwhacker.png',
    antitank: false,
    index: 13,
    tier: 'b',
  },
  {
    displayName: 'Grenade Pistol',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond6',
    internalName: 'gp31grenadepistol',
    imageURL: 'gp31grenadepistol.png',
    antitank: false,
    index: 14,
    tier: 's',
  },
  {
    displayName: 'Re-Educator',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond22',
    internalName: 'p35reeducator',
    imageURL: 'p35reeducator.webp',
    antitank: false,
    index: 15,
    tier: 'b',
  },
  {
    displayName: 'Dagger',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond5',
    internalName: 'las7dagger',
    imageURL: 'las7dagger.png',
    antitank: false,
    index: 16,
    tier: 'c',
  },
  {
    displayName: 'Talon',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond14',
    internalName: 'las58talon',
    imageURL: 'las58talon.png',
    antitank: false,
    index: 17,
    tier: 'a',
  },
  {
    displayName: 'Crisper',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond9',
    internalName: 'p72crisper',
    imageURL: 'p72crisper.png',
    antitank: false,
    index: 18,
    tier: 'b',
  },
  {
    displayName: 'GP-31 Ultimatum',
    type: 'Equipment',
    category: 'secondary',
    tags: [],
    warbondCode: 'warbond13',
    internalName: 'gp31ultimatum',
    imageURL: 'gp31ultimatum.png',
    antitank: true,
    index: 19,
    tier: 's',
  },
];

// s: 2
// a: 4
// b: 6
// c: 6
