const SECONDARIES = [
  {
    displayName: "Peacemaker",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "none",
    internalName: "p2peacemaker",
    imageURL: "p2peacemaker.png",
    tier: "c",
  },
  {
    displayName: "Combat Hatchet",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "cqc5combathatchet",
    imageURL: "cqc5combathatchet.png",
    tier: "c",
  },
  {
    displayName: "Saber",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond15",
    internalName: "cqc2saber",
    imageURL: "cqc2saber.png",
    tier: "c",
  },
  {
    displayName: "Stun Lance",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond12",
    internalName: "cqc19stunlance",
    imageURL: "cqc19stunlance.png",
    tier: "c",
  },
  {
    displayName: "Stun Baton",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "cqc30stunbaton",
    imageURL: "cqc30stunbaton.png",
    tier: "c",
  },
  {
    displayName: "Stim Pistol",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond10",
    internalName: "p11stimpistol",
    imageURL: "p11stimpistol.png",
    tier: "b",
  },
  {
    displayName: "Loyalist",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond11",
    internalName: "plas15loyalist",
    imageURL: "plas15loyalist.png",
    tier: "a",
  },
  {
    displayName: "Bushwhacker",
    type: "Equipment",
    category: "secondary",
    tags: ["Shotgun"],
    warbondCode: "warbond8",
    internalName: "sg22bushwhacker",
    imageURL: "sg22bushwhacker.png",
    tier: "b",
  },
  {
    displayName: "Redeemer",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond3",
    internalName: "p19redeemer",
    imageURL: "p19redeemer.png",
    tier: "b",
  },
  {
    displayName: "Grenade Pistol",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond6",
    internalName: "gp31grenadepistol",
    imageURL: "gp31grenadepistol.png",
    tier: "s",
  },
  {
    displayName: "Verdict",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond7",
    internalName: "p113verdict",
    imageURL: "p113verdict.png",
    tier: "a",
  },
  {
    displayName: "Senator",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond4",
    internalName: "p4senator",
    imageURL: "p4senator.png",
    tier: "a",
  },
  {
    displayName: "Dagger",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond5",
    internalName: "las7dagger",
    imageURL: "las7dagger.png",
    tier: "c",
  },
  {
    displayName: "Talon",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond14",
    internalName: "las58talon",
    imageURL: "las58talon.png",
    tier: "a",
  },
  {
    displayName: "Crisper",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond9",
    internalName: "p72crisper",
    imageURL: "p72crisper.png",
    tier: "b",
  },
  {
    displayName: "GP-31 Ultimatum",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond13",
    internalName: "gp31ultimatum",
    imageURL: "gp31ultimatum.png",
    tier: "s",
  },
  {
    displayName: "P-92 Warrant",
    type: "Equipment",
    category: "secondary",
    tags: [],
    warbondCode: "warbond1",
    internalName: "p92warrant",
    imageURL: "p92warrant.png",
    tier: "b",
  },

  // {
  //   displayName: "M6C/SOCOM Pistol",
  //   type: "Equipment",
  //   category: "secondary",
  //   tags: [],
  //   warbondCode: "warbond19",
  //   internalName: "m6csocompistol",
  //   imageURL: "m6csocompistol.png",
  //   tier: "b",
  // },
];

// s: 2
// a: 4
// b: 5
// c: 6
