const ybwamahe = 'You begin with, and must always have equipped, ';
const SPECIALISTS = [
  {
    displayName: 'The Zealous Martyr',
    starterItems: ['Portable Hellbomb', 'Combat Hatchet', 'Integrated Explosives armor'],
    stratagems: ['portablehellbomb'],
    primaries: [],
    boosters: [],
    secondaries: ['cqc5combathatchet'],
    throwables: [],
    armorPassives: ['integratedexplosives'],
    traits: [],
  },
  {
    displayName: 'The Permacura Rep',
    starterItems: ['Stim Pistol', 'Med-Kit armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ['stimpistol'],
    throwables: [],
    armorPassives: ['medkit'],
    traits: [],
  },
  {
    displayName: 'The Sheriff',
    starterItems: ['Senator or Talon', 'Gunslinger armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ['p4senator', 'las58talon'],
    throwables: [],
    armorPassives: ['gunslinger'],
    traits: ['You cannot roll support weapons'],
  },
  {
    displayName: 'The Speedrunner',
    starterItems: ['Fast Recon Vehicle', 'Expert Extraction Pilot booster or Dead Sprint booster'],
    stratagems: ['fastreconvehicle'],
    primaries: [],
    boosters: [],
    secondaries: ['deadsprint', 'expertextractionpilot'],
    throwables: [],
    armorPassives: [],
    traits: [],
  },
  {
    displayName: 'The Viper Commando',
    starterItems: ['Liberator Carbine', 'Peak Physique armor', 'Throwing Knives'],
    stratagems: [],
    primaries: ['ar23aliberatorcarbine'],
    boosters: [],
    secondaries: [],
    throwables: ['k2throwingknife'],
    armorPassives: ['peakphysique'],
    traits: [],
  },
  {
    displayName: 'The Pyromaniac',
    starterItems: ['Torcher', 'Inflammable armor'],
    stratagems: [],
    primaries: ['flam66torcher'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['inflammable'],
    traits: [],
  },
  {
    displayName: 'The Lightning Bug',
    starterItems: ['Arc Thrower', 'Tesla Tower', 'Electrical Conduit armor'],
    stratagems: ['arc3arcthrower', 'teslatower'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['electricalconduit'],
    traits: [],
  },
  {
    displayName: 'The Scout Sniper',
    starterItems: ['Diligence Marksman Rifle', 'UAV Recon booster', 'Scout armor'],
    stratagems: [],
    primaries: ['r63diligence'],
    boosters: ['uavrecon'],
    secondaries: [],
    throwables: [],
    armorPassives: ['scout'],
    traits: [],
  },
  {
    displayName: 'The Hellpod Enthusiast',
    starterItems: ['Expendable Anti-Tank', 'Commando', 'Firebomb Hellpods booster'],
    stratagems: ['eat17expendableantitank', 'mls4xcommandorocketlauncher'],
    primaries: [],
    boosters: ['firebombhellpods'],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['You cannot roll Eagle or Orbital strategems'],
  },
  {
    displayName: 'The O.G.',
    starterItems: ['Liberator'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [
      'You must always have the B-01 Tactical armor equipped',
      'Chance of rolling high-tier items is increased',
    ],
  },
  {
    displayName: 'The Truth Enforcer',
    starterItems: ['Reprimand or Halt', 'Unflinching armor'],
    stratagems: [],
    primaries: ['smg32reprimand', 'sg20halt'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['unflinching'],
    traits: [],
  },
  {
    displayName: 'The Exterminator',
    starterItems: ['Gas grenades', 'Sterilizer', 'Advanced Filtration armor'],
    stratagems: [],
    primaries: ['tx41sterilizer'],
    boosters: [],
    secondaries: [],
    throwables: ['g4gasgrenade'],
    armorPassives: ['advancedfiltration'],
    traits: [],
  },
  {
    displayName: 'The Urban Soldier',
    starterItems: ['Siege Ready armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['You can only roll one-handed primary weapons'],
  },
  {
    displayName: 'The Assault Trooper',
    starterItems: [
      'StA-52 Assault Rifle, PLAS-39 Accelerator Rifle, or StA-11 SMG',
      'Acclimated armor',
    ],
    stratagems: [],
    primaries: ['sta52assaultrifle', 'plas39acceleratorrifle', 'sta11smg'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['acclimated'],
    traits: [],
  },
  {
    displayName: 'The Loot Goblin',
    starterItems: ['Supply Pack', 'Sample Extricator booster'],
    stratagems: ['b1supplypack'],
    primaries: [],
    boosters: ['sampleextricator'],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
  },
  {
    displayName: 'The Escape Artist',
    starterItems: ['Jump Pack', 'Smoke Grenades'],
    stratagems: ['lift850jumppack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['g3smokegrenade'],
    armorPassives: [],
    traits: [],
  },
];
