const SPECOPSSPECS = [
  {
    locked: true,
    displayName: "The Arsonist",
    stratagems: [
      "Flamethrower",
      "Eagle Napalm Strike",
      "Orbital Napalm Barrage",
      "Flame Sentry",
    ],
    primary: "Torcher",
    secondary: "Crisper",
    throwable: "G-10 Incendiary",
    armorPassive: "Inflammable",
  },
  {
    locked: true,
    displayName: "The Asphyxiator",
    stratagems: [
      "Sterilizer",
      "Orbital Gas Strike",
      "Gas Mines",
      "Guard Dog Breath",
    ],
    primary: "Pummeler",
    secondary: "Crisper",
    throwable: "G-4 Gas",
    armorPassive: "Advanced Filtration",
  },
  {
    locked: true,
    displayName: "The O.G.",
    stratagems: [
      "Machine Gun",
      "Orbital Precision Strike",
      "Machine Gun Sentry",
      "Eagle Airstrike",
    ],
    primary: "Liberator",
    secondary: "Peacemaker",
    throwable: "G-12 High Explosive",
    armorPassive: "Extra Padding",
  },
  {
    locked: true,
    displayName: "The Engineer",
    stratagems: [
      "Autocannon Sentry",
      "HMG Emplacement",
      "Shield Generator Relay",
      "Mortar Sentry",
    ],
    primary: "Defender",
    secondary: "P-92 Warrant",
    throwable: "G-50 Seeker",
    armorPassive: "Engineering Kit",
  },
  {
    locked: true,
    displayName: "Eagle-1's Favorite",
    stratagems: [
      "Eagle 500kg Bomb",
      "Eagle Airstrike",
      "Eagle Strafing Run",
      "Eagle Cluster Bomb",
    ],
    primary: "StA-11 SMG",
    secondary: "Talon",
    throwable: "G-6 Frag",
    armorPassive: "Servo-Assisted",
  },
  {
    locked: true,
    displayName: "Former Bridge Officer",
    stratagems: [
      "Orbital Walking Barrage",
      "Orbital Precision Strike",
      "Orbital 120mm HE Barrage",
      "Orbital Airburst Strike",
    ],
    primary: "Punisher",
    secondary: "Verdict",
    throwable: "G-6 Frag",
    armorPassive: "Reinforced Epaulettes",
  },
  {
    locked: true,
    displayName: "The Tankbuster",
    stratagems: [
      "Recoilless Rifle",
      "Eagle 110mm Rocket Pods",
      "Orbital Railcannon Strike",
      "Anti-Tank Mines",
    ],
    primary: "Eruptor",
    secondary: "GP-31 Ultimatum",
    throwable: "G-123 Thermite",
    armorPassive: "Fortified",
  },
  {
    locked: true,
    displayName: "The Stunner",
    stratagems: [
      "GL-52 De-Escalator",
      "Orbital EMS Strike",
      "EMS Mortar Sentry",
      "Guard Dog Arc",
    ],
    primary: "Halt",
    secondary: "Bushwhacker",
    throwable: "G-23 Stun",
    armorPassive: "Ballistic Padding",
  },
  {
    locked: true,
    displayName: "The Detonator",
    stratagems: [
      "Grenade Launcher",
      "Eagle Cluster Bomb",
      "Portable Hellbomb",
      "Anti-Personnel Minefield",
    ],
    primary: "Exploding Crossbow",
    secondary: "Grenade Pistol",
    throwable: "Throwable Dynamite",
    armorPassive: "Integrated Explosives",
  },
  {
    locked: true,
    displayName: "The Ghost",
    stratagems: [
      "Orbital Smoke Strike",
      "Eagle Smoke Strike",
      "Anti-Material Rifle",
      "Hover Pack",
    ],
    primary: "Diligence",
    secondary: "Redeemer",
    throwable: "K-2 Throwing Knife",
    armorPassive: "Scout",
  },
  {
    locked: true,
    displayName: "The Most Democratic",
    stratagems: [
      "Portable Hellbomb",
      "One True Flag",
      "Orbital 380mm HE Barrage",
      "Eagle 500kg Bomb",
    ],
    primary: "Constitution",
    secondary: "Senator",
    throwable: "G-12 High Explosive",
    armorPassive: "Democracy Protects",
  },
  {
    locked: true,
    displayName: "The Wallbouncer",
    stratagems: [
      "Expendable Anti-Tank",
      "Commando",
      "Eagle Strafing Run",
      "Jump Pack",
    ],
    primary: "Slugger",
    secondary: "Senator",
    throwable: "G-12 High Explosive",
    armorPassive: "Extra Padding",
  },
  {
    locked: true,
    displayName: "Dark Render",
    stratagems: [
      "Autocannon Sentry",
      "Recoilless Rifle",
      "Orbital Walking Barrage",
      "Eagle Strafing Run",
    ],
    primary: "Deadeye",
    secondary: "Senator",
    throwable: "G-4 Gas",
    armorPassive: "Servo-Assisted",
  },
  {
    locked: true,
    displayName: "Tyler Johnson the GOAT",
    stratagems: [
      "Eagle Airstrike",
      "Orbital 120mm HE Barrage",
      "Autocannon Sentry",
      "Machine Gun",
    ],
    primary: "Liberator Penetrator",
    secondary: "Grenade Pistol",
    throwable: "G-123 Thermite",
    armorPassive: "Extra Padding",
  },
  {
    locked: true,
    displayName: "The Paramedic",
    stratagems: [
      "Eagle Smoke Strike",
      "Shield Generator Relay",
      "Supply Pack",
      "Fast Recon Vehicle",
    ],
    primary: "Liberator Concussive",
    secondary: "Stim Pistol",
    throwable: "G-3 Smoke",
    armorPassive: "Med-Kit",
  },
  {
    locked: true,
    displayName: "The Viper Commando",
    stratagems: [
      "Commando",
      "Orbital Laser",
      "Anti-Personnel Minefield",
      "Patriot Exosuit",
    ],
    primary: "Liberator Carbine",
    secondary: "Bushwhacker",
    throwable: "K-2 Throwing Knife",
    armorPassive: "Peak Physique",
  },
  {
    locked: true,
    displayName: "The Peace Officer",
    stratagems: [
      "Ballistic Shield",
      "GL-52 De-Escalator",
      "Grenadier Battlement",
      "Fast Recon Vehicle",
    ],
    primary: "AR-32 Pacifier",
    secondary: "Stun Baton",
    throwable: "G-4 Gas",
    armorPassive: "Ballistic Padding",
  },
  {
    locked: true,
    displayName: "Child of Helghan",
    stratagems: [
      "W.A.S.P. Launcher",
      "Orbital Napalm Barrage",
      "Gas Mines",
      "Tesla Tower",
    ],
    primary: "StA-52 Assault Rifle",
    secondary: "Verdict",
    throwable: "G-12 High Explosive",
    armorPassive: "Acclimated",
  },
  {
    locked: true,
    displayName: "The Overwatch",
    stratagems: [
      "Supply Pack",
      "Heavy Machine Gun",
      "Anti-Tank Emplacement",
      "Eagle 500kg Bomb",
    ],
    primary: "Liberator Penetrator",
    secondary: "Grenade Pistol",
    throwable: "G-123 Thermite",
    armorPassive: "Engineering Kit",
  },
  {
    locked: true,
    displayName: "The Heavy Gunner",
    stratagems: [
      "Heavy Machine Gun",
      "HMG Emplacement",
      "Orbital Gatling Barrage",
      "Guard Dog Bullets",
    ],
    primary: "Adjudicator",
    secondary: "Verdict",
    throwable: "G-16 Impact",
    armorPassive: "Siege Ready",
  },
  {
    locked: true,
    displayName: "The Autocannoneer",
    stratagems: [
      "Autocannon",
      "Autocannon Sentry",
      "Emancipator Exosuit",
      "Eagle Strafing Run",
    ],
    primary: "Tenderizer",
    secondary: "Talon",
    throwable: "G-13 Incendiary Impact",
    armorPassive: "Fortified",
  },
  {
    locked: true,
    displayName: "The Lightshow",
    stratagems: [
      "Laser Cannon",
      "Orbital Laser",
      "Guard Dog Laser",
      "Laser Sentry",
    ],
    primary: "Scythe",
    secondary: "Dagger",
    throwable: "G-142 Pyrotech",
    armorPassive: "Unflinching",
  },
  {
    locked: true,
    displayName: "The Stormcaller",
    stratagems: [
      "Arc Thrower",
      "Guard Dog Arc",
      "Tesla Tower",
      "Orbital EMS Strike",
    ],
    primary: "Blitzer",
    secondary: "Peacemaker",
    throwable: "G-31 Arc",
    armorPassive: "Electrical Conduit",
  },
  {
    locked: true,
    displayName: "The Bullet Whisperer",
    stratagems: [
      "Stalwart",
      "Orbital Gatling Barrage",
      "Gatling Sentry",
      "Eagle Strafing Run",
    ],
    primary: "Variable",
    secondary: "Redeemer",
    throwable: "G-6 Frag",
    armorPassive: "Siege Ready",
  },
  {
    locked: true,
    displayName: "The Mad Scientist",
    stratagems: ["Epoch", "Warp Pack", "Orbital Laser", "Tesla Tower"],
    primary: "Scorcher",
    secondary: "Loyalist",
    throwable: "G-142 Pyrotech",
    armorPassive: "Adreno-Defibrillator",
  },
  {
    locked: true,
    displayName: "The Problem Child",
    stratagems: [
      "Airburst Rocket Launcher",
      "Orbital Napalm Barrage",
      "Mortar Sentry",
      "Incendiary Mines",
    ],
    primary: "Blitzer",
    secondary: "GP-31 Ultimatum",
    throwable: "G-31 Arc",
    armorPassive: "Integrated Explosives",
  },
  {
    locked: true,
    displayName: "The Penitent",
    stratagems: [
      "One True Flag",
      "Orbital EMS Strike",
      "Orbital Smoke Strike",
      "Eagle Smoke Strike",
    ],
    primary: "Constitution",
    secondary: "Combat Hatchet",
    throwable: "K-2 Throwing Knife",
    armorPassive: "Integrated Explosives",
  },
];
