const SPECIALOPSOBJECTIVES = [
  {
    name: "Extract with the High-Value Item 1 time",
    goal: 1,
    progress: 0,
    progressType: "positive",
    id: 0,
    inputType: "num",
    inputName: "High Value Items Collected:",
  },
  {
    name: "Kill a total of X enemies",
    goal: 300,
    progress: 0,
    progressType: "positive",
    id: 1,
    inputType: "num",
    inputName: "Enemies Killed:",
  },
  {
    name: "Die less than X times",
    goal: 8,
    progress: 0,
    progressType: "negative",
    id: 2,
    inputType: "num",
    inputName: "Deaths:",
  },
  {
    name: "Collect X common samples",
    goal: 20,
    progress: 0,
    progressType: "positive",
    id: 3,
    inputType: "num",
    inputName: "Common Samples Collected:",
  },
  {
    name: "Collect X rare samples",
    goal: 12,
    progress: 0,
    progressType: "positive",
    id: 4,
    inputType: "num",
    inputName: "Rare Samples Collected:",
  },
  {
    name: "Collect X super samples",
    goal: 7,
    progress: 0,
    progressType: "positive",
    id: 5,
    inputType: "num",
    inputName: "Super Samples Collected:",
  },
  {
    name: "Have less than X accidentals",
    goal: 4,
    progress: 0,
    progressType: "negative",
    id: 6,
    inputType: "num",
    inputName: "Accidentals:",
  },
  {
    name: "Earn X stars",
    goal: 12,
    progress: 0,
    progressType: "positive",
    id: 7,
    inputType: "num",
    inputName: "Stars Earned:",
  },
  // {
  //   name: "Have an average of more than X% mission time remaining",
  //   goal: 33,
  //   progress: 0,
  //   progressType: "positive",
  //   id: 8,
  //   inputType: "num",
  //   inputName: "Time Remaining (%):",
  // },
  {
    name: "Perform X melee kills",
    goal: 20,
    progress: 0,
    progressType: "positive",
    id: 9,
    inputType: "num",
    inputName: "Melee Kills:",
  },
];
