const SPECOPSSPECS = [
  {
    locked: true,
    displayName: 'The Arsonist',
    stratagems: [1, 27, 46, 61, 67],
    primary: 20,
    secondary: 18,
    throwable: 4,
    armorPassive: 7,
    warbonds: ['warbond9', 'warbond12', 'warbond4', 'warbond21'],
  },
  {
    locked: true,
    displayName: 'The Asphyxiator',
    stratagems: [0, 51, 77, 28],
    primary: 23,
    secondary: 15,
    throwable: 12,
    armorPassive: 0,
    warbonds: ['warbond10', 'warbond22', 'warbond4'],
  },
  {
    locked: true,
    displayName: 'The O.G.',
    stratagems: [5, 50, 65, 44],
    primary: 0,
    secondary: 0,
    throwable: 0,
    armorPassive: 5,
    warbonds: [],
  },
  {
    locked: true,
    displayName: 'The Engineer',
    stratagems: [70, 17, 71, 63],
    primary: 12,
    secondary: 9,
    throwable: 9,
    armorPassive: 4,
    warbonds: ['warbond1', 'warbond13', 'warbond20'],
  },
  {
    locked: true,
    displayName: "Eagle-1's Favorite",
    stratagems: [49, 44, 43, 45],
    primary: 30,
    secondary: 17,
    throwable: 1,
    armorPassive: 11,
    warbonds: ['warbond14', 'warbond15'],
  },
  {
    locked: true,
    displayName: 'Former Bridge Officer',
    stratagems: [54, 50, 58, 59],
    primary: 7,
    secondary: 2,
    throwable: 1,
    armorPassive: 16,
    warbonds: ['warbond15', 'warbond7'],
  },
  {
    locked: true,
    displayName: 'The Tankbuster',
    stratagems: [25, 48, 55, 75],
    primary: 41,
    secondary: 19,
    throwable: 6,
    armorPassive: 6,
    warbonds: ['warbond6', 'warbond13', 'warbond6'],
  },
  {
    locked: true,
    displayName: 'The Stunner',
    stratagems: [9, 52, 64, 31],
    primary: 25,
    secondary: 6,
    throwable: 5,
    armorPassive: 17,
    warbonds: ['warbond16', 'warbond11', 'warbond5', 'warbond8'],
  },
  {
    locked: true,
    displayName: 'The Detonator',
    stratagems: [8, 45, 39, 76],
    primary: 42,
    secondary: 0,
    throwable: 15,
    armorPassive: 14,
    warbonds: ['warbond13', 'warbond6', 'warbond20', 'warbond13'],
  },
  {
    locked: true,
    displayName: 'The Ghost',
    stratagems: [53, 47, 10, 33],
    primary: 27,
    secondary: 17,
    throwable: 8,
    armorPassive: 10,
    warbonds: ['warbond14', 'warbond8'],
  },
  {
    locked: true,
    displayName: 'The Most Democratic',
    stratagems: [39, 18, 59, 49],
    primary: 32,
    secondary: 8,
    throwable: 0,
    armorPassive: 2,
    warbonds: ['warbond13', 'warbond15', 'warbond4'],
  },
  {
    locked: true,
    displayName: 'The Wallbouncer',
    stratagems: [14, 15, 43, 32],
    primary: 21,
    secondary: 8,
    throwable: 0,
    armorPassive: 5,
    warbonds: ['warbond4'],
  },
  {
    locked: true,
    displayName: 'Dark Render',
    stratagems: [69, 24, 60, 43],
    primary: 29,
    secondary: 8,
    throwable: 12,
    armorPassive: 11,
    warbonds: ['warbond14', 'warbond4', 'warbond10'],
  },
  {
    locked: true,
    displayName: 'Tyler Johnson the GOAT',
    stratagems: [44, 58, 69, 5],
    primary: 1,
    secondary: 14,
    throwable: 6,
    armorPassive: 5,
    warbonds: ['warbond6'],
  },
  {
    locked: true,
    displayName: 'The Paramedic',
    stratagems: [47, 71, 35, 40],
    primary: 2,
    secondary: 11,
    throwable: 3,
    armorPassive: 8,
    warbonds: ['warbond4', 'warbond10'],
  },
  {
    locked: true,
    displayName: 'The Viper Commando',
    stratagems: [15, 56, 76, 41],
    primary: 3,
    secondary: 13,
    throwable: 8,
    armorPassive: 9,
    warbonds: ['warbond8'],
  },
  {
    locked: true,
    displayName: 'The Peace Officer',
    stratagems: [38, 9, 74, 40],
    primary: 6,
    secondary: 4,
    throwable: 12,
    armorPassive: 17,
    warbonds: ['warbond16', 'warbond1', 'warbond10'],
  },
  {
    locked: true,
    displayName: 'Child of Helghan',
    stratagems: [22, 61, 77, 62],
    primary: 5,
    secondary: 7,
    throwable: 0,
    armorPassive: 1,
    warbonds: ['warbond7', 'warbond18'],
  },
  {
    locked: true,
    displayName: 'The Overwatch',
    stratagems: [35, 6, 73, 49],
    primary: 1,
    secondary: 14,
    throwable: 6,
    armorPassive: 4,
    warbonds: ['warbond12', 'warbond6'],
  },
  {
    locked: true,
    displayName: 'The Heavy Gunner',
    stratagems: [6, 72, 57, 30],
    primary: 4,
    secondary: 7,
    throwable: 1,
    armorPassive: 13,
    warbonds: ['warbond6', 'warbond7', 'warbond12'],
  },
  {
    locked: true,
    displayName: 'The Autocannoneer',
    stratagems: [21, 69, 42, 58],
    primary: 44,
    secondary: 0,
    throwable: 7,
    armorPassive: 6,
    warbonds: ['warbond7', 'warbond14'],
  },
  {
    locked: true,
    displayName: 'The Lightshow',
    stratagems: [3, 56, 29, 68],
    primary: 33,
    secondary: 16,
    throwable: 11,
    armorPassive: 12,
    warbonds: ['warbond17', 'warbond5', 'warbond15', 'warbond11'],
  },
  {
    locked: true,
    displayName: 'The Stormcaller',
    stratagems: [7, 31, 62, 52],
    primary: 38,
    secondary: 0,
    throwable: 14,
    armorPassive: 3,
    warbonds: ['warbond16', 'warbond17', 'warbond5'],
  },
  {
    locked: true,
    displayName: 'The Bullet Whisperer',
    stratagems: [4, 57, 66, 65],
    primary: 43,
    secondary: 7,
    throwable: 1,
    armorPassive: 13,
    warbonds: ['warbond17', 'warbond12', 'warbond7'],
  },
  {
    locked: true,
    displayName: 'The Mad Scientist',
    stratagems: [13, 34, 56, 62],
    primary: 37,
    secondary: 12,
    throwable: 14,
    armorPassive: 18,
    warbonds: ['warbond17', 'warbond5', 'warbond11', 'warbond15'],
  },
  {
    locked: true,
    displayName: 'The Problem Child',
    stratagems: [23, 61, 63, 78],
    primary: 38,
    secondary: 19,
    throwable: 14,
    armorPassive: 14,
    warbonds: ['warbond5', 'warbond13', 'warbond17'],
  },
  {
    locked: true,
    displayName: 'The Lone Penant',
    stratagems: [18, 52, 53, 47],
    primary: 32,
    secondary: 1,
    throwable: 8,
    armorPassive: 14,
    warbonds: ['warbond15', 'warbond1', 'warbond8', 'warbond13'],
  },
  {
    locked: true,
    displayName: 'The Wall',
    stratagems: [72, 73, 74, 36],
    primary: 13,
    secondary: 12,
    throwable: 13,
    armorPassive: 5,
    warbonds: ['warbond12', 'warbond7', 'warbond11', 'warbond16'],
  },
  {
    locked: true,
    displayName: 'The Masochist',
    stratagems: [11, 34, 78, 54],
    primary: 39,
    secondary: 18,
    throwable: 7,
    armorPassive: 18,
    warbonds: ['warbond17', 'warbond13', 'warbond9'],
  },
  {
    locked: true,
    displayName: 'The Preacher',
    stratagems: [47, 44, 33, 1],
    primary: 29,
    secondary: 8,
    throwable: 13,
    armorPassive: 15,
    warbonds: ['warbond14', 'warbond4', 'warbond16'],
  },
  {
    locked: true,
    displayName: 'The Shotgun Surgeon',
    stratagems: [54, 48, 32, 60],
    primary: 19,
    secondary: 13,
    throwable: 1,
    armorPassive: 12,
    warbonds: ['warbond8', 'warbond11'],
  },
  {
    locked: true,
    displayName: 'The Helghast Sniper',
    stratagems: [51, 53, 17, 64],
    primary: 40,
    secondary: 6,
    throwable: 3,
    armorPassive: 1,
    warbonds: ['warbond18'],
  },
  {
    locked: true,
    displayName: 'The Supplier',
    stratagems: [35, 14, 16, 7],
    primary: 34,
    secondary: 11,
    throwable: 11,
    armorPassive: 8,
    warbonds: ['warbond10', 'warbond15', 'warbond20'],
  },
  {
    locked: true,
    displayName: 'Selenestica',
    stratagems: [5, 40, 60, 51],
    primary: 41,
    secondary: 13,
    throwable: 5,
    armorPassive: 9,
    warbonds: ['warbond6', 'warbond7', 'warbond8', 'warbond5'],
  },
  {
    locked: true,
    displayName: 'Septimus',
    stratagems: [32, 12, 58, 66],
    primary: 33,
    secondary: 19,
    throwable: 1,
    armorPassive: 2,
    warbonds: ['warbond13'],
  },
  {
    locked: true,
    displayName: 'The Sapper',
    stratagems: [76, 77, 78, 75],
    primary: 14,
    secondary: 16,
    throwable: 9,
    armorPassive: 4,
    warbonds: ['warbond5', 'warbond13', 'warbond11'],
  },
  {
    locked: true,
    displayName: 'The Psychopath',
    stratagems: [28, 47, 53, 52],
    primary: 45,
    secondary: 4,
    throwable: 12,
    armorPassive: 9,
    warbonds: ['warbond10', 'warbond12', 'warbond8'],
  },
  {
    locked: true,
    displayName: 'The Courier',
    stratagems: [46, 43, 32, 40],
    primary: 16,
    secondary: 8,
    throwable: 10,
    armorPassive: 15,
    warbonds: ['warbond0', 'warbond4', 'warbond14'],
  },
  {
    locked: true,
    displayName: 'The Helljumper',
    stratagems: [55, 40, 12, 37],
    primary: 8,
    secondary: 10,
    throwable: 1,
    armorPassive: 19,
    warbonds: ['warbond19', 'warbond12'],
  },
  {
    locked: true,
    displayName: 'The Recon Operative',
    stratagems: [44, 41, 32, 10],
    primary: 17,
    secondary: 10,
    throwable: 3,
    armorPassive: 19,
    warbonds: ['warbond19'],
  },
  {
    locked: true,
    displayName: 'The Raider',
    stratagems: [2, 43, 55, 67],
    primary: 9,
    secondary: 3,
    throwable: 15,
    armorPassive: 20,
    warbonds: ['warbond20', 'warbond15', 'warbond12', 'warbond1'],
  },
  {
    locked: true,
    displayName: 'The Sardaukar',
    stratagems: [37, 14, 45, 48],
    primary: 33,
    secondary: 2,
    throwable: 5,
    armorPassive: 20,
    warbonds: ['warbond20', 'warbond15', 'warbond14', 'warbond5'],
  },
  {
    locked: true,
    displayName: 'The Expendable',
    stratagems: [14, 16, 15, 39, 17],
    primary: 22,
    secondary: 17,
    throwable: 4,
    armorPassive: 14,
    warbonds: ['warbond13', 'warbond20', 'warbond14', 'warbond4'],
  },
  {
    locked: true,
    displayName: 'The Python Commando',
    stratagems: [20, 56, 66, 46],
    primary: 10,
    secondary: 3,
    throwable: 0,
    armorPassive: 21,
    warbonds: ['warbond21'],
  },
  {
    locked: true,
    displayName: 'The Intercessor',
    stratagems: [32, 19, 64, 50],
    primary: 15,
    secondary: 7,
    throwable: 3,
    armorPassive: 9,
    warbonds: ['warbond21', 'warbond18', 'warbond7', 'warbond8'],
  },
  {
    locked: true,
    displayName: 'The Doom Guy',
    stratagems: [34, 4, 65, 42],
    primary: 18,
    secondary: 3,
    throwable: 1,
    armorPassive: 21,
    warbonds: ['warbond21', 'warbond1', 'warbond20', 'warbond17'],
  },
  {
    locked: true,
    displayName: 'Field Artillery',
    stratagems: [63, 64, 60, 23],
    primary: 24,
    secondary: 7,
    throwable: 9,
    armorPassive: 4,
    warbonds: ['warbond7', 'warbond13'],
  },
  {
    locked: true,
    displayName: 'The Assassin',
    stratagems: [34, 55, 48, 76],
    primary: 31,
    secondary: 2,
    throwable: 17,
    armorPassive: 22,
    warbonds: ['warbond22', 'warbond15', 'warbond17', 'warbond1'],
  },
  {
    locked: true,
    displayName: 'The Saboteur',
    stratagems: [26, 39, 75, 56],
    primary: 11,
    secondary: 15,
    throwable: 10,
    armorPassive: 22,
    warbonds: ['warbond22', 'warbond13', 'warbond14'],
  },

  // {
  //   locked: true,
  //   displayName: "The Truth Enforcer",
  //   stratagems: [
  //     "Eagle Napalm Strike",
  //     "Gatling Sentry",
  //     "Orbital 380mm Barrage",
  //     "Orbital Napalm Barrage",
  //   ],
  //   primary: "Halt",
  //   secondary: 12,
  //   throwable: 9,
  //   armorPassive: "Unflinching",
  //   warbonds: ["warbond7", "warbond13"],
  // },

  // {
  //   locked: true,
  //   displayName: "The Devil Dog",
  //   stratagems: [
  //     "Heavy Flamer",
  //     "Mortar Sentry",
  //     "Grenadier Battlement",
  //     "TD-220 Bastion",
  //   ],
  //   primary: "trench shotgun",
  //   secondary: "trench pistol",
  //   throwable: 12,
  //   armorPassive: "trench armor",
  //   warbonds: ["warbond22", "warbond13", "warbond14"],
  // },

  // {
  //   locked: true,
  //   displayName: "The Mechanic",
  //   stratagems: [
  //     "Fast Recon Vehicle",
  //     "Patriot Exosuit",
  //     "TD-220 Bastion",
  //     "Supply Pack",
  //   ],
  //   primary: "fire SMG",
  //   secondary: 14,
  //   throwable: "energy shield grenade",
  //   armorPassive: Engineering Kit",
  //   warbonds: ["warbond22", "warbond13", "warbond14"],
  // },

  // {
  //   locked: true,
  //   displayName: "The Protector",
  //   stratagems: [
  //     "Shield Generator Relay",
  //     "Directional Shield",
  //     "Grenadier Battlement",
  //     "De-Escalator",
  //   ],
  //   primary: "Trident",
  //   secondary: 11,
  //   throwable: "energy shield grenade",
  //   armorPassive: "Med-Kit",
  //   warbonds: ["warbond22", "warbond13", "warbond14"],
  // },

  // {
  //   locked: true,
  //   displayName: "The Counter Sniper",
  //   stratagems: [
  //     "Spear",
  //     "Solo Silo",
  //     "Rocket Sentry",
  //     "Anti-Tank Emplacement",
  //   ],
  //   primary: "Diligence Counter Sniper",
  //   secondary: 10,
  //   throwable: "energy shield grenade",
  //   armorPassive: "Scout",
  //   warbonds: ["warbond22", "warbond13", "warbond14"],
  // },

  // {
  //   locked: true,
  //   displayName: "The Grenadier",
  //   stratagems: [
  //     "belt fed grenade launcher",
  //     "Grenadier Battlement",
  //     "Eagle Cluster Bomb",
  //     "Orbital Gatling Barrage",
  //   ],
  //   primary: "One Two",
  //   secondary: 14,
  //   throwable: 2,
  //   armorPassive: "Integrated Explosives",
  //   warbonds: ["warbond22", "warbond13", "warbond14"],
  // },

  // heavy flamer
  // trench pistol
  // trench shotgun
  // trench armor
  // energy shield grenade
  // fire SMG
  // TD-220 Bastion
  // sledgehammer
  // Trident
  // belt fed grenade launcher

  // UNUSED ITEMS:
  // scorcher
  // purifier
  //
];
