const SPECIALISTS = [
  {
    displayName: 'The Zealous Martyr',
    starterItems: ['Portable Hellbomb', 'Combat Hatchet', 'Integrated Explosives armor'],
    stratagems: ['Portable Hellbomb'],
    primaries: [],
    boosters: [],
    secondaries: ['Combat Hatchet'],
    throwables: [],
    armorPassives: ['Integrated Explosives'],
    traits: [],
    imageURL: 'zealousMartyr.png',
    warbonds: ['warbond1', 'warbond13'],
  },
  {
    displayName: 'The Permacura Rep',
    starterItems: ['Stim Pistol', 'Med-Kit armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ['Stim Pistol'],
    throwables: [],
    armorPassives: ['Med-Kit'],
    traits: [],
    imageURL: 'permacuraRep.png',
    warbonds: ['warbond10'],
  },
  {
    displayName: 'The Flag Bearer',
    starterItems: ['One True Flag', 'Reinforced Epaulettes armor', 'Stamina Enhancement booster'],
    stratagems: ['One True Flag'],
    primaries: [],
    boosters: ['Stamina Enhancement'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Reinforced Epaulettes'],
    traits: [],
    imageURL: 'theFlagBearer.png',
    warbonds: ['warbond15'],
  },
  {
    displayName: 'The Speedrunner',
    starterItems: ['Fast Recon Vehicle', 'Expert Extraction Pilot booster or Dead Sprint booster'],
    stratagems: ['Fast Recon Vehicle'],
    primaries: [],
    boosters: ['Expert Extraction Pilot', 'Dead Sprint'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Oxygenator'],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Viper Commando',
    starterItems: ['Liberator Carbine', 'Peak Physique armor', 'Throwing Knives'],
    stratagems: [],
    primaries: ['Liberator Carbine'],
    boosters: [],
    secondaries: [],
    throwables: ['K-2 Throwing Knife'],
    armorPassives: ['Peak Physique'],
    traits: [],
    imageURL: 'viperCommando.png',
    warbonds: ['warbond8'],
  },
  {
    displayName: 'The Pyromaniac',
    starterItems: ['Torcher', 'Crisper', 'Inflammable armor'],
    stratagems: [],
    primaries: ['Torcher'],
    boosters: [],
    secondaries: ['Crisper'],
    throwables: [],
    armorPassives: ['Inflammable'],
    traits: [],
    imageURL: 'pyromaniac.webp',
    warbonds: ['warbond9'],
  },
  {
    displayName: 'The Lightning Bug',
    starterItems: ['Arc Thrower', 'Tesla Tower', 'Electrical Conduit armor'],
    stratagems: ['Arc Thrower', 'Tesla Tower'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Electrical Conduit'],
    traits: [],
    imageURL: 'lightningBug.webp',
    warbonds: ['warbond5'],
  },
  {
    displayName: 'The Scout Sniper',
    starterItems: ['Diligence', 'UAV Recon booster', 'Scout armor'],
    stratagems: [],
    primaries: ['Diligence'],
    boosters: ['UAV Recon'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Scout'],
    traits: [],
    imageURL: 'scoutSniper.webp',
    warbonds: [],
  },
  {
    displayName: 'The Truth Enforcer',
    starterItems: ['Reprimand or Halt', 'Unflinching armor'],
    stratagems: [],
    primaries: ['Reprimand', 'Halt'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Unflinching'],
    traits: [],
    imageURL: 'truthEnforcer.webp',
    warbonds: ['warbond11'],
  },
  {
    displayName: 'The Exterminator',
    starterItems: ['Gas grenades', 'Sterilizer', 'Advanced Filtration armor'],
    stratagems: ['Sterilizer'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-4 Gas'],
    armorPassives: ['Advanced Filtration'],
    traits: [],
    imageURL: 'exterminator.webp',
    warbonds: ['warbond10'],
  },
  {
    displayName: 'The Assault Trooper',
    starterItems: [
      'StA-52 Assault Rifle, PLAS-39 Accelerator Rifle, or StA-11 SMG',
      'Acclimated armor',
    ],
    stratagems: [],
    primaries: ['StA-52 Assault Rifle', 'PLAS-39 Accelerator Rifle', 'StA-11 SMG'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Acclimated'],
    traits: [],
    imageURL: 'assaultTrooper.webp',
    warbonds: ['warbond18'],
  },
  {
    displayName: 'The Loot Goblin',
    starterItems: ['Supply Pack', 'Sample Scanner booster'],
    stratagems: ['Supply Pack'],
    primaries: [],
    boosters: ['Sample Scanner'],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: 'lootGoblin.webp',
    warbonds: ['warbond15'],
  },
  {
    displayName: 'The Escape Artist',
    starterItems: ['Jump Pack', 'Smoke Grenades'],
    stratagems: ['Jump Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-3 Smoke'],
    armorPassives: [],
    traits: [],
    imageURL: 'escapeArtist.webp',
    warbonds: [],
  },
  {
    displayName: 'The Arbiter',
    starterItems: ['P-92 Warrant', 'Ballistic Shield', 'Ballistic Padding armor'],
    stratagems: ['Ballistic Shield'],
    primaries: [],
    boosters: [],
    secondaries: ['P-92 Warrant'],
    throwables: [],
    armorPassives: ['Ballistic Padding'],
    traits: [],
    imageURL: 'arbiter.webp',
    warbonds: ['warbond1', 'warbond16'],
  },
  {
    displayName: 'Test Subject #4311',
    starterItems: ['Warp Pack', 'Adreno-Defibrillator armor'],
    stratagems: ['Warp Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Adreno-Defibrillator'],
    traits: [],
    imageURL: 'testSubject4311.png',
    warbonds: ['warbond17'],
  },
  {
    displayName: 'The Urban Soldier',
    starterItems: ['Defender', 'Siege Ready armor'],
    stratagems: [],
    primaries: ['Defender'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Siege Ready'],
    traits: [],
    imageURL: 'urbanSoldier.webp',
    warbonds: ['warbond12'],
  },
  {
    displayName: 'The Preacher',
    starterItems: ['Senator or Talon', 'Gunslinger armor'],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ['Senator', 'Talon'],
    throwables: [],
    armorPassives: ['Gunslinger'],
    traits: ['You cannot roll support weapons'],
    imageURL: 'preacher.webp',
    warbonds: ['warbond14'],
  },
  {
    displayName: 'The Hellpod Enthusiast',
    starterItems: ['Expendable Anti-Tank', 'Firebomb Hellpods booster'],
    stratagems: ['Expendable Anti-Tank'],
    primaries: [],
    boosters: ['Firebomb Hellpods', 'Stun Pods', 'Concealed Insertion'],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['You cannot roll Eagle or Orbital stratagems'],
    imageURL: 'hellpodEnthusiast.webp',
    warbonds: ['warbond9'],
  },
  {
    displayName: 'The ODST',
    starterItems: ['MA5C Assault Rifle', 'M7S SMG', 'or M90A Shotgun', 'Feet First armor'],
    stratagems: [],
    primaries: ['MA5C Assault Rifle', 'M7S SMG', 'M90A Shotgun'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Feet First'],
    traits: [],
    imageURL: 'theOdst.webp',
    warbonds: ['warbond19'],
  },
  {
    displayName: 'The Sardaukar',
    starterItems: ['Shield Generator Pack', 'Desert Stormer armor', 'Machete or Saber'],
    stratagems: ['Shield Generator Pack'],
    primaries: [],
    boosters: [],
    secondaries: ['Machete', 'Saber'],
    throwables: [],
    armorPassives: ['Desert Stormer'],
    traits: [],
    imageURL: 'sardaukar.webp',
    warbonds: ['warbond20', 'warbond15'],
  },
  {
    displayName: 'The Python Commando',
    starterItems: ['Rock Solid armor', 'Maxigun'],
    stratagems: ['Maxigun'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Rock Solid'],
    traits: [],
    imageURL: 'pythoncommando.webp',
    warbonds: ['warbond21'],
  },
  {
    displayName: 'The Doom Guy',
    starterItems: ['Rock Solid armor', 'Double Freedom'],
    stratagems: [],
    primaries: ['Double Freedom'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Rock Solid'],
    traits: [],
    imageURL: 'doomguy.webp',
    warbonds: ['warbond21', 'warbond1'],
  },
  {
    displayName: 'The K9 Handler',
    starterItems: [
      'Guard Dog Bullets',
      'Guard Dog Laser',
      'Guard Dog Breath',
      'Guard Dog Arc',
      'and/or Guard Dog Flames',
    ],
    stratagems: [
      'Guard Dog Bullets',
      'Guard Dog Laser',
      'Guard Dog Breath',
      'Guard Dog Arc',
      'Guard Dog Flames',
    ],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['You cannot roll stratagems'],
    imageURL: 'k9handler.webp',
    warbonds: ['warbond21', 'warbond10', 'warbond16'],
  },
  {
    displayName: 'The Saboteur',
    starterItems: ['C4 Pack', 'Reduced Signature armor', 'Concealed Insertion booster'],
    stratagems: ['C4 Pack'],
    primaries: [],
    boosters: ['Concealed Insertion'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Reduced Signature'],
    traits: [],
    imageURL: 'saboteur.webp',
    warbonds: ['warbond22'],
  },
  {
    displayName: 'The Assassin',
    starterItems: ['Censor or Suppressor', 'Reduced Signature armor'],
    stratagems: [],
    primaries: ['Censor', 'Suppressor'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Reduced Signature'],
    traits: [],
    imageURL: 'assassin.webp',
    warbonds: ['warbond22'],
  },
  {
    displayName: 'The Siege Breaker',
    starterItems: ['Leveller', 'Supplementary Adrenaline armor'],
    stratagems: ['Leveller'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Supplementary Adrenaline'],
    traits: [],
    imageURL: 'siegebreaker.png',
    warbonds: ['warbond23'],
  },
  {
    displayName: 'The Juggernaut',
    starterItems: ['Breaching Hammer', 'Shield Generator Pack', 'Supplementary Adrenaline armor'],
    stratagems: ['Breaching Hammer', 'Shield Generator Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Supplementary Adrenaline'],
    traits: [],
    imageURL: 'juggernaut.png',
    warbonds: ['warbond23'],
  },
  {
    displayName: 'The Kriegsman',
    starterItems: ['Entrenchment Tool', 'Concussive Padding armor', 'Orbital Gas Strike'],
    stratagems: ['Orbital Gas Strike'],
    primaries: [],
    boosters: [],
    secondaries: ['Entrenchment Tool'],
    throwables: [],
    armorPassives: ['Concussive Padding'],
    traits: [],
    imageURL: '',
    warbonds: ['warbond24'],
  },
  {
    displayName: 'The Commandant',
    starterItems: ['Veto', 'Concussive Padding armor', 'Orbital Railcannon Strike'],
    stratagems: ['Orbital Railcannon Strike'],
    primaries: [],
    boosters: [],
    secondaries: ['Veto'],
    throwables: [],
    armorPassives: ['Concussive Padding'],
    traits: [],
    imageURL: '',
    warbonds: ['warbond24'],
  },
  {
    displayName: 'The Assault Marine',
    starterItems: ['Jump Pack', 'Defoliation Tool and/or Breaching Hammer'],
    stratagems: ['Jump Pack', 'Defoliation Tool', 'Breaching Hammer'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: ['warbond23', 'warbond21'],
  },
  {
    displayName: 'Eagle Ground Coordinator',
    starterItems: ['Servo-Assisted armor', 'Eagle Strafing Run'],
    stratagems: ['Eagle Strafing Run'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Servo-Assisted'],
    traits: ['Can only roll Eagle stratagems'],
    imageURL: 'egc.webp',
    warbonds: [],
  },
  {
    displayName: 'Orbital Bombardment Ground Coordinator',
    starterItems: ['Servo-Assisted armor', 'Orbital Precision Strike'],
    stratagems: ['Orbital Precision Strike'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Servo-Assisted'],
    traits: ['Can only roll Orbital stratagems'],
    imageURL: 'ogc.webp',
    warbonds: [],
  },
  {
    displayName: 'The Minesweeper',
    starterItems: ['Lure Mines', 'Anti-Personnel Mines'],
    stratagems: ['Anti-Personnel Mines'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['TM-01 Lure Mine'],
    armorPassives: [],
    traits: ['Can only roll mine stratagems'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Combat Engineer',
    starterItems: ['Pummeler', 'Machine Gun Sentry', 'Engineering Kit armor'],
    stratagems: ['Machine Gun Sentry'],
    primaries: ['Pummeler'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Engineering Kit'],
    traits: ['Can only roll sentry stratagems'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Law Enforcer',
    starterItems: ['De-Escalator', 'Ballistic Padding armor', 'Stun Pods'],
    stratagems: ['De-Escalator'],
    primaries: [],
    boosters: ['Stun Pods'],
    secondaries: [],
    throwables: [],
    armorPassives: ['Ballistic Padding'],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Beamer',
    starterItems: ['Scythe', 'Guard Dog Laser'],
    stratagems: ['Guard Dog Laser'],
    primaries: ['Scythe'],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'L.A.N.C.E.',
    starterItems: ['Anti-Material Rifle', 'Hover Pack'],
    stratagems: ['Hover Pack', 'Anti-Material Rifle'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Turtle',
    starterItems: ['Shield Generator Pack', 'G/SH-39 Shield'],
    stratagems: ['Shield Generator Pack'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G/SH-39 Shield'],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Pilot',
    starterItems: ['Breakthrough Exosuit', 'Oxygenator armor'],
    stratagems: ['Breakthrough Exosuit'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ['Oxygenator'],
    traits: ['Can only roll vehicle, exosuit, and eagle stratagems'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Hazard',
    starterItems: ['Airburst Rocket Launcher', 'G-7 Pineapple'],
    stratagems: ['Airburst Rocket Launcher'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-7 Pineapple'],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Tank Hunter',
    starterItems: ['Anti-Tank Emplacement', 'G-123 Thermite'],
    stratagems: ['Anti-Tank Emplacement'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ['G-123 Thermite'],
    armorPassives: [],
    traits: ['Can only roll anti-tank stratagems'],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Fisherman',
    starterItems: ['Speargun'],
    stratagems: ['Speargun'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Spartan',
    starterItems: ['Ballistic Shield', 'Peak Physique armor', 'Melee weapon secondaries'],
    stratagems: ['Ballistic Shield'],
    primaries: [],
    boosters: [],
    secondaries: ['Stun Lance', 'Stun Baton', 'Machete', 'Saber', 'Combat Hatchet'],
    throwables: [],
    armorPassives: ['Peak Physique'],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Arnold',
    starterItems: ['Commando', 'Dynamite', 'Verdict'],
    stratagems: ['Commando'],
    primaries: [],
    boosters: [],
    secondaries: ['Verdict'],
    throwables: ['Dynamite'],
    armorPassives: [],
    traits: [],
    imageURL: '',
    warbonds: [],
  },
  {
    displayName: 'The Expendable',
    starterItems: ['Bullet Storm'],
    stratagems: ['Bullet Storm'],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ['Can only roll expendable stratagems'],
    imageURL: '',
    warbonds: [],
  },
];
