const ybwamahe = "You begin with, and must always have equipped, ";
const SPECIALISTS = [
  {
    displayName: "The Zealous Martyr",
    starterItems: [
      "Portable Hellbomb",
      "Combat Hatchet",
      "Integrated Explosives armor",
    ],
    stratagems: ["Portable Hellbomb"],
    primaries: [],
    boosters: [],
    secondaries: ["Combat Hatchet"],
    throwables: [],
    armorPassives: ["Integrated Explosives"],
    traits: [],
    warbonds: ["warbond1", "warbond13"],
  },
  {
    displayName: "The Permacura Rep",
    starterItems: ["Stim Pistol", "Med-Kit armor"],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ["Stim Pistol"],
    throwables: [],
    armorPassives: ["Med-Kit"],
    traits: [],
    warbonds: ["warbond10"],
  },
  {
    displayName: "The Flag Bearer",
    starterItems: [
      "One True Flag",
      "Reinforced Epaulettes armor",
      "Stamina Enhancement booster",
    ],
    stratagems: ["One True Flag"],
    primaries: [],
    boosters: ["Stamina Enhancement"],
    secondaries: [],
    throwables: [],
    armorPassives: ["Reinforced Epaulettes"],
    traits: [],
    warbonds: ["warbond15"],
  },
  {
    displayName: "The Speedrunner",
    starterItems: [
      "Fast Recon Vehicle",
      "Expert Extraction Pilot booster or Dead Sprint booster",
    ],
    stratagems: ["Fast Recon Vehicle"],
    primaries: [],
    boosters: ["Expert Extraction Pilot", "Dead Sprint"],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    warbonds: ["warbond6", "warbond11"],
  },
  {
    displayName: "The Viper Commando",
    starterItems: [
      "Liberator Carbine",
      "Peak Physique armor",
      "Throwing Knives",
    ],
    stratagems: [],
    primaries: ["Liberator Carbine"],
    boosters: [],
    secondaries: [],
    throwables: ["K-2 Throwing Knife"],
    armorPassives: ["Peak Physique"],
    traits: [],
    warbonds: ["warbond8"],
  },
  {
    displayName: "The Pyromaniac",
    starterItems: ["Torcher", "Crisper", "Inflammable armor"],
    stratagems: [],
    primaries: ["Torcher"],
    boosters: [],
    secondaries: ["Crisper"],
    throwables: [],
    armorPassives: ["Inflammable"],
    traits: [],
    warbonds: ["warbond9"],
  },
  {
    displayName: "The Lightning Bug",
    starterItems: ["Arc Thrower", "Tesla Tower", "Electrical Conduit armor"],
    stratagems: ["Arc Thrower", "Tesla Tower"],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ["Electrical Conduit"],
    traits: [],
    warbonds: ["warbond5"],
  },
  {
    displayName: "The Scout Sniper",
    starterItems: ["Diligence", "UAV Recon booster", "Scout armor"],
    stratagems: [],
    primaries: ["Diligence"],
    boosters: ["UAV Recon"],
    secondaries: [],
    throwables: [],
    armorPassives: ["Scout"],
    traits: [],
    warbonds: [],
  },
  {
    displayName: "The Truth Enforcer",
    starterItems: ["Reprimand or Halt", "Unflinching armor"],
    stratagems: [],
    primaries: ["Reprimand", "Halt"],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ["Unflinching"],
    traits: [],
    warbonds: ["warbond11"],
  },
  {
    displayName: "The Exterminator",
    starterItems: ["Gas grenades", "Sterilizer", "Advanced Filtration armor"],
    stratagems: ["Sterilizer"],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ["G-4 Gas"],
    armorPassives: ["Advanced Filtration"],
    traits: [],
    warbonds: ["warbond10"],
  },
  {
    displayName: "The Assault Trooper",
    starterItems: [
      "StA-52 Assault Rifle, PLAS-39 Accelerator Rifle, or StA-11 SMG",
      "Acclimated armor",
    ],
    stratagems: [],
    primaries: [
      "StA-52 Assault Rifle",
      "PLAS-39 Accelerator Rifle",
      "StA-11 SMG",
    ],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ["Acclimated"],
    traits: [],
    warbonds: [],
  },
  {
    displayName: "The Loot Goblin",
    starterItems: ["Supply Pack", "Sample Scanner booster"],
    stratagems: ["Supply Pack"],
    primaries: [],
    boosters: ["Sample Scanner"],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: [],
    warbonds: ["warbond15"],
  },
  {
    displayName: "The Escape Artist",
    starterItems: ["Jump Pack", "Smoke Grenades"],
    stratagems: ["Jump Pack"],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: ["G-3 Smoke"],
    armorPassives: [],
    traits: [],
    warbonds: [],
  },
  {
    displayName: "The Arbiter",
    starterItems: [
      "P-92 Warrant",
      "Ballistic Shield",
      "Ballistic Padding armor",
    ],
    stratagems: ["Ballistic Shield"],
    primaries: [],
    boosters: [],
    secondaries: ["P-92 Warrant"],
    throwables: [],
    armorPassives: ["Ballistic Padding"],
    traits: [],
    warbonds: ["warbond1", "warbond16"],
  },
  {
    displayName: "Test Subject #4311",
    starterItems: ["Warp Pack", "Adreno-Defibrillator armor"],
    stratagems: ["Warp Pack"],
    primaries: [],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ["Adreno-Defibrillator"],
    traits: [],
    warbonds: ["warbond17"],
  },
  {
    displayName: "The Urban Soldier",
    starterItems: ["Defender", "Siege Ready armor"],
    stratagems: [],
    primaries: ["Defender"],
    boosters: [],
    secondaries: [],
    throwables: [],
    armorPassives: ["Siege Ready"],
    traits: [],
    warbonds: ["warbond12"],
  },
  {
    displayName: "The Preacher",
    starterItems: ["Senator or Talon", "Gunslinger armor"],
    stratagems: [],
    primaries: [],
    boosters: [],
    secondaries: ["Senator", "Talon"],
    throwables: [],
    armorPassives: ["Gunslinger"],
    traits: ["You cannot roll support weapons"],
    warbonds: ["warbond14"],
  },
  {
    displayName: "The Hellpod Enthusiast",
    starterItems: ["Expendable Anti-Tank", "Firebomb Hellpods booster"],
    stratagems: ["Expendable Anti-Tank"],
    primaries: [],
    boosters: ["Firebomb Hellpods"],
    secondaries: [],
    throwables: [],
    armorPassives: [],
    traits: ["You cannot roll Eagle or Orbital stratagems"],
    warbonds: ["warbond9"],
  },
  // {
  //   displayName: 'The O.G.',
  //   starterItems: ['Liberator'],
  //   stratagems: [],
  //   primaries: ['Liberator'],
  //   boosters: [],
  //   secondaries: [],
  //   throwables: [],
  //   armorPassives: ['Extra Padding'],
  //   traits: [
  //     'Chance of rolling high-tier items is increased',
  //   ],
  // },
];
