const STRATAGEMS = [
  {
    displayName: 'Sterilizer',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond10',
    internalName: 'tx41sterilizer',
    imageURL: 'tx41sterilizer.svg',
    antitank: false,
    tier: 'c',
    index: 0,
  },
  {
    displayName: 'Flamethrower',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'flam40flamethrower',
    imageURL: 'flam40flamethrower.svg',
    antitank: false,
    tier: 'b',
    index: 1,
  },
  {
    displayName: 'Speargun',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond20',
    internalName: 'speargun',
    imageURL: 'speargun.svg',
    antitank: false,
    tier: 'a',
    index: 2,
  },
  {
    displayName: 'Laser Cannon',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'las98lasercannon',
    imageURL: 'las98lasercannon.svg',
    antitank: true,
    tier: 'b',
    index: 3,
  },
  {
    displayName: 'Stalwart',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'm105stalwart',
    imageURL: 'm105stalwart.svg',
    antitank: false,
    tier: 'b',
    index: 4,
  },
  {
    displayName: 'Machine Gun',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'mg43machinegun',
    imageURL: 'mg43machinegun.svg',
    antitank: false,
    tier: 'b',
    index: 5,
  },
  {
    displayName: 'Heavy Machine Gun',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'mg206heavymachinegun',
    imageURL: 'mg206heavymachinegun.svg',
    antitank: true,
    tier: 'b',
    index: 6,
  },
  {
    displayName: 'Arc Thrower',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'arc3arcthrower',
    imageURL: 'arc3arcthrower.svg',
    antitank: false,
    tier: 'b',
    index: 7,
  },
  {
    displayName: 'Grenade Launcher',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'gl21grenadelauncher',
    imageURL: 'gl21grenadelauncher.svg',
    antitank: false,
    tier: 'b',
    index: 8,
  },
  {
    displayName: 'De-Escalator',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond16',
    internalName: 'gl52deescalator',
    imageURL: 'gl52deescalator.svg',
    antitank: true,
    tier: 'a',
    index: 9,
  },
  {
    displayName: 'Anti-Material Rifle',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'apw1antimaterielrifle',
    imageURL: 'apw1antimaterielrifle.svg',
    antitank: true,
    tier: 'a',
    index: 10,
  },
  {
    displayName: 'Railgun',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'rs422railgun',
    imageURL: 'rs422railgun.svg',
    antitank: true,
    tier: 'b',
    index: 11,
  },
  {
    displayName: 'Quasar Cannon',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'las99quasarcannon',
    imageURL: 'las99quasarcannon.svg',
    antitank: true,
    tier: 's',
    index: 12,
  },
  {
    displayName: 'Epoch',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond17',
    internalName: 'epoch',
    imageURL: 'epoch.svg',
    antitank: true,
    tier: 'a',
    index: 13,
  },
  {
    displayName: 'Expendable Anti-Tank',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'eat17expendableantitank',
    imageURL: 'eat17expendableantitank.svg',
    antitank: true,
    tier: 'a',
    index: 14,
  },
  {
    displayName: 'Commando',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'none',
    internalName: 'mls4xcommandorocketlauncher',
    imageURL: 'mls4xcommandorocketlauncher.svg',
    antitank: true,
    tier: 'a',
    index: 15,
  },
  {
    displayName: 'Expendable Napalm',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond20',
    internalName: 'eat700expendablenapalm',
    imageURL: 'eat700expendablenapalm.svg',
    antitank: false,
    tier: 'b',
    index: 16,
  },
  {
    displayName: 'Solo Silo',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond20',
    internalName: 'solosilo',
    imageURL: 'solosilo.svg',
    antitank: true,
    tier: 'a',
    index: 17,
  },
  {
    displayName: 'One True Flag',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond15',
    internalName: 'onetrueflag',
    imageURL: 'onetrueflag.svg',
    antitank: false,
    tier: 'c',
    index: 18,
  },
  {
    displayName: 'Defoliation Tool',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons'],
    warbondCode: 'warbond21',
    internalName: 'defoliationtool',
    imageURL: 'defoliationtool.svg',
    antitank: false,
    tier: 'c',
    index: 19,
  },
  {
    displayName: 'Maxigun',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'warbond21',
    internalName: 'maxigun',
    imageURL: 'maxigun.svg',
    antitank: false,
    tier: 'a',
    index: 20,
  },
  {
    displayName: 'Autocannon',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'none',
    internalName: 'ac8autocannon',
    imageURL: 'ac8autocannon.svg',
    antitank: true,
    tier: 'a',
    index: 21,
  },
  {
    displayName: 'W.A.S.P. Launcher',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'none',
    internalName: 'wasplauncher',
    imageURL: 'wasplauncher.svg',
    antitank: true,
    tier: 'a',
    index: 22,
  },
  {
    displayName: 'Airburst Rocket Launcher',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'none',
    internalName: 'rl77airburstrocketlauncher',
    imageURL: 'rl77airburstrocketlauncher.svg',
    antitank: false,
    tier: 'b',
    index: 23,
  },
  {
    displayName: 'Recoilless Rifle',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'none',
    internalName: 'gr8recoillessrifle',
    imageURL: 'gr8recoillessrifle.svg',
    antitank: true,
    tier: 's',
    index: 24,
  },
  {
    displayName: 'Spear',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'none',
    internalName: 'faf14spear',
    imageURL: 'faf14spear.svg',
    antitank: true,
    tier: 'b',
    index: 25,
  },
  {
    displayName: 'C4 Pack',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Weapons', 'Backpacks'],
    warbondCode: 'none',
    internalName: 'c4pack',
    imageURL: 'c4pack.svg',
    antitank: true,
    tier: 'b',
    index: 26,
  },
  {
    displayName: 'Guard Dog Flames',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond21',
    internalName: 'guarddogflames',
    imageURL: 'guarddogflames.svg',
    antitank: false,
    tier: 'b',
    index: 27,
  },
  {
    displayName: 'Guard Dog Breath',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond10',
    internalName: 'axtx13guarddogdogbreath',
    imageURL: 'axtx13guarddogdogbreath.svg',
    antitank: false,
    tier: 'a',
    index: 28,
  },
  {
    displayName: 'Guard Dog Laser',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'axlas5guarddogrover',
    imageURL: 'axlas5guarddogrover.svg',
    antitank: false,
    tier: 'b',
    index: 29,
  },
  {
    displayName: 'Guard Dog Bullets',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'ad334guarddog',
    imageURL: 'ad334guarddog.svg',
    antitank: false,
    tier: 'a',
    index: 30,
  },
  {
    displayName: 'Guard Dog Arc',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond16',
    internalName: 'guarddogarc',
    imageURL: 'guarddogarc.svg',
    antitank: false,
    tier: 'a',
    index: 31,
  },
  {
    displayName: 'Jump Pack',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'lift850jumppack',
    imageURL: 'lift850jumppack.svg',
    antitank: false,
    tier: 's',
    index: 32,
  },
  {
    displayName: 'Hover Pack',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond14',
    internalName: 'lift860hoverpack',
    imageURL: 'lift860hoverpack.svg',
    antitank: false,
    tier: 'b',
    index: 33,
  },
  {
    displayName: 'Warp Pack',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond17',
    internalName: 'warppack',
    imageURL: 'warppack.svg',
    antitank: false,
    tier: 's',
    index: 34,
  },
  {
    displayName: 'Supply Pack',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'b1supplypack',
    imageURL: 'b1supplypack.svg',
    antitank: false,
    tier: 's',
    index: 35,
  },
  {
    displayName: 'Directional Shield',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond12',
    internalName: 'sh51directionalshield',
    imageURL: 'sh51directionalshield.svg',
    antitank: false,
    tier: 'c',
    index: 36,
  },
  {
    displayName: 'Shield Generator Pack',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'sh20shieldgeneratorpack',
    imageURL: 'sh20shieldgeneratorpack.svg',
    antitank: false,
    tier: 'a',
    index: 37,
  },
  {
    displayName: 'Ballistic Shield',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'none',
    internalName: 'sh20ballisticshieldbackpack',
    imageURL: 'sh20ballisticshieldbackpack.svg',
    antitank: false,
    tier: 'b',
    index: 38,
  },
  {
    displayName: 'Portable Hellbomb',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Backpacks'],
    warbondCode: 'warbond13',
    internalName: 'portablehellbomb',
    imageURL: 'portablehellbomb.svg',
    antitank: true,
    tier: 'a',
    index: 39,
  },
  {
    displayName: 'Fast Recon Vehicle',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles'],
    warbondCode: 'none',
    internalName: 'fastreconvehicle',
    imageURL: 'fastreconvehicle.svg',
    antitank: false,
    tier: 'a',
    index: 40,
  },
  {
    displayName: 'Patriot Exosuit',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles'],
    warbondCode: 'none',
    internalName: 'exo45patriotexosuit',
    imageURL: 'exo45patriotexosuit.svg',
    antitank: true,
    tier: 's',
    index: 41,
  },
  {
    displayName: 'Emancipator Exosuit',
    type: 'Stratagem',
    category: 'Supply',
    tags: ['Vehicles'],
    warbondCode: 'none',
    internalName: 'exo49emancipatorexosuit',
    imageURL: 'exo49emancipatorexosuit.svg',
    antitank: true,
    tier: 's',
    index: 42,
  },
  {
    displayName: 'Eagle Strafing Run',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eaglestrafingrun',
    imageURL: 'eaglestrafingrun.svg',
    antitank: false,
    tier: 's',
    index: 43,
  },
  {
    displayName: 'Eagle Airstrike',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eagleairstrike',
    imageURL: 'eagleairstrike.svg',
    antitank: true,
    tier: 's',
    index: 44,
  },
  {
    displayName: 'Eagle Cluster Bomb',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eagleclusterbomb',
    imageURL: 'eagleclusterbomb.svg',
    antitank: false,
    tier: 'b',
    index: 45,
  },
  {
    displayName: 'Eagle Napalm Strike',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eaglenapalmstrike',
    imageURL: 'eaglenapalmstrike.svg',
    antitank: false,
    tier: 'b',
    index: 46,
  },
  {
    displayName: 'Eagle Smoke Strike',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eaglesmokestrike',
    imageURL: 'eaglesmokestrike.svg',
    antitank: false,
    tier: 'c',
    index: 47,
  },
  {
    displayName: 'Eagle 110mm Rocket Pods',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eagle110mmrocketpods',
    imageURL: 'eagle110mmrocketpods.svg',
    antitank: true,
    tier: 'b',
    index: 48,
  },
  {
    displayName: 'Eagle 500kg Bomb',
    type: 'Stratagem',
    category: 'Eagle',
    tags: ['Eagle'],
    warbondCode: 'none',
    internalName: 'eagle500kgbomb',
    imageURL: 'eagle500kgbomb.svg',
    antitank: true,
    tier: 's',
    index: 49,
  },
  {
    displayName: 'Orbital Precision Strike',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalprecisionstrike',
    imageURL: 'orbitalprecisionstrike.svg',
    antitank: true,
    tier: 'b',
    index: 50,
  },
  {
    displayName: 'Orbital Gas Strike',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalgasstrike',
    imageURL: 'orbitalgasstrike.svg',
    antitank: false,
    tier: 'a',
    index: 51,
  },
  {
    displayName: 'Orbital EMS Strike',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalemsstrike',
    imageURL: 'orbitalemsstrike.svg',
    antitank: false,
    tier: 'c',
    index: 52,
  },
  {
    displayName: 'Orbital Smoke Strike',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalsmokestrike',
    imageURL: 'orbitalsmokestrike.svg',
    antitank: false,
    tier: 'c',
    index: 53,
  },
  {
    displayName: 'Orbital Airburst Strike',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalairburststrike',
    imageURL: 'orbitalairburststrike.svg',
    antitank: false,
    tier: 'b',
    index: 54,
  },
  {
    displayName: 'Orbital Railcannon Strike',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalrailcannonstrike',
    imageURL: 'orbitalrailcannonstrike.svg',
    antitank: true,
    tier: 'b',
    index: 55,
  },
  {
    displayName: 'Orbital Laser',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitallaser',
    imageURL: 'orbitallaser.svg',
    antitank: true,
    tier: 'a',
    index: 56,
  },
  {
    displayName: 'Orbital Gatling Barrage',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalgatlingbarrage',
    imageURL: 'orbitalgatlingbarrage.svg',
    antitank: false,
    tier: 'b',
    index: 57,
  },
  {
    displayName: 'Orbital 120mm Barrage',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbital120mmhebarrage',
    imageURL: 'orbital120mmhebarrage.svg',
    antitank: true,
    tier: 'a',
    index: 58,
  },
  {
    displayName: 'Orbital 380mm Barrage',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbital380mmhebarrage',
    imageURL: 'orbital380mmhebarrage.svg',
    antitank: true,
    tier: 'a',
    index: 59,
  },
  {
    displayName: 'Orbital Walking Barrage',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalwalkingbarrage',
    imageURL: 'orbitalwalkingbarrage.svg',
    antitank: true,
    tier: 'a',
    index: 60,
  },
  {
    displayName: 'Orbital Napalm Barrage',
    type: 'Stratagem',
    category: 'Orbital',
    tags: ['Orbital'],
    warbondCode: 'none',
    internalName: 'orbitalnapalmbarrage',
    imageURL: 'orbitalnapalmbarrage.svg',
    antitank: false,
    tier: 's',
    index: 61,
  },
  {
    displayName: 'Tesla Tower',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'teslatower',
    imageURL: 'teslatower.svg',
    antitank: false,
    tier: 'b',
    index: 62,
  },
  {
    displayName: 'Mortar Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'mortarsentry',
    imageURL: 'mortarsentry.svg',
    antitank: false,
    tier: 'b',
    index: 63,
  },
  {
    displayName: 'EMS Mortar Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'emsmortarsentry',
    imageURL: 'emsmortarsentry.svg',
    antitank: false,
    tier: 'c',
    index: 64,
  },
  {
    displayName: 'Machine Gun Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'machinegunsentry',
    imageURL: 'machinegunsentry.svg',
    antitank: false,
    tier: 'a',
    index: 65,
  },
  {
    displayName: 'Gatling Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'gatlingsentry',
    imageURL: 'gatlingsentry.svg',
    antitank: false,
    tier: 'a',
    index: 66,
  },
  {
    displayName: 'Flame Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'warbond12',
    internalName: 'aflam40flamesentry',
    imageURL: 'aflam40flamesentry.svg',
    antitank: false,
    tier: 'b',
    index: 67,
  },
  {
    displayName: 'Laser Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'warbond17',
    internalName: 'lasersentry',
    imageURL: 'lasersentry.svg',
    antitank: true,
    tier: 'a',
    index: 68,
  },
  {
    displayName: 'Autocannon Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'autocannonsentry',
    imageURL: 'autocannonsentry.svg',
    antitank: true,
    tier: 'a',
    index: 69,
  },
  {
    displayName: 'Rocket Sentry',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Sentry'],
    warbondCode: 'none',
    internalName: 'rocketsentry',
    imageURL: 'rocketsentry.svg',
    antitank: true,
    tier: 'a',
    index: 70,
  },
  {
    displayName: 'Shield Generator Relay',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'shieldgeneratorrelay',
    imageURL: 'shieldgeneratorrelay.svg',
    antitank: false,
    tier: 'c',
    index: 71,
  },
  {
    displayName: 'HMG Emplacement',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'hmgemplacement',
    imageURL: 'hmgemplacement.svg',
    antitank: true,
    tier: 'a',
    index: 72,
  },
  {
    displayName: 'Anti-Tank Emplacement',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'warbond12',
    internalName: 'eat12antitankemplacement',
    imageURL: 'eat12antitankemplacement.svg',
    antitank: true,
    tier: 's',
    index: 73,
  },
  {
    displayName: 'Grenadier Battlement',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'grenadierbattlement',
    imageURL: 'grenadierbattlement.svg',
    antitank: false,
    tier: 'b',
    index: 74,
  },
  {
    displayName: 'Anti-Tank Mines',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'antitankmines',
    imageURL: 'antitankmines.svg',
    antitank: true,
    tier: 'b',
    index: 75,
  },
  {
    displayName: 'Anti-Personnel Mines',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'antipersonnelminefield',
    imageURL: 'antipersonnelminefield.svg',
    antitank: false,
    tier: 'b',
    index: 76,
  },
  {
    displayName: 'Gas Mines',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'gasmines',
    imageURL: 'gasmines.svg',
    antitank: false,
    tier: 's',
    index: 77,
  },
  {
    displayName: 'Incendiary Mines',
    type: 'Stratagem',
    category: 'Defense',
    tags: ['Emplacement'],
    warbondCode: 'none',
    internalName: 'incendiarymines',
    imageURL: 'incendiarymines.svg',
    antitank: false,
    tier: 'b',
    index: 78,
  },
];

// s: 11
// a: 28
// b: 30
// c: 9
