const STRATAGEMS = [
  {
    displayName: "Sterilizer",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "Chemical Agents",
    warbondCode: "warbond10",
    internalName: "tx41sterilizer",
    imageURL: "tx41sterilizer.svg",
    tier: "c",
  },
  {
    displayName: "Expendable Anti-Tank",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eat17expendableantitank",
    imageURL: "eat17expendableantitank.svg",
    tier: "a",
  },
  {
    displayName: "Flamethrower",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "flam40flamethrower",
    imageURL: "flam40flamethrower.svg",
    tier: "b",
  },
  {
    displayName: "Laser Cannon",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "las98lasercannon",
    imageURL: "las98lasercannon.svg",
    tier: "b",
  },
  {
    displayName: "Stalwart",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "m105stalwart",
    imageURL: "m105stalwart.svg",
    tier: "b",
  },
  {
    displayName: "Machine Gun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "mg43machinegun",
    imageURL: "mg43machinegun.svg",
    tier: "a",
  },
  {
    displayName: "Arc Thrower",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "arc3arcthrower",
    imageURL: "arc3arcthrower.svg",
    tier: "b",
  },
  {
    displayName: "Grenade Launcher",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "gl21grenadelauncher",
    imageURL: "gl21grenadelauncher.svg",
    tier: "b",
  },
  {
    displayName: "Anti-Material Rifle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "apw1antimaterielrifle",
    imageURL: "apw1antimaterielrifle.svg",
    tier: "a",
  },
  {
    displayName: "Railgun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "rs422railgun",
    imageURL: "rs422railgun.svg",
    tier: "b",
  },
  {
    displayName: "Quasar Cannon",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "las99quasarcannon",
    imageURL: "las99quasarcannon.svg",
    tier: "s",
  },
  {
    displayName: "Commando",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "mls4xcommandorocketlauncher",
    imageURL: "mls4xcommandorocketlauncher.svg",
    tier: "a",
  },
  {
    displayName: "Heavy Machine Gun",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "None",
    warbondCode: "none",
    internalName: "mg206heavymachinegun",
    imageURL: "mg206heavymachinegun.svg",
    tier: "b",
  },
  {
    displayName: "One True Flag",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "Masters of Ceremony",
    warbondCode: "warbond15",
    internalName: "onetrueflag",
    imageURL: "onetrueflag.svg",
    tier: "c",
  },
  {
    displayName: "GL-52 De-Escalator",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons"],
    warbond: "Force of Law",
    warbondCode: "warbond16",
    internalName: "gl52deescalator",
    imageURL: "gl52deescalator.svg",
    tier: "a",
  },
  {
    displayName: "Airburst Rocket Launcher",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "rl77airburstrocketlauncher",
    imageURL: "rl77airburstrocketlauncher.svg",
    tier: "b",
  },
  {
    displayName: "Autocannon",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "ac8autocannon",
    imageURL: "ac8autocannon.svg",
    tier: "a",
  },
  {
    displayName: "W.A.S.P. Launcher",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "wasplauncher",
    imageURL: "wasplauncher.svg",
    tier: "a",
  },
  {
    displayName: "Recoilless Rifle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "gr8recoillessrifle",
    imageURL: "gr8recoillessrifle.svg",
    tier: "s",
  },
  {
    displayName: "Spear",
    type: "Stratagem",
    category: "Supply",
    tags: ["Weapons", "Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "faf14spear",
    imageURL: "faf14spear.svg",
    tier: "b",
  },
  {
    displayName: " Guard Dog Breath",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "Chemical Agents",
    warbondCode: "warbond10",
    internalName: "axtx13guarddogdogbreath",
    imageURL: "axtx13guarddogdogbreath.svg",
    tier: "a",
  },
  {
    displayName: "Guard Dog Laser",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "axlas5guarddogrover",
    imageURL: "axlas5guarddogrover.svg",
    tier: "b",
  },
  {
    displayName: "Guard Dog Bullets",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "ad334guarddog",
    imageURL: "ad334guarddog.svg",
    tier: "a",
  },
  {
    displayName: "Guard Dog Arc",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "Force of Law",
    warbondCode: "warbond16",
    internalName: "guarddogarc",
    imageURL: "guarddogarc.svg",
    tier: "a",
  },
  {
    displayName: "Jump Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "lift850jumppack",
    imageURL: "lift850jumppack.svg",
    tier: "s",
  },
  {
    displayName: "Hover Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "Borderline Justice",
    warbondCode: "warbond14",
    internalName: "lift860hoverpack",
    imageURL: "lift860hoverpack.svg",
    tier: "b",
  },
  {
    displayName: "Supply Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "b1supplypack",
    imageURL: "b1supplypack.svg",
    tier: "s",
  },
  {
    displayName: "Directional Shield",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "Urban Legends",
    warbondCode: "warbond12",
    internalName: "sh51directionalshield",
    imageURL: "sh51directionalshield.svg",
    tier: "c",
  },
  {
    displayName: "Shield Generator Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "sh20shieldgeneratorpack",
    imageURL: "sh20shieldgeneratorpack.svg",
    tier: "a",
  },
  {
    displayName: "Ballistic Shield",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "None",
    warbondCode: "none",
    internalName: "sh20ballisticshieldbackpack",
    imageURL: "sh20ballisticshieldbackpack.svg",
    tier: "b",
  },
  {
    displayName: "Portable Hellbomb",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbond: "Servants of Freedom",
    warbondCode: "warbond13",
    internalName: "portablehellbomb",
    imageURL: "portablehellbomb.svg",
    tier: "a",
  },
  {
    displayName: "Fast Recon Vehicle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbond: "None",
    warbondCode: "none",
    internalName: "fastreconvehicle",
    imageURL: "fastreconvehicle.svg",
    tier: "a",
  },
  {
    displayName: "Patriot Exosuit",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbond: "None",
    warbondCode: "none",
    internalName: "exo45patriotexosuit",
    imageURL: "exo45patriotexosuit.svg",
    tier: "s",
  },
  {
    displayName: "Emancipator Exosuit",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbond: "None",
    warbondCode: "none",
    internalName: "exo49emancipatorexosuit",
    imageURL: "exo49emancipatorexosuit.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Strafing Run",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eaglestrafingrun",
    imageURL: "eaglestrafingrun.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Airstrike",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eagleairstrike",
    imageURL: "eagleairstrike.svg",
    tier: "s",
  },
  {
    displayName: "Eagle Cluster Bomb",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eagleclusterbomb",
    imageURL: "eagleclusterbomb.svg",
    tier: "b",
  },
  {
    displayName: "Eagle Napalm Strike",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eaglenapalmstrike",
    imageURL: "eaglenapalmstrike.svg",
    tier: "b",
  },
  {
    displayName: "Eagle Smoke Strike",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eaglesmokestrike",
    imageURL: "eaglesmokestrike.svg",
    tier: "c",
  },
  {
    displayName: "Eagle 110mm Rocket Pods",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eagle110mmrocketpods",
    imageURL: "eagle110mmrocketpods.svg",
    tier: "b",
  },
  {
    displayName: "Eagle 500kg Bomb",
    type: "Stratagem",
    category: "Eagle",
    tags: ["Eagle"],
    warbond: "None",
    warbondCode: "none",
    internalName: "eagle500kgbomb",
    imageURL: "eagle500kgbomb.svg",
    tier: "s",
  },
  {
    displayName: "Orbital Precision Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalprecisionstrike",
    imageURL: "orbitalprecisionstrike.svg",
    tier: "b",
  },
  {
    displayName: "Orbital Napalm Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalnapalmbarrage",
    imageURL: "orbitalnapalmbarrage.svg",
    tier: "s",
  },
  {
    displayName: "Orbital Airburst Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalairburststrike",
    imageURL: "orbitalairburststrike.svg",
    tier: "b",
  },
  {
    displayName: "Orbital 120mm HE Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbital120mmhebarrage",
    imageURL: "orbital120mmhebarrage.svg",
    tier: "a",
  },
  {
    displayName: "Orbital 380mm HE Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbital380mmhebarrage",
    imageURL: "orbital380mmhebarrage.svg",
    tier: "a",
  },
  {
    displayName: "Orbital Walking Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalwalkingbarrage",
    imageURL: "orbitalwalkingbarrage.svg",
    tier: "a",
  },
  {
    displayName: "Orbital Laser",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitallaser",
    imageURL: "orbitallaser.svg",
    tier: "a",
  },
  {
    displayName: "Orbital Railcannon Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalrailcannonstrike",
    imageURL: "orbitalrailcannonstrike.svg",
    tier: "b",
  },
  {
    displayName: "Orbital Gatling Barrage",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalgatlingbarrage",
    imageURL: "orbitalgatlingbarrage.svg",
    tier: "b",
  },
  {
    displayName: "Orbital Gas Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalgasstrike",
    imageURL: "orbitalgasstrike.svg",
    tier: "a",
  },
  {
    displayName: "Orbital EMS Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalemsstrike",
    imageURL: "orbitalemsstrike.svg",
    tier: "c",
  },
  {
    displayName: "Orbital Smoke Strike",
    type: "Stratagem",
    category: "Orbital",
    tags: ["Orbital"],
    warbond: "None",
    warbondCode: "none",
    internalName: "orbitalsmokestrike",
    imageURL: "orbitalsmokestrike.svg",
    tier: "c",
  },
  {
    displayName: "Tesla Tower",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "teslatower",
    imageURL: "teslatower.svg",
    tier: "b",
  },
  {
    displayName: "Mortar Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "None",
    warbondCode: "none",
    internalName: "mortarsentry",
    imageURL: "mortarsentry.svg",
    tier: "b",
  },
  {
    displayName: "EMS Mortar Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "None",
    warbondCode: "none",
    internalName: "emsmortarsentry",
    imageURL: "emsmortarsentry.svg",
    tier: "c",
  },
  {
    displayName: "Machine Gun Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "None",
    warbondCode: "none",
    internalName: "machinegunsentry",
    imageURL: "machinegunsentry.svg",
    tier: "a",
  },
  {
    displayName: "Gatling Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "None",
    warbondCode: "none",
    internalName: "gatlingsentry",
    imageURL: "gatlingsentry.svg",
    tier: "a",
  },
  {
    displayName: "Flame Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "Urban Legends",
    warbondCode: "warbond12",
    internalName: "aflam40flamesentry",
    imageURL: "aflam40flamesentry.svg",
    tier: "c",
  },
  {
    displayName: "Anti-Personnel Minefield",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "antipersonnelminefield",
    imageURL: "antipersonnelminefield.svg",
    tier: "b",
  },
  {
    displayName: "Gas Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "gasmines",
    imageURL: "gasmines.svg",
    tier: "a",
  },
  {
    displayName: "Incendiary Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "incendiarymines",
    imageURL: "incendiarymines.svg",
    tier: "b",
  },
  {
    displayName: "Shield Generator Relay",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "shieldgeneratorrelay",
    imageURL: "shieldgeneratorrelay.svg",
    tier: "c",
  },
  {
    displayName: "HMG Emplacement",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "hmgemplacement",
    imageURL: "hmgemplacement.svg",
    tier: "a",
  },
  {
    displayName: "Anti-Tank Emplacement",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "Urban Legends",
    warbondCode: "warbond12",
    internalName: "eat12antitankemplacement",
    imageURL: "eat12antitankemplacement.svg",
    tier: "s",
  },
  {
    displayName: "Grenadier Embattlement",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "grenadierembattlement",
    imageURL: "grenadierembattlement.svg",
    tier: "b",
  },
  {
    displayName: "Autocannon Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "None",
    warbondCode: "none",
    internalName: "autocannonsentry",
    imageURL: "autocannonsentry.svg",
    tier: "b",
  },
  {
    displayName: "Rocket Sentry",
    type: "Stratagem",
    category: "Defense",
    tags: ["Sentry"],
    warbond: "None",
    warbondCode: "none",
    internalName: "rocketsentry",
    imageURL: "rocketsentry.svg",
    tier: "a",
  },
  {
    displayName: "Anti-Tank Mines",
    type: "Stratagem",
    category: "Defense",
    tags: ["Emplacement"],
    warbond: "None",
    warbondCode: "none",
    internalName: "antitankmines",
    imageURL: "antitankmines.svg",
    tier: "b",
  },
];

// s: 11
// a: 22
// b: 26
// c: 9
