const SPECOPSSPECS = [
  {
    displayName: "The Helldiver",
    stratagems: [50, 44, 65, 5],
    primary: 0,
    secondary: 0,
    throwable: 0,
    armorPassive: 5,
    warbonds: [],
    deaths: 0,
    booster: 0,
    minutes: 0,
    extraStrats: 2,
    stims: 0,
  },
  {
    displayName: "The Arsonist",
    stratagems: [1, 27, 46, 61, 67],
    primary: 20,
    secondary: 18,
    throwable: 4,
    armorPassive: 7,
    warbonds: ["warbond9", "warbond12", "warbond4", "warbond21"],
    deaths: 2,
    booster: 0,
    minutes: 0,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Engineer",
    stratagems: [70, 17, 71, 63],
    primary: 12,
    secondary: 9,
    throwable: 9,
    armorPassive: 4,
    warbonds: ["warbond1", "warbond13", "warbond20"],
    deaths: 0,
    booster: 1,
    minutes: 1,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Tankbuster",
    stratagems: [25, 48, 55, 75],
    primary: 41,
    secondary: 19,
    throwable: 6,
    armorPassive: 6,
    warbonds: ["warbond6", "warbond13", "warbond6"],
    deaths: 1,
    booster: 0,
    minutes: 0,
    extraStrats: 1,
    stims: 0,
  },
  {
    displayName: "The Demoman",
    stratagems: [8, 45, 39, 76, 26], // 81 belt fed grenade launcher, 26 c4 pack
    primary: 42,
    secondary: 0,
    throwable: 15,
    armorPassive: 14,
    warbonds: ["warbond13", "warbond6", "warbond20", "warbond13"],
    deaths: 0,
    booster: 1,
    minutes: 1,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Ghost",
    stratagems: [53, 47, 10, 33],
    primary: 27,
    secondary: 17,
    throwable: 8,
    armorPassive: 10,
    warbonds: ["warbond14", "warbond8"],
    deaths: 1,
    booster: 0,
    minutes: 1,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Paramedic",
    stratagems: [47, 71, 35, 40],
    primary: 2,
    secondary: 11,
    throwable: 18,
    armorPassive: 8,
    warbonds: ["warbond4", "warbond10", "warbond23"],
    deaths: 0,
    booster: 0,
    minutes: 0,
    extraStrats: 0,
    stims: 2,
  },
  {
    displayName: "The Peace Officer",
    stratagems: [38, 9, 74, 40],
    primary: 6,
    secondary: 4,
    throwable: 12,
    armorPassive: 17,
    warbonds: ["warbond16", "warbond1", "warbond10"],
    deaths: 1,
    booster: 0,
    minutes: 0,
    extraStrats: 0,
    stims: 1,
  },
  {
    displayName: "The Overwatch",
    stratagems: [35, 6, 73, 49],
    primary: 1,
    secondary: 14,
    throwable: 6,
    armorPassive: 4,
    warbonds: ["warbond12", "warbond6"],
    deaths: 0,
    booster: 1,
    minutes: 0,
    extraStrats: 1,
    stims: 0,
  },
  {
    displayName: "The Heavy Gunner",
    stratagems: [6, 72, 57, 30],
    primary: 4,
    secondary: 7,
    throwable: 1,
    armorPassive: 13,
    warbonds: ["warbond6", "warbond7", "warbond12"],
    deaths: 0,
    booster: 1,
    minutes: 0,
    extraStrats: 0,
    stims: 1,
  },
  {
    displayName: "The Lightshow",
    stratagems: [3, 56, 29, 68],
    primary: 33,
    secondary: 16,
    throwable: 11,
    armorPassive: 12,
    warbonds: ["warbond17", "warbond5", "warbond15", "warbond11"],
    deaths: 0,
    booster: 0,
    minutes: 1,
    extraStrats: 0,
    stims: 1,
  },
  {
    displayName: "The Stormcaller",
    stratagems: [7, 31, 62, 52],
    primary: 38,
    secondary: 0,
    throwable: 14,
    armorPassive: 3,
    warbonds: ["warbond16", "warbond17", "warbond5"],
    deaths: 0,
    booster: 0,
    minutes: 2,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Mad Scientist",
    stratagems: [13, 34, 56, 62],
    primary: 37,
    secondary: 12,
    throwable: 14,
    armorPassive: 18,
    warbonds: ["warbond17", "warbond5", "warbond11", "warbond15"],
    deaths: 1,
    booster: 0,
    minutes: 0,
    extraStrats: 0,
    stims: 1,
  },
  {
    displayName: "The Lone Penant",
    stratagems: [18, 52, 53, 47],
    primary: 32,
    secondary: 1,
    throwable: 8,
    armorPassive: 14,
    warbonds: ["warbond15", "warbond1", "warbond8", "warbond13"],
    deaths: 0,
    booster: 2,
    minutes: 0,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Wall",
    stratagems: [72, 73, 74, 36],
    primary: 13,
    secondary: 12,
    throwable: 13,
    armorPassive: 5,
    warbonds: ["warbond12", "warbond7", "warbond11", "warbond16"],
    deaths: 0,
    booster: 1,
    minutes: 0,
    extraStrats: 0,
    stims: 1,
  },
  {
    displayName: "The Supplier",
    stratagems: [35, 14, 16, 7],
    primary: 34,
    secondary: 11,
    throwable: 11,
    armorPassive: 8,
    warbonds: ["warbond10", "warbond15", "warbond20"],
    deaths: 0,
    booster: 0,
    minutes: 0,
    extraStrats: 2,
    stims: 0,
  },
  {
    displayName: "Vanguard",
    stratagems: [40, 41, 82, 79], // frv, patriot, bastion, hammer
    primary: 36, // purifier
    secondary: 12, // loyalist
    throwable: 6, // thermite
    armorPassive: 4, // engineering kit
    warbonds: ["warbond23", "warbond7", "warbond6"],
    deaths: 0,
    booster: 0,
    minutes: 2,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Recon Operative",
    stratagems: [44, 41, 32, 10],
    primary: 17,
    secondary: 10,
    throwable: 3,
    armorPassive: 19,
    warbonds: ["warbond19"],
    deaths: 0,
    booster: 1,
    minutes: 1,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Expendable",
    stratagems: [14, 16, 15, 39, 17, 80], // 80 leveller
    primary: 22,
    secondary: 17,
    throwable: 4,
    armorPassive: 14,
    warbonds: ["warbond13", "warbond20", "warbond14", "warbond4"],
    deaths: 1,
    booster: 0,
    minutes: 0,
    extraStrats: 0,
    stims: 1,
  },
  {
    displayName: "Field Artillery",
    stratagems: [63, 64, 60, 23],
    primary: 24,
    secondary: 7,
    throwable: 9,
    armorPassive: 4,
    warbonds: ["warbond7", "warbond13"],
    deaths: 0,
    booster: 1,
    minutes: 0,
    extraStrats: 1,
    stims: 0,
  },
  {
    displayName: "The Assassin",
    stratagems: [34, 55, 48, 76],
    primary: 31,
    secondary: 2,
    throwable: 17,
    armorPassive: 22,
    warbonds: ["warbond22", "warbond15", "warbond17", "warbond1"],
    deaths: 2,
    booster: 0,
    minutes: 0,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Saboteur",
    stratagems: [26, 39, 75, 56],
    primary: 11,
    secondary: 15,
    throwable: 10,
    armorPassive: 22,
    warbonds: ["warbond22", "warbond13", "warbond14"],
    deaths: 1,
    booster: 0,
    minutes: 1,
    extraStrats: 0,
    stims: 0,
  },
  {
    displayName: "The Juggernaut",
    stratagems: [37, 79, 66, 54], // shield generator pack, breaching hammer, gatling sentry, orbital airburst strike
    primary: 35, // scorcher
    secondary: 13, // bushwhacker
    throwable: 0, // HE grenade
    armorPassive: 23, // supplemental adrenaline
    warbonds: ["warbond23", "warbond8"],
    deaths: 0,
    booster: 0,
    minutes: 0,
    extraStrats: 1,
    stims: 1,
  },
  {
    displayName: "The Counter Sniper",
    stratagems: [25, 17, 70, 73], // spear, solo silo, rocket sentry, anti-tank emplacement
    primary: 28, // "Diligence Counter Sniper"
    secondary: 10, // "SOCOM"
    throwable: 18, // "energy shield grenade"
    armorPassive: 10, // "Scout"
    warbonds: ["warbond20", "warbond12", "warbond19", "warbond23"],
    deaths: 0,
    booster: 0,
    minutes: 1,
    extraStrats: 1,
    stims: 0,
  },
  {
    displayName: "The Devil Dog",
    stratagems: [
      84, // Cremator,
      54, // Orbital Airburst Strike,
      44, // Eagle Airstrike,
      82, // "TD-220 Bastion",
    ],
    primary: 48, // Sweeper
    secondary: 20, // Veto
    throwable: 12, // Gas grenade
    armorPassive: 24, // Concussive Padding
    warbonds: ["warbond24", "warbond1", "warbond10"],
    deaths: 1,
    booster: 0,
    minutes: 0,
    extraStrats: 1,
    stims: 0,
  },
];
