const THROWABLES = [
  {
    displayName: "G-12 High Explosive",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "none",
    internalName: "g12highexplosivegrenade",
    imageURL: "g12highexplosivegrenade.png",
    tier: "a",
  },
  {
    displayName: "G-4 Gas",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond10",
    internalName: "g4gasgrenade",
    imageURL: "g4gasgrenade.png",
    tier: "s",
  },
  {
    displayName: "K-2 Throwing Knife",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond8",
    internalName: "k2throwingknife",
    imageURL: "k2throwingknife.png",
    tier: "c",
  },
  {
    displayName: "G-6 Frag",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond3",
    internalName: "g6fraggrenade",
    imageURL: "g6fraggrenade.png",
    tier: "b",
  },
  {
    displayName: "G-16 Impact",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond3",
    internalName: "g16impactgrenade",
    imageURL: "g16impactgrenade.png",
    tier: "a",
  },
  {
    displayName: "G-3 Smoke",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond3",
    internalName: "g3smokegrenade",
    imageURL: "g3smokegrenade.png",
    tier: "c",
  },
  {
    displayName: "G-10 Incendiary",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond4",
    internalName: "g10incendiarygrenade",
    imageURL: "g10incendiarygrenade.png",
    tier: "b",
  },
  {
    displayName: "G-23 Stun",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond5",
    internalName: "g23stungrenade",
    imageURL: "g23stungrenade.png",
    tier: "a",
  },
  {
    displayName: "G-123 Thermite",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond6",
    internalName: "g123thermitegrenade",
    imageURL: "g123thermitegrenade.png",
    tier: "a",
  },
  {
    displayName: "G-13 Incendiary Impact",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond7",
    internalName: "g13incendiaryimpact",
    imageURL: "g13incendiaryimpact.png",
    tier: "b",
  },
  {
    displayName: "G-50 Seeker",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond13",
    internalName: "g50seeker",
    imageURL: "g50seeker.png",
    tier: "a",
  },
  {
    displayName: "Dynamite",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond14",
    internalName: "ted63throwabledynamite",
    imageURL: "ted63throwabledynamite.png",
    tier: "b",
  },
  {
    displayName: "G-142 Pyrotech",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond15",
    internalName: "g142pyrotech",
    imageURL: "g142pyrotech.png",
    tier: "s",
  },
  {
    displayName: "G-109 Urchin",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond16",
    internalName: "g109urchin",
    imageURL: "g109urchin.png",
    tier: "b",
  },
  {
    displayName: "G-31 Arc",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbondCode: "warbond17",
    internalName: "g31arc",
    imageURL: "g31arc.png",
    tier: "b",
  },

  // {
  //   displayName: "G-7 Pineapple",
  //   type: "Equipment",
  //   category: "throwable",
  //   tags: [],
  //   warbondCode: "warbond20",
  //   internalName: "g7pineapple",
  //   imageURL: "g7pineapple.png",
  //   tier: "b",
  // },
];

// s: 2
// a: 6
// b: 5
// c: 2
