const THROWABLES = [
  {
    displayName: 'G-12 High Explosive',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'none',
    internalName: 'g12highexplosivegrenade',
    imageURL: 'g12highexplosivegrenade.png',
    antitank: false,
    index: 0,
    tier: 'a',
  },
  {
    displayName: 'G-6 Frag',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'g6fraggrenade',
    imageURL: 'g6fraggrenade.png',
    antitank: false,
    index: 1,
    tier: 'b',
  },
  {
    displayName: 'G-16 Impact',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'g16impactgrenade',
    imageURL: 'g16impactgrenade.png',
    antitank: false,
    index: 2,
    tier: 'a',
  },
  {
    displayName: 'G-3 Smoke',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond3',
    internalName: 'g3smokegrenade',
    imageURL: 'g3smokegrenade.png',
    antitank: false,
    index: 3,
    tier: 'c',
  },
  {
    displayName: 'G-10 Incendiary',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond4',
    internalName: 'g10incendiarygrenade',
    imageURL: 'g10incendiarygrenade.png',
    antitank: false,
    index: 4,
    tier: 'b',
  },
  {
    displayName: 'G-23 Stun',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond5',
    internalName: 'g23stungrenade',
    imageURL: 'g23stungrenade.png',
    antitank: false,
    index: 5,
    tier: 'a',
  },
  {
    displayName: 'G-123 Thermite',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond6',
    internalName: 'g123thermitegrenade',
    imageURL: 'g123thermitegrenade.png',
    antitank: true,
    index: 6,
    tier: 's',
  },
  {
    displayName: 'G-13 Incendiary Impact',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond7',
    internalName: 'g13incendiaryimpact',
    imageURL: 'g13incendiaryimpact.png',
    antitank: false,
    index: 7,
    tier: 'b',
  },
  {
    displayName: 'K-2 Throwing Knife',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond8',
    internalName: 'k2throwingknife',
    imageURL: 'k2throwingknife.png',
    antitank: false,
    index: 8,
    tier: 'c',
  },
  {
    displayName: 'G-50 Seeker',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond13',
    internalName: 'g50seeker',
    imageURL: 'g50seeker.png',
    antitank: false,
    index: 9,
    tier: 'a',
  },
  {
    displayName: 'Dynamite',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond14',
    internalName: 'ted63throwabledynamite',
    imageURL: 'ted63throwabledynamite.png',
    antitank: true,
    index: 10,
    tier: 'a',
  },
  {
    displayName: 'G-142 Pyrotech',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond15',
    internalName: 'g142pyrotech',
    imageURL: 'g142pyrotech.png',
    antitank: false,
    index: 11,
    tier: 's',
  },
  {
    displayName: 'G-4 Gas',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond10',
    internalName: 'g4gasgrenade',
    imageURL: 'g4gasgrenade.png',
    antitank: false,
    index: 12,
    tier: 's',
  },
  {
    displayName: 'G-109 Urchin',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond16',
    internalName: 'g109urchin',
    imageURL: 'g109urchin.png',
    antitank: false,
    index: 13,
    tier: 'b',
  },
  {
    displayName: 'G-31 Arc',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond17',
    internalName: 'g31arc',
    imageURL: 'g31arc.png',
    antitank: false,
    index: 14,
    tier: 'b',
  },
  {
    displayName: 'G-7 Pineapple',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond20',
    internalName: 'g7pineapple',
    imageURL: 'g7pineapple.png',
    antitank: false,
    index: 15,
    tier: 'b',
  },
  {
    displayName: 'TM-01 Lure Mine',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond22',
    internalName: 'tm01luremine',
    imageURL: 'tm01luremine.webp',
    antitank: false,
    index: 16,
    tier: 'b',
  },
  {
    displayName: 'G-89 Smokescreen',
    type: 'Equipment',
    category: 'throwable',
    tags: [],
    warbondCode: 'warbond1',
    internalName: 'g89smokescreen',
    imageURL: 'g89smokescreen.png',
    antitank: false,
    index: 17,
    tier: 'c',
  },
];

// s: 3
// a: 5
// b: 7
// c: 3
