const THROWABLES = [
  {
    displayName: "G-12 High Explosive",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "None",
    warbondCode: "none",
    internalName: "g12highexplosivegrenade",
    imageURL: "g12highexplosivegrenade.png",
    tier: "a",
  },
  {
    displayName: "G-4 Gas",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Chemical Agents",
    warbondCode: "warbond10",
    internalName: "g4gasgrenade",
    imageURL: "g4gasgrenade.png",
    tier: "s",
  },
  {
    displayName: "K-2 Throwing Knife",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Viper Commandos",
    warbondCode: "warbond8",
    internalName: "k2throwingknife",
    imageURL: "k2throwingknife.png",
    tier: "c",
  },
  {
    displayName: "G-6 Frag",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Helldivers Mobilize",
    warbondCode: "warbond3",
    internalName: "g6fraggrenade",
    imageURL: "g6fraggrenade.png",
    tier: "b",
  },
  {
    displayName: "G-16 Impact",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Helldivers Mobilize",
    warbondCode: "warbond3",
    internalName: "g16impactgrenade",
    imageURL: "g16impactgrenade.png",
    tier: "a",
  },
  {
    displayName: "G-3 Smoke",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Helldivers Mobilize",
    warbondCode: "warbond3",
    internalName: "g3smokegrenade",
    imageURL: "g3smokegrenade.png",
    tier: "c",
  },
  {
    displayName: "G-10 Incendiary",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Steeled Veterans",
    warbondCode: "warbond4",
    internalName: "g10incendiarygrenade",
    imageURL: "g10incendiarygrenade.png",
    tier: "b",
  },
  {
    displayName: "G-23 Stun",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Cutting Edge",
    warbondCode: "warbond5",
    internalName: "g23stungrenade",
    imageURL: "g23stungrenade.png",
    tier: "a",
  },
  {
    displayName: "G-123 Thermite",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Democratic Detonation",
    warbondCode: "warbond6",
    internalName: "g123thermitegrenade",
    imageURL: "g123thermitegrenade.png",
    tier: "a",
  },
  {
    displayName: "G-13 Incendiary Impact",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Polar Patriots",
    warbondCode: "warbond7",
    internalName: "g13incendiaryimpact",
    imageURL: "g13incendiaryimpact.png",
    tier: "b",
  },
  {
    displayName: "G-50 Seeker",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Servants of Freedom",
    warbondCode: "warbond13",
    internalName: "g50seeker",
    imageURL: "g50seeker.png",
    tier: "a",
  },
  {
    displayName: "Throwable Dynamite",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Borderline Justice",
    warbondCode: "warbond14",
    internalName: "ted63throwabledynamite",
    imageURL: "ted63throwabledynamite.png",
    tier: "b",
  },
  {
    displayName: "G-142 Pyrotech",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Masters of Ceremony",
    warbondCode: "warbond15",
    internalName: "g142pyrotech",
    imageURL: "g142pyrotech.png",
    tier: "s",
  },
  {
    displayName: "G-109 Urchin",
    type: "Equipment",
    category: "throwable",
    tags: [],
    warbond: "Force of Law",
    warbondCode: "warbond16",
    internalName: "g109urchin",
    imageURL: "g109urchin.png",
    tier: "b",
  },
];

// s: 2
// a: 5
// b: 5
// c: 2
