const WARBONDS = [
  {
    displayName: "Helldivers Mobilize",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond3",
    internalName: "helldiversMobilizeWB",
    imageURL: "helldiversMobilizeWB.png",
    tier: "s",
  },
  {
    displayName: "Steeled Veterans",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond4",
    internalName: "steeledVeteransWB",
    imageURL: "steeledVeteransWB.png",
    tier: "a",
  },
  {
    displayName: "Cutting Edge",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond5",
    internalName: "cuttingEdgeWB",
    imageURL: "cuttingEdgeWB.png",
    tier: "a",
  },
  {
    displayName: "Democratic Detonation",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond6",
    internalName: "democraticDetonationWB",
    imageURL: "democraticDetonationWB.png",
    tier: "s",
  },
  {
    displayName: "Polar Patriots",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond7",
    internalName: "polarPatriotsWB",
    imageURL: "polarPatriotsWB.png",
    tier: "b",
  },
  {
    displayName: "Viper Commandos",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond8",
    internalName: "viperCommandosWB",
    imageURL: "viperCommandosWB.png",
    tier: "b",
  },
  {
    displayName: "Freedom's Flame",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond9",
    internalName: "freedomsFlameWB",
    imageURL: "freedomsFlameWB.png",
    tier: "b",
  },
  {
    displayName: "Chemical Agents",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond10",
    internalName: "chemicalAgentsWB",
    imageURL: "chemicalAgentsWB.png",
    tier: "b",
  },
  {
    displayName: "Truth Enforcers",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond11",
    internalName: "truthEnforcersWB",
    imageURL: "truthEnforcersWB.png",
    tier: "b",
  },
  {
    displayName: "Urban Legends",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond12",
    internalName: "urbanLegendsWB",
    imageURL: "urbanLegendsWB.png",
    tier: "b",
  },
  {
    displayName: "Servants of Freedom",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond13",
    internalName: "servantsOfFreedomWB",
    imageURL: "servantsOfFreedomWB.png",
    tier: "a",
  },
  {
    displayName: "Borderline Justice",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond14",
    internalName: "borderlineJusticeWB",
    imageURL: "borderlineJusticeWB.png",
    tier: "b",
  },
  {
    displayName: "Masters of Ceremony",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond15",
    internalName: "mastersOfCeremonyWB",
    imageURL: "mastersOfCeremonyWB.png",
    tier: "c",
  },
  {
    displayName: "Force of Law",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond16",
    internalName: "forceOfLawWB",
    imageURL: "forceOfLawWB.png",
    tier: "b",
  },
  {
    displayName: "Control Group",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond17",
    internalName: "controlGroupWB",
    imageURL: "controlGroupWB.png",
    tier: "a",
  },
  {
    displayName: "ODST",
    type: "Warbond",
    category: "",
    tags: [],
    warbondCode: "warbond19",
    internalName: "odstWB",
    imageURL: "odstWB.png",
    tier: "a",
  },
];
