const FE_BOOSTERS = [
  {
    displayName: "Vitality Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "vitalityenhancement",
    imageURL: "vitalityenhancement.png",
    tier: "s",
  },
  {
    displayName: "Muscle Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "muscleenhancement",
    imageURL: "muscleenhancement.png",
    tier: "a",
  },
  {
    displayName: "Stamina Enhancement",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "staminaenhancement",
    imageURL: "staminaenhancement.png",
    tier: "s",
  },
  {
    displayName: "Localization Confusion",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond5",
    internalName: "localizationconfusion",
    imageURL: "localizationconfusion.png",
    tier: "b",
  },
  {
    displayName: "Hellpod Space Optimization",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond3",
    internalName: "hellpodspaceoptimization",
    imageURL: "hellpodspaceoptimization.png",
    tier: "s",
  },
  {
    displayName: "Experimental Infusion",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond8",
    internalName: "experimentalinfusion",
    imageURL: "experimentalinfusion.png",
    tier: "s",
  },
  {
    displayName: "Motivational Shocks",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond7",
    internalName: "motivationalshocks",
    imageURL: "motivationalshocks.png",
    tier: "b",
  },
  {
    displayName: "Expert Extraction Pilot",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond6",
    internalName: "expertextractionpilot",
    imageURL: "expertextractionpilot.png",
    tier: "c",
  },
  {
    displayName: "Dead Sprint",
    type: "Equipment",
    category: "booster",
    tags: [],
    warbondCode: "warbond11",
    internalName: "deadsprint",
    imageURL: "deadsprint.png",
    tier: "b",
  },
];
