const FE_STRATAGEMS = [
  {
    displayName: "Fast Recon Vehicle",
    type: "Stratagem",
    category: "Supply",
    tags: ["Vehicles"],
    warbondCode: "none",
    internalName: "fastreconvehicle",
    imageURL: "fastreconvehicle.svg",
    tier: "a",
  },
  {
    displayName: "Warp Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "warbond17",
    internalName: "warppack",
    imageURL: "warppack.svg",
    tier: "a",
  },
  {
    displayName: "Supply Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "b1supplypack",
    imageURL: "b1supplypack.svg",
    tier: "s",
  },
  {
    displayName: "Jump Pack",
    type: "Stratagem",
    category: "Supply",
    tags: ["Backpacks"],
    warbondCode: "none",
    internalName: "lift850jumppack",
    imageURL: "lift850jumppack.svg",
    tier: "s",
  },
];
